// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: cc/arduino/cli/commands/v1/compile.proto

package commands

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompileRequest struct {
	state                                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance                      *Instance              `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	xxx_hidden_Fqbn                          *string                `protobuf:"bytes,2,opt,name=fqbn" json:"fqbn,omitempty"`
	xxx_hidden_SketchPath                    *string                `protobuf:"bytes,3,opt,name=sketch_path,json=sketchPath" json:"sketch_path,omitempty"`
	xxx_hidden_ShowProperties                bool                   `protobuf:"varint,4,opt,name=show_properties,json=showProperties" json:"show_properties,omitempty"`
	xxx_hidden_Preprocess                    bool                   `protobuf:"varint,5,opt,name=preprocess" json:"preprocess,omitempty"`
	xxx_hidden_BuildCachePath                *string                `protobuf:"bytes,6,opt,name=build_cache_path,json=buildCachePath" json:"build_cache_path,omitempty"`
	xxx_hidden_BuildPath                     *string                `protobuf:"bytes,7,opt,name=build_path,json=buildPath" json:"build_path,omitempty"`
	xxx_hidden_BuildProperties               []string               `protobuf:"bytes,8,rep,name=build_properties,json=buildProperties" json:"build_properties,omitempty"`
	xxx_hidden_Warnings                      *string                `protobuf:"bytes,9,opt,name=warnings" json:"warnings,omitempty"`
	xxx_hidden_Verbose                       bool                   `protobuf:"varint,10,opt,name=verbose" json:"verbose,omitempty"`
	xxx_hidden_Quiet                         bool                   `protobuf:"varint,11,opt,name=quiet" json:"quiet,omitempty"`
	xxx_hidden_Jobs                          int32                  `protobuf:"varint,14,opt,name=jobs" json:"jobs,omitempty"`
	xxx_hidden_Libraries                     []string               `protobuf:"bytes,15,rep,name=libraries" json:"libraries,omitempty"`
	xxx_hidden_OptimizeForDebug              bool                   `protobuf:"varint,16,opt,name=optimize_for_debug,json=optimizeForDebug" json:"optimize_for_debug,omitempty"`
	xxx_hidden_ExportDir                     *string                `protobuf:"bytes,18,opt,name=export_dir,json=exportDir" json:"export_dir,omitempty"`
	xxx_hidden_Clean                         bool                   `protobuf:"varint,19,opt,name=clean" json:"clean,omitempty"`
	xxx_hidden_CreateCompilationDatabaseOnly bool                   `protobuf:"varint,21,opt,name=create_compilation_database_only,json=createCompilationDatabaseOnly" json:"create_compilation_database_only,omitempty"`
	xxx_hidden_SourceOverride                map[string]string      `protobuf:"bytes,22,rep,name=source_override,json=sourceOverride" json:"source_override,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_ExportBinaries                bool                   `protobuf:"varint,23,opt,name=export_binaries,json=exportBinaries" json:"export_binaries,omitempty"`
	xxx_hidden_Library                       []string               `protobuf:"bytes,24,rep,name=library" json:"library,omitempty"`
	xxx_hidden_KeysKeychain                  *string                `protobuf:"bytes,25,opt,name=keys_keychain,json=keysKeychain" json:"keys_keychain,omitempty"`
	xxx_hidden_SignKey                       *string                `protobuf:"bytes,26,opt,name=sign_key,json=signKey" json:"sign_key,omitempty"`
	xxx_hidden_EncryptKey                    *string                `protobuf:"bytes,27,opt,name=encrypt_key,json=encryptKey" json:"encrypt_key,omitempty"`
	xxx_hidden_SkipLibrariesDiscovery        bool                   `protobuf:"varint,28,opt,name=skip_libraries_discovery,json=skipLibrariesDiscovery" json:"skip_libraries_discovery,omitempty"`
	xxx_hidden_DoNotExpandBuildProperties    bool                   `protobuf:"varint,29,opt,name=do_not_expand_build_properties,json=doNotExpandBuildProperties" json:"do_not_expand_build_properties,omitempty"`
	xxx_hidden_BuildCacheExtraPaths          []string               `protobuf:"bytes,30,rep,name=build_cache_extra_paths,json=buildCacheExtraPaths" json:"build_cache_extra_paths,omitempty"`
	XXX_raceDetectHookData                   protoimpl.RaceDetectHookData
	XXX_presence                             [1]uint32
	unknownFields                            protoimpl.UnknownFields
	sizeCache                                protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CompileRequest) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *CompileRequest) GetFqbn() string {
	if x != nil {
		if x.xxx_hidden_Fqbn != nil {
			return *x.xxx_hidden_Fqbn
		}
		return ""
	}
	return ""
}

func (x *CompileRequest) GetSketchPath() string {
	if x != nil {
		if x.xxx_hidden_SketchPath != nil {
			return *x.xxx_hidden_SketchPath
		}
		return ""
	}
	return ""
}

func (x *CompileRequest) GetShowProperties() bool {
	if x != nil {
		return x.xxx_hidden_ShowProperties
	}
	return false
}

func (x *CompileRequest) GetPreprocess() bool {
	if x != nil {
		return x.xxx_hidden_Preprocess
	}
	return false
}

// Deprecated: Marked as deprecated in cc/arduino/cli/commands/v1/compile.proto.
func (x *CompileRequest) GetBuildCachePath() string {
	if x != nil {
		if x.xxx_hidden_BuildCachePath != nil {
			return *x.xxx_hidden_BuildCachePath
		}
		return ""
	}
	return ""
}

func (x *CompileRequest) GetBuildPath() string {
	if x != nil {
		if x.xxx_hidden_BuildPath != nil {
			return *x.xxx_hidden_BuildPath
		}
		return ""
	}
	return ""
}

func (x *CompileRequest) GetBuildProperties() []string {
	if x != nil {
		return x.xxx_hidden_BuildProperties
	}
	return nil
}

func (x *CompileRequest) GetWarnings() string {
	if x != nil {
		if x.xxx_hidden_Warnings != nil {
			return *x.xxx_hidden_Warnings
		}
		return ""
	}
	return ""
}

func (x *CompileRequest) GetVerbose() bool {
	if x != nil {
		return x.xxx_hidden_Verbose
	}
	return false
}

func (x *CompileRequest) GetQuiet() bool {
	if x != nil {
		return x.xxx_hidden_Quiet
	}
	return false
}

func (x *CompileRequest) GetJobs() int32 {
	if x != nil {
		return x.xxx_hidden_Jobs
	}
	return 0
}

func (x *CompileRequest) GetLibraries() []string {
	if x != nil {
		return x.xxx_hidden_Libraries
	}
	return nil
}

func (x *CompileRequest) GetOptimizeForDebug() bool {
	if x != nil {
		return x.xxx_hidden_OptimizeForDebug
	}
	return false
}

func (x *CompileRequest) GetExportDir() string {
	if x != nil {
		if x.xxx_hidden_ExportDir != nil {
			return *x.xxx_hidden_ExportDir
		}
		return ""
	}
	return ""
}

func (x *CompileRequest) GetClean() bool {
	if x != nil {
		return x.xxx_hidden_Clean
	}
	return false
}

func (x *CompileRequest) GetCreateCompilationDatabaseOnly() bool {
	if x != nil {
		return x.xxx_hidden_CreateCompilationDatabaseOnly
	}
	return false
}

func (x *CompileRequest) GetSourceOverride() map[string]string {
	if x != nil {
		return x.xxx_hidden_SourceOverride
	}
	return nil
}

func (x *CompileRequest) GetExportBinaries() bool {
	if x != nil {
		return x.xxx_hidden_ExportBinaries
	}
	return false
}

func (x *CompileRequest) GetLibrary() []string {
	if x != nil {
		return x.xxx_hidden_Library
	}
	return nil
}

func (x *CompileRequest) GetKeysKeychain() string {
	if x != nil {
		if x.xxx_hidden_KeysKeychain != nil {
			return *x.xxx_hidden_KeysKeychain
		}
		return ""
	}
	return ""
}

func (x *CompileRequest) GetSignKey() string {
	if x != nil {
		if x.xxx_hidden_SignKey != nil {
			return *x.xxx_hidden_SignKey
		}
		return ""
	}
	return ""
}

func (x *CompileRequest) GetEncryptKey() string {
	if x != nil {
		if x.xxx_hidden_EncryptKey != nil {
			return *x.xxx_hidden_EncryptKey
		}
		return ""
	}
	return ""
}

func (x *CompileRequest) GetSkipLibrariesDiscovery() bool {
	if x != nil {
		return x.xxx_hidden_SkipLibrariesDiscovery
	}
	return false
}

func (x *CompileRequest) GetDoNotExpandBuildProperties() bool {
	if x != nil {
		return x.xxx_hidden_DoNotExpandBuildProperties
	}
	return false
}

func (x *CompileRequest) GetBuildCacheExtraPaths() []string {
	if x != nil {
		return x.xxx_hidden_BuildCacheExtraPaths
	}
	return nil
}

func (x *CompileRequest) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *CompileRequest) SetFqbn(v string) {
	x.xxx_hidden_Fqbn = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 26)
}

func (x *CompileRequest) SetSketchPath(v string) {
	x.xxx_hidden_SketchPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 26)
}

func (x *CompileRequest) SetShowProperties(v bool) {
	x.xxx_hidden_ShowProperties = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 26)
}

func (x *CompileRequest) SetPreprocess(v bool) {
	x.xxx_hidden_Preprocess = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 26)
}

// Deprecated: Marked as deprecated in cc/arduino/cli/commands/v1/compile.proto.
func (x *CompileRequest) SetBuildCachePath(v string) {
	x.xxx_hidden_BuildCachePath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 26)
}

func (x *CompileRequest) SetBuildPath(v string) {
	x.xxx_hidden_BuildPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 26)
}

func (x *CompileRequest) SetBuildProperties(v []string) {
	x.xxx_hidden_BuildProperties = v
}

func (x *CompileRequest) SetWarnings(v string) {
	x.xxx_hidden_Warnings = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 26)
}

func (x *CompileRequest) SetVerbose(v bool) {
	x.xxx_hidden_Verbose = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 26)
}

func (x *CompileRequest) SetQuiet(v bool) {
	x.xxx_hidden_Quiet = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 26)
}

func (x *CompileRequest) SetJobs(v int32) {
	x.xxx_hidden_Jobs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 26)
}

func (x *CompileRequest) SetLibraries(v []string) {
	x.xxx_hidden_Libraries = v
}

func (x *CompileRequest) SetOptimizeForDebug(v bool) {
	x.xxx_hidden_OptimizeForDebug = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 26)
}

func (x *CompileRequest) SetExportDir(v string) {
	x.xxx_hidden_ExportDir = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 26)
}

func (x *CompileRequest) SetClean(v bool) {
	x.xxx_hidden_Clean = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 26)
}

func (x *CompileRequest) SetCreateCompilationDatabaseOnly(v bool) {
	x.xxx_hidden_CreateCompilationDatabaseOnly = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 16, 26)
}

func (x *CompileRequest) SetSourceOverride(v map[string]string) {
	x.xxx_hidden_SourceOverride = v
}

func (x *CompileRequest) SetExportBinaries(v bool) {
	x.xxx_hidden_ExportBinaries = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 18, 26)
}

func (x *CompileRequest) SetLibrary(v []string) {
	x.xxx_hidden_Library = v
}

func (x *CompileRequest) SetKeysKeychain(v string) {
	x.xxx_hidden_KeysKeychain = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 20, 26)
}

func (x *CompileRequest) SetSignKey(v string) {
	x.xxx_hidden_SignKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 21, 26)
}

func (x *CompileRequest) SetEncryptKey(v string) {
	x.xxx_hidden_EncryptKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 22, 26)
}

func (x *CompileRequest) SetSkipLibrariesDiscovery(v bool) {
	x.xxx_hidden_SkipLibrariesDiscovery = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 23, 26)
}

func (x *CompileRequest) SetDoNotExpandBuildProperties(v bool) {
	x.xxx_hidden_DoNotExpandBuildProperties = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 24, 26)
}

func (x *CompileRequest) SetBuildCacheExtraPaths(v []string) {
	x.xxx_hidden_BuildCacheExtraPaths = v
}

func (x *CompileRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *CompileRequest) HasFqbn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CompileRequest) HasSketchPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CompileRequest) HasShowProperties() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CompileRequest) HasPreprocess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

// Deprecated: Marked as deprecated in cc/arduino/cli/commands/v1/compile.proto.
func (x *CompileRequest) HasBuildCachePath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *CompileRequest) HasBuildPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *CompileRequest) HasWarnings() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *CompileRequest) HasVerbose() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *CompileRequest) HasQuiet() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *CompileRequest) HasJobs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *CompileRequest) HasOptimizeForDebug() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *CompileRequest) HasExportDir() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *CompileRequest) HasClean() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *CompileRequest) HasCreateCompilationDatabaseOnly() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 16)
}

func (x *CompileRequest) HasExportBinaries() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 18)
}

func (x *CompileRequest) HasKeysKeychain() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 20)
}

func (x *CompileRequest) HasSignKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 21)
}

func (x *CompileRequest) HasEncryptKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 22)
}

func (x *CompileRequest) HasSkipLibrariesDiscovery() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 23)
}

func (x *CompileRequest) HasDoNotExpandBuildProperties() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 24)
}

func (x *CompileRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

func (x *CompileRequest) ClearFqbn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Fqbn = nil
}

func (x *CompileRequest) ClearSketchPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SketchPath = nil
}

func (x *CompileRequest) ClearShowProperties() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ShowProperties = false
}

func (x *CompileRequest) ClearPreprocess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Preprocess = false
}

// Deprecated: Marked as deprecated in cc/arduino/cli/commands/v1/compile.proto.
func (x *CompileRequest) ClearBuildCachePath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_BuildCachePath = nil
}

func (x *CompileRequest) ClearBuildPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_BuildPath = nil
}

func (x *CompileRequest) ClearWarnings() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Warnings = nil
}

func (x *CompileRequest) ClearVerbose() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Verbose = false
}

func (x *CompileRequest) ClearQuiet() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_Quiet = false
}

func (x *CompileRequest) ClearJobs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_Jobs = 0
}

func (x *CompileRequest) ClearOptimizeForDebug() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_OptimizeForDebug = false
}

func (x *CompileRequest) ClearExportDir() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_ExportDir = nil
}

func (x *CompileRequest) ClearClean() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_Clean = false
}

func (x *CompileRequest) ClearCreateCompilationDatabaseOnly() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 16)
	x.xxx_hidden_CreateCompilationDatabaseOnly = false
}

func (x *CompileRequest) ClearExportBinaries() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 18)
	x.xxx_hidden_ExportBinaries = false
}

func (x *CompileRequest) ClearKeysKeychain() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 20)
	x.xxx_hidden_KeysKeychain = nil
}

func (x *CompileRequest) ClearSignKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 21)
	x.xxx_hidden_SignKey = nil
}

func (x *CompileRequest) ClearEncryptKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 22)
	x.xxx_hidden_EncryptKey = nil
}

func (x *CompileRequest) ClearSkipLibrariesDiscovery() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 23)
	x.xxx_hidden_SkipLibrariesDiscovery = false
}

func (x *CompileRequest) ClearDoNotExpandBuildProperties() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 24)
	x.xxx_hidden_DoNotExpandBuildProperties = false
}

type CompileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Arduino Core Service instance from the `Init` response.
	Instance *Instance
	// Fully Qualified Board Name, e.g.: `arduino:avr:uno`. If this field is
	// not defined, the FQBN of the board attached to the sketch via the
	// `BoardAttach` method is used.
	Fqbn *string
	// The path where the sketch is stored.
	SketchPath *string
	// Just get the build properties and do not run the full compile.
	ShowProperties *bool
	// Print preprocessed code to stdout instead of compiling.
	Preprocess *bool
	// Builds of core and sketches are saved into this path to be cached and
	// reused.
	//
	// Deprecated: Marked as deprecated in cc/arduino/cli/commands/v1/compile.proto.
	BuildCachePath *string
	// Path to use to store the files used for the compilation. If omitted,
	// a directory will be created in the operating system's default temporary
	// path.
	BuildPath *string
	// List of custom build properties.
	BuildProperties []string
	// Used to tell gcc which warning level to use. The level names are: "none",
	// "default", "more" and "all".
	Warnings *string
	// Turns on verbose mode.
	Verbose *bool
	// Suppresses almost every output.
	Quiet *bool
	// The max number of concurrent compiler instances to run (as `make -jx`).
	// If jobs is set to 0, it will use the number of available CPUs as the
	// maximum.
	Jobs *int32
	// A list of paths to directories containing a collection of libraries.
	Libraries []string
	// Optimize compile output for debug, not for release.
	OptimizeForDebug *bool
	// Optional: save the build artifacts in this directory, the directory must
	// exist.
	ExportDir *string
	// Optional: cleanup the build folder and do not use any previously cached
	// build.
	Clean *bool
	// When set to `true` only the compilation database will be produced and no
	// actual build will be performed.
	CreateCompilationDatabaseOnly *bool
	// This map (source file -> new content) let the builder use the provided
	// content instead of reading the corresponding file on disk. This is useful
	// for IDE that have unsaved changes in memory. The path must be relative to
	// the sketch directory. Only files from the sketch are allowed.
	SourceOverride map[string]string
	// optional
	ExportBinaries *bool
	// A list of paths to single libraries root directory.
	Library []string
	// The path where to search for the custom signing key name and the encrypt
	// key name.
	KeysKeychain *string
	// The name of the custom key to use for signing during the compile process.
	SignKey *string
	// The name of the custom key to use for encrypting during the compile process.
	EncryptKey *string
	// If set to true the build will skip the library discovery process and will
	// use the same libraries of latest build. Enabling this flag may produce a
	// wrong output and should not be used in regular compiles unless there is a
	// very specific reason to do so. This flag is mainly provided for usage in
	// language servers to optimize the build speed in some particular cases.
	SkipLibrariesDiscovery *bool
	// If set to true the returned build properties will be left unexpanded, with
	// the variables placeholders exactly as defined in the platform.
	DoNotExpandBuildProperties *bool
	// Search for precompiled cores in the given paths and use them if found.
	// This search is performed after the standard build_cache directory.
	BuildCacheExtraPaths []string
}

func (b0 CompileRequest_builder) Build() *CompileRequest {
	m0 := &CompileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	if b.Fqbn != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 26)
		x.xxx_hidden_Fqbn = b.Fqbn
	}
	if b.SketchPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 26)
		x.xxx_hidden_SketchPath = b.SketchPath
	}
	if b.ShowProperties != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 26)
		x.xxx_hidden_ShowProperties = *b.ShowProperties
	}
	if b.Preprocess != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 26)
		x.xxx_hidden_Preprocess = *b.Preprocess
	}
	if b.BuildCachePath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 26)
		x.xxx_hidden_BuildCachePath = b.BuildCachePath
	}
	if b.BuildPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 26)
		x.xxx_hidden_BuildPath = b.BuildPath
	}
	x.xxx_hidden_BuildProperties = b.BuildProperties
	if b.Warnings != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 26)
		x.xxx_hidden_Warnings = b.Warnings
	}
	if b.Verbose != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 26)
		x.xxx_hidden_Verbose = *b.Verbose
	}
	if b.Quiet != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 26)
		x.xxx_hidden_Quiet = *b.Quiet
	}
	if b.Jobs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 26)
		x.xxx_hidden_Jobs = *b.Jobs
	}
	x.xxx_hidden_Libraries = b.Libraries
	if b.OptimizeForDebug != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 26)
		x.xxx_hidden_OptimizeForDebug = *b.OptimizeForDebug
	}
	if b.ExportDir != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 26)
		x.xxx_hidden_ExportDir = b.ExportDir
	}
	if b.Clean != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 26)
		x.xxx_hidden_Clean = *b.Clean
	}
	if b.CreateCompilationDatabaseOnly != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 16, 26)
		x.xxx_hidden_CreateCompilationDatabaseOnly = *b.CreateCompilationDatabaseOnly
	}
	x.xxx_hidden_SourceOverride = b.SourceOverride
	if b.ExportBinaries != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 18, 26)
		x.xxx_hidden_ExportBinaries = *b.ExportBinaries
	}
	x.xxx_hidden_Library = b.Library
	if b.KeysKeychain != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 20, 26)
		x.xxx_hidden_KeysKeychain = b.KeysKeychain
	}
	if b.SignKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 21, 26)
		x.xxx_hidden_SignKey = b.SignKey
	}
	if b.EncryptKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 22, 26)
		x.xxx_hidden_EncryptKey = b.EncryptKey
	}
	if b.SkipLibrariesDiscovery != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 23, 26)
		x.xxx_hidden_SkipLibrariesDiscovery = *b.SkipLibrariesDiscovery
	}
	if b.DoNotExpandBuildProperties != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 24, 26)
		x.xxx_hidden_DoNotExpandBuildProperties = *b.DoNotExpandBuildProperties
	}
	x.xxx_hidden_BuildCacheExtraPaths = b.BuildCacheExtraPaths
	return m0
}

type CompileResponse struct {
	state              protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Message isCompileResponse_Message `protobuf_oneof:"message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CompileResponse) GetOutStream() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*compileResponse_OutStream); ok {
			return x.OutStream
		}
	}
	return nil
}

func (x *CompileResponse) GetErrStream() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*compileResponse_ErrStream); ok {
			return x.ErrStream
		}
	}
	return nil
}

func (x *CompileResponse) GetProgress() *TaskProgress {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*compileResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *CompileResponse) GetResult() *BuilderResult {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*compileResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *CompileResponse) SetOutStream(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Message = &compileResponse_OutStream{v}
}

func (x *CompileResponse) SetErrStream(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Message = &compileResponse_ErrStream{v}
}

func (x *CompileResponse) SetProgress(v *TaskProgress) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &compileResponse_Progress{v}
}

func (x *CompileResponse) SetResult(v *BuilderResult) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &compileResponse_Result{v}
}

func (x *CompileResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *CompileResponse) HasOutStream() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*compileResponse_OutStream)
	return ok
}

func (x *CompileResponse) HasErrStream() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*compileResponse_ErrStream)
	return ok
}

func (x *CompileResponse) HasProgress() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*compileResponse_Progress)
	return ok
}

func (x *CompileResponse) HasResult() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*compileResponse_Result)
	return ok
}

func (x *CompileResponse) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *CompileResponse) ClearOutStream() {
	if _, ok := x.xxx_hidden_Message.(*compileResponse_OutStream); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *CompileResponse) ClearErrStream() {
	if _, ok := x.xxx_hidden_Message.(*compileResponse_ErrStream); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *CompileResponse) ClearProgress() {
	if _, ok := x.xxx_hidden_Message.(*compileResponse_Progress); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *CompileResponse) ClearResult() {
	if _, ok := x.xxx_hidden_Message.(*compileResponse_Result); ok {
		x.xxx_hidden_Message = nil
	}
}

const CompileResponse_Message_not_set_case case_CompileResponse_Message = 0
const CompileResponse_OutStream_case case_CompileResponse_Message = 1
const CompileResponse_ErrStream_case case_CompileResponse_Message = 2
const CompileResponse_Progress_case case_CompileResponse_Message = 3
const CompileResponse_Result_case case_CompileResponse_Message = 4

func (x *CompileResponse) WhichMessage() case_CompileResponse_Message {
	if x == nil {
		return CompileResponse_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *compileResponse_OutStream:
		return CompileResponse_OutStream_case
	case *compileResponse_ErrStream:
		return CompileResponse_ErrStream_case
	case *compileResponse_Progress:
		return CompileResponse_Progress_case
	case *compileResponse_Result:
		return CompileResponse_Result_case
	default:
		return CompileResponse_Message_not_set_case
	}
}

type CompileResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Message:
	// The output of the compilation process (stream).
	OutStream []byte
	// The error output of the compilation process (stream).
	ErrStream []byte
	// Completions reports of the compilation process (stream).
	Progress *TaskProgress
	// The compilation result.
	Result *BuilderResult
	// -- end of xxx_hidden_Message
}

func (b0 CompileResponse_builder) Build() *CompileResponse {
	m0 := &CompileResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.OutStream != nil {
		x.xxx_hidden_Message = &compileResponse_OutStream{b.OutStream}
	}
	if b.ErrStream != nil {
		x.xxx_hidden_Message = &compileResponse_ErrStream{b.ErrStream}
	}
	if b.Progress != nil {
		x.xxx_hidden_Message = &compileResponse_Progress{b.Progress}
	}
	if b.Result != nil {
		x.xxx_hidden_Message = &compileResponse_Result{b.Result}
	}
	return m0
}

type case_CompileResponse_Message protoreflect.FieldNumber

func (x case_CompileResponse_Message) String() string {
	md := file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isCompileResponse_Message interface {
	isCompileResponse_Message()
}

type compileResponse_OutStream struct {
	// The output of the compilation process (stream).
	OutStream []byte `protobuf:"bytes,1,opt,name=out_stream,json=outStream,oneof"`
}

type compileResponse_ErrStream struct {
	// The error output of the compilation process (stream).
	ErrStream []byte `protobuf:"bytes,2,opt,name=err_stream,json=errStream,oneof"`
}

type compileResponse_Progress struct {
	// Completions reports of the compilation process (stream).
	Progress *TaskProgress `protobuf:"bytes,3,opt,name=progress,oneof"`
}

type compileResponse_Result struct {
	// The compilation result.
	Result *BuilderResult `protobuf:"bytes,4,opt,name=result,oneof"`
}

func (*compileResponse_OutStream) isCompileResponse_Message() {}

func (*compileResponse_ErrStream) isCompileResponse_Message() {}

func (*compileResponse_Progress) isCompileResponse_Message() {}

func (*compileResponse_Result) isCompileResponse_Message() {}

type InstanceNeedsReinitializationError struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceNeedsReinitializationError) Reset() {
	*x = InstanceNeedsReinitializationError{}
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceNeedsReinitializationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceNeedsReinitializationError) ProtoMessage() {}

func (x *InstanceNeedsReinitializationError) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type InstanceNeedsReinitializationError_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 InstanceNeedsReinitializationError_builder) Build() *InstanceNeedsReinitializationError {
	m0 := &InstanceNeedsReinitializationError{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type BuilderResult struct {
	state                             protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_BuildPath              *string                     `protobuf:"bytes,1,opt,name=build_path,json=buildPath" json:"build_path,omitempty"`
	xxx_hidden_UsedLibraries          *[]*Library                 `protobuf:"bytes,2,rep,name=used_libraries,json=usedLibraries" json:"used_libraries,omitempty"`
	xxx_hidden_ExecutableSectionsSize *[]*ExecutableSectionSize   `protobuf:"bytes,3,rep,name=executable_sections_size,json=executableSectionsSize" json:"executable_sections_size,omitempty"`
	xxx_hidden_BoardPlatform          *InstalledPlatformReference `protobuf:"bytes,4,opt,name=board_platform,json=boardPlatform" json:"board_platform,omitempty"`
	xxx_hidden_BuildPlatform          *InstalledPlatformReference `protobuf:"bytes,5,opt,name=build_platform,json=buildPlatform" json:"build_platform,omitempty"`
	xxx_hidden_BuildProperties        []string                    `protobuf:"bytes,7,rep,name=build_properties,json=buildProperties" json:"build_properties,omitempty"`
	xxx_hidden_Diagnostics            *[]*CompileDiagnostic       `protobuf:"bytes,8,rep,name=diagnostics" json:"diagnostics,omitempty"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *BuilderResult) Reset() {
	*x = BuilderResult{}
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuilderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuilderResult) ProtoMessage() {}

func (x *BuilderResult) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BuilderResult) GetBuildPath() string {
	if x != nil {
		if x.xxx_hidden_BuildPath != nil {
			return *x.xxx_hidden_BuildPath
		}
		return ""
	}
	return ""
}

func (x *BuilderResult) GetUsedLibraries() []*Library {
	if x != nil {
		if x.xxx_hidden_UsedLibraries != nil {
			return *x.xxx_hidden_UsedLibraries
		}
	}
	return nil
}

func (x *BuilderResult) GetExecutableSectionsSize() []*ExecutableSectionSize {
	if x != nil {
		if x.xxx_hidden_ExecutableSectionsSize != nil {
			return *x.xxx_hidden_ExecutableSectionsSize
		}
	}
	return nil
}

func (x *BuilderResult) GetBoardPlatform() *InstalledPlatformReference {
	if x != nil {
		return x.xxx_hidden_BoardPlatform
	}
	return nil
}

func (x *BuilderResult) GetBuildPlatform() *InstalledPlatformReference {
	if x != nil {
		return x.xxx_hidden_BuildPlatform
	}
	return nil
}

func (x *BuilderResult) GetBuildProperties() []string {
	if x != nil {
		return x.xxx_hidden_BuildProperties
	}
	return nil
}

func (x *BuilderResult) GetDiagnostics() []*CompileDiagnostic {
	if x != nil {
		if x.xxx_hidden_Diagnostics != nil {
			return *x.xxx_hidden_Diagnostics
		}
	}
	return nil
}

func (x *BuilderResult) SetBuildPath(v string) {
	x.xxx_hidden_BuildPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *BuilderResult) SetUsedLibraries(v []*Library) {
	x.xxx_hidden_UsedLibraries = &v
}

func (x *BuilderResult) SetExecutableSectionsSize(v []*ExecutableSectionSize) {
	x.xxx_hidden_ExecutableSectionsSize = &v
}

func (x *BuilderResult) SetBoardPlatform(v *InstalledPlatformReference) {
	x.xxx_hidden_BoardPlatform = v
}

func (x *BuilderResult) SetBuildPlatform(v *InstalledPlatformReference) {
	x.xxx_hidden_BuildPlatform = v
}

func (x *BuilderResult) SetBuildProperties(v []string) {
	x.xxx_hidden_BuildProperties = v
}

func (x *BuilderResult) SetDiagnostics(v []*CompileDiagnostic) {
	x.xxx_hidden_Diagnostics = &v
}

func (x *BuilderResult) HasBuildPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BuilderResult) HasBoardPlatform() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BoardPlatform != nil
}

func (x *BuilderResult) HasBuildPlatform() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BuildPlatform != nil
}

func (x *BuilderResult) ClearBuildPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_BuildPath = nil
}

func (x *BuilderResult) ClearBoardPlatform() {
	x.xxx_hidden_BoardPlatform = nil
}

func (x *BuilderResult) ClearBuildPlatform() {
	x.xxx_hidden_BuildPlatform = nil
}

type BuilderResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The compiler build path.
	BuildPath *string
	// The libraries used in the build.
	UsedLibraries []*Library
	// The size of the executable split by sections.
	ExecutableSectionsSize []*ExecutableSectionSize
	// The platform where the board is defined.
	BoardPlatform *InstalledPlatformReference
	// The platform used for the build (if referenced from the board platform).
	BuildPlatform *InstalledPlatformReference
	// Build properties used for compiling.
	BuildProperties []string
	// Compiler errors and warnings.
	Diagnostics []*CompileDiagnostic
}

func (b0 BuilderResult_builder) Build() *BuilderResult {
	m0 := &BuilderResult{}
	b, x := &b0, m0
	_, _ = b, x
	if b.BuildPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_BuildPath = b.BuildPath
	}
	x.xxx_hidden_UsedLibraries = &b.UsedLibraries
	x.xxx_hidden_ExecutableSectionsSize = &b.ExecutableSectionsSize
	x.xxx_hidden_BoardPlatform = b.BoardPlatform
	x.xxx_hidden_BuildPlatform = b.BuildPlatform
	x.xxx_hidden_BuildProperties = b.BuildProperties
	x.xxx_hidden_Diagnostics = &b.Diagnostics
	return m0
}

type ExecutableSectionSize struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	xxx_hidden_Size        int64                  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	xxx_hidden_MaxSize     int64                  `protobuf:"varint,3,opt,name=max_size,json=maxSize" json:"max_size,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExecutableSectionSize) Reset() {
	*x = ExecutableSectionSize{}
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutableSectionSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutableSectionSize) ProtoMessage() {}

func (x *ExecutableSectionSize) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecutableSectionSize) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ExecutableSectionSize) GetSize() int64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *ExecutableSectionSize) GetMaxSize() int64 {
	if x != nil {
		return x.xxx_hidden_MaxSize
	}
	return 0
}

func (x *ExecutableSectionSize) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ExecutableSectionSize) SetSize(v int64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ExecutableSectionSize) SetMaxSize(v int64) {
	x.xxx_hidden_MaxSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ExecutableSectionSize) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ExecutableSectionSize) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ExecutableSectionSize) HasMaxSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ExecutableSectionSize) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *ExecutableSectionSize) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Size = 0
}

func (x *ExecutableSectionSize) ClearMaxSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MaxSize = 0
}

type ExecutableSectionSize_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The name of the section.
	Name *string
	// The used size of the section in bytes.
	Size *int64
	// The maximum size of the section in bytes.
	MaxSize *int64
}

func (b0 ExecutableSectionSize_builder) Build() *ExecutableSectionSize {
	m0 := &ExecutableSectionSize{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Name = b.Name
	}
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Size = *b.Size
	}
	if b.MaxSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_MaxSize = *b.MaxSize
	}
	return m0
}

type CompileDiagnostic struct {
	state                  protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Severity    *string                      `protobuf:"bytes,1,opt,name=severity" json:"severity,omitempty"`
	xxx_hidden_Message     *string                      `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	xxx_hidden_File        *string                      `protobuf:"bytes,3,opt,name=file" json:"file,omitempty"`
	xxx_hidden_Line        int64                        `protobuf:"varint,4,opt,name=line" json:"line,omitempty"`
	xxx_hidden_Column      int64                        `protobuf:"varint,5,opt,name=column" json:"column,omitempty"`
	xxx_hidden_Context     *[]*CompileDiagnosticContext `protobuf:"bytes,6,rep,name=context" json:"context,omitempty"`
	xxx_hidden_Notes       *[]*CompileDiagnosticNote    `protobuf:"bytes,7,rep,name=notes" json:"notes,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CompileDiagnostic) Reset() {
	*x = CompileDiagnostic{}
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileDiagnostic) ProtoMessage() {}

func (x *CompileDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CompileDiagnostic) GetSeverity() string {
	if x != nil {
		if x.xxx_hidden_Severity != nil {
			return *x.xxx_hidden_Severity
		}
		return ""
	}
	return ""
}

func (x *CompileDiagnostic) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *CompileDiagnostic) GetFile() string {
	if x != nil {
		if x.xxx_hidden_File != nil {
			return *x.xxx_hidden_File
		}
		return ""
	}
	return ""
}

func (x *CompileDiagnostic) GetLine() int64 {
	if x != nil {
		return x.xxx_hidden_Line
	}
	return 0
}

func (x *CompileDiagnostic) GetColumn() int64 {
	if x != nil {
		return x.xxx_hidden_Column
	}
	return 0
}

func (x *CompileDiagnostic) GetContext() []*CompileDiagnosticContext {
	if x != nil {
		if x.xxx_hidden_Context != nil {
			return *x.xxx_hidden_Context
		}
	}
	return nil
}

func (x *CompileDiagnostic) GetNotes() []*CompileDiagnosticNote {
	if x != nil {
		if x.xxx_hidden_Notes != nil {
			return *x.xxx_hidden_Notes
		}
	}
	return nil
}

func (x *CompileDiagnostic) SetSeverity(v string) {
	x.xxx_hidden_Severity = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *CompileDiagnostic) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *CompileDiagnostic) SetFile(v string) {
	x.xxx_hidden_File = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *CompileDiagnostic) SetLine(v int64) {
	x.xxx_hidden_Line = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *CompileDiagnostic) SetColumn(v int64) {
	x.xxx_hidden_Column = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *CompileDiagnostic) SetContext(v []*CompileDiagnosticContext) {
	x.xxx_hidden_Context = &v
}

func (x *CompileDiagnostic) SetNotes(v []*CompileDiagnosticNote) {
	x.xxx_hidden_Notes = &v
}

func (x *CompileDiagnostic) HasSeverity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CompileDiagnostic) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CompileDiagnostic) HasFile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CompileDiagnostic) HasLine() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CompileDiagnostic) HasColumn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CompileDiagnostic) ClearSeverity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Severity = nil
}

func (x *CompileDiagnostic) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

func (x *CompileDiagnostic) ClearFile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_File = nil
}

func (x *CompileDiagnostic) ClearLine() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Line = 0
}

func (x *CompileDiagnostic) ClearColumn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Column = 0
}

type CompileDiagnostic_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Severity of the diagnostic.
	Severity *string
	// The explanation of the diagnostic (it may be multiple preformatted lines).
	Message *string
	// The file containing the diagnostic.
	File *string
	// The line of the diagnostic if available (starts from 1).
	Line *int64
	// The column of the diagnostic if available (starts from 1).
	Column *int64
	// The context where this diagnostic is found (it may be multiple files that
	// represents a chain of includes, or a text describing where the diagnostic
	// is found).
	Context []*CompileDiagnosticContext
	// Annotations or suggestions to the diagnostic made by the compiler.
	Notes []*CompileDiagnosticNote
}

func (b0 CompileDiagnostic_builder) Build() *CompileDiagnostic {
	m0 := &CompileDiagnostic{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Severity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Severity = b.Severity
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Message = b.Message
	}
	if b.File != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_File = b.File
	}
	if b.Line != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Line = *b.Line
	}
	if b.Column != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Column = *b.Column
	}
	x.xxx_hidden_Context = &b.Context
	x.xxx_hidden_Notes = &b.Notes
	return m0
}

type CompileDiagnosticContext struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message     *string                `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	xxx_hidden_File        *string                `protobuf:"bytes,2,opt,name=file" json:"file,omitempty"`
	xxx_hidden_Line        int64                  `protobuf:"varint,3,opt,name=line" json:"line,omitempty"`
	xxx_hidden_Column      int64                  `protobuf:"varint,4,opt,name=column" json:"column,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CompileDiagnosticContext) Reset() {
	*x = CompileDiagnosticContext{}
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileDiagnosticContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileDiagnosticContext) ProtoMessage() {}

func (x *CompileDiagnosticContext) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CompileDiagnosticContext) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *CompileDiagnosticContext) GetFile() string {
	if x != nil {
		if x.xxx_hidden_File != nil {
			return *x.xxx_hidden_File
		}
		return ""
	}
	return ""
}

func (x *CompileDiagnosticContext) GetLine() int64 {
	if x != nil {
		return x.xxx_hidden_Line
	}
	return 0
}

func (x *CompileDiagnosticContext) GetColumn() int64 {
	if x != nil {
		return x.xxx_hidden_Column
	}
	return 0
}

func (x *CompileDiagnosticContext) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *CompileDiagnosticContext) SetFile(v string) {
	x.xxx_hidden_File = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *CompileDiagnosticContext) SetLine(v int64) {
	x.xxx_hidden_Line = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *CompileDiagnosticContext) SetColumn(v int64) {
	x.xxx_hidden_Column = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *CompileDiagnosticContext) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CompileDiagnosticContext) HasFile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CompileDiagnosticContext) HasLine() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CompileDiagnosticContext) HasColumn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CompileDiagnosticContext) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Message = nil
}

func (x *CompileDiagnosticContext) ClearFile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_File = nil
}

func (x *CompileDiagnosticContext) ClearLine() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Line = 0
}

func (x *CompileDiagnosticContext) ClearColumn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Column = 0
}

type CompileDiagnosticContext_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The message describing the context reference.
	Message *string
	// The file of the context reference.
	File *string
	// The line of the context reference.
	Line *int64
	// The column of the context reference.
	Column *int64
}

func (b0 CompileDiagnosticContext_builder) Build() *CompileDiagnosticContext {
	m0 := &CompileDiagnosticContext{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Message = b.Message
	}
	if b.File != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_File = b.File
	}
	if b.Line != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Line = *b.Line
	}
	if b.Column != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Column = *b.Column
	}
	return m0
}

type CompileDiagnosticNote struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message     *string                `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	xxx_hidden_File        *string                `protobuf:"bytes,2,opt,name=file" json:"file,omitempty"`
	xxx_hidden_Line        int64                  `protobuf:"varint,3,opt,name=line" json:"line,omitempty"`
	xxx_hidden_Column      int64                  `protobuf:"varint,4,opt,name=column" json:"column,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CompileDiagnosticNote) Reset() {
	*x = CompileDiagnosticNote{}
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileDiagnosticNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileDiagnosticNote) ProtoMessage() {}

func (x *CompileDiagnosticNote) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CompileDiagnosticNote) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *CompileDiagnosticNote) GetFile() string {
	if x != nil {
		if x.xxx_hidden_File != nil {
			return *x.xxx_hidden_File
		}
		return ""
	}
	return ""
}

func (x *CompileDiagnosticNote) GetLine() int64 {
	if x != nil {
		return x.xxx_hidden_Line
	}
	return 0
}

func (x *CompileDiagnosticNote) GetColumn() int64 {
	if x != nil {
		return x.xxx_hidden_Column
	}
	return 0
}

func (x *CompileDiagnosticNote) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *CompileDiagnosticNote) SetFile(v string) {
	x.xxx_hidden_File = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *CompileDiagnosticNote) SetLine(v int64) {
	x.xxx_hidden_Line = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *CompileDiagnosticNote) SetColumn(v int64) {
	x.xxx_hidden_Column = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *CompileDiagnosticNote) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CompileDiagnosticNote) HasFile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CompileDiagnosticNote) HasLine() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CompileDiagnosticNote) HasColumn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CompileDiagnosticNote) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Message = nil
}

func (x *CompileDiagnosticNote) ClearFile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_File = nil
}

func (x *CompileDiagnosticNote) ClearLine() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Line = 0
}

func (x *CompileDiagnosticNote) ClearColumn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Column = 0
}

type CompileDiagnosticNote_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The message describing the compiler note.
	Message *string
	// The file of the compiler note.
	File *string
	// The line of the compiler note.
	Line *int64
	// The column of the compiler note.
	Column *int64
}

func (b0 CompileDiagnosticNote_builder) Build() *CompileDiagnosticNote {
	m0 := &CompileDiagnosticNote{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Message = b.Message
	}
	if b.File != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_File = b.File
	}
	if b.Line != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Line = *b.Line
	}
	if b.Column != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Column = *b.Column
	}
	return m0
}

var File_cc_arduino_cli_commands_v1_compile_proto protoreflect.FileDescriptor

var file_cc_arduino_cli_commands_v1_compile_proto_rawDesc = []byte{
	0x0a, 0x28, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x69,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d,
	0x70, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x63, 0x63, 0x2e, 0x61,
	0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x27, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69,
	0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x24, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf7, 0x08, 0x0a, 0x0e, 0x43, 0x6f, 0x6d,
	0x70, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x71, 0x62, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x71, 0x62,
	0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x73, 0x68, 0x6f,
	0x77, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x72, 0x65, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0a, 0x70, 0x72, 0x65, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x10, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x42, 0x02, 0x18, 0x01, 0x52, 0x0e, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68, 0x12, 0x29, 0x0a, 0x10, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x69,
	0x65, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x71, 0x75, 0x69, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6a,
	0x6f, 0x62, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x0f, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65,
	0x73, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x5f, 0x66, 0x6f,
	0x72, 0x5f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x6f,
	0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x46, 0x6f, 0x72, 0x44, 0x65, 0x62, 0x75, 0x67, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x12, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x69, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x18, 0x13, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x63,
	0x6c, 0x65, 0x61, 0x6e, 0x12, 0x47, 0x0a, 0x20, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x63,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x15, 0x20, 0x01, 0x28, 0x08, 0x52, 0x1d,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x67, 0x0a,
	0x0f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65,
	0x18, 0x16, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75,
	0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4f, 0x76,
	0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x5f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x17, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0e, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x18, 0x18, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x6b, 0x65, 0x79,
	0x73, 0x5f, 0x6b, 0x65, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x19, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6b, 0x65, 0x79, 0x73, 0x4b, 0x65, 0x79, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x19,
	0x0a, 0x08, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x1a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x1b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x18, 0x73, 0x6b,
	0x69, 0x70, 0x5f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x5f, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x18, 0x1c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x73, 0x6b,
	0x69, 0x70, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x79, 0x12, 0x42, 0x0a, 0x1e, 0x64, 0x6f, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x65,
	0x78, 0x70, 0x61, 0x6e, 0x64, 0x5f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x1d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x1a, 0x64, 0x6f,
	0x4e, 0x6f, 0x74, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x17, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x73, 0x18, 0x1e, 0x20, 0x03, 0x28, 0x09, 0x52, 0x14, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x78, 0x74, 0x72, 0x61, 0x50, 0x61, 0x74, 0x68, 0x73, 0x1a,
	0x41, 0x0a, 0x13, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0xeb, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x6f, 0x75,
	0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1f, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x5f, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x65,
	0x72, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x46, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x63, 0x2e,
	0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x43, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x24, 0x0a, 0x22, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x65, 0x65, 0x64,
	0x73, 0x52, 0x65, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xa1, 0x04, 0x0a, 0x0d, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68, 0x12, 0x4a, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x64, 0x5f,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x62,
	0x72, 0x61, 0x72, 0x79, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x64, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x6b, 0x0a, 0x18, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69,
	0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x16, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x5d, 0x0a, 0x0e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72,
	0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x0d, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12,
	0x5d, 0x0a, 0x0e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64,
	0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52,
	0x0d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x29,
	0x0a, 0x10, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69,
	0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x4f, 0x0a, 0x0b, 0x64, 0x69, 0x61,
	0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d,
	0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x69, 0x6c, 0x65, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52, 0x0b, 0x64,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x22, 0x5a, 0x0a, 0x15, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d,
	0x61, 0x78, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d,
	0x61, 0x78, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xa2, 0x02, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x65, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x12, 0x4e, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f,
	0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74,
	0x69, 0x63, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x47, 0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x31, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63,
	0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63,
	0x4e, 0x6f, 0x74, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x74, 0x0a, 0x18, 0x43,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x22, 0x71, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x44, 0x69, 0x61, 0x67,
	0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x4e, 0x6f, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x42, 0x50, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69,
	0x6e, 0x6f, 0x2d, 0x63, 0x6c, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x63, 0x2f, 0x61, 0x72,
	0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x92, 0x03,
	0x05, 0xd2, 0x3e, 0x02, 0x10, 0x03, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x70, 0xe8, 0x07,
}

var file_cc_arduino_cli_commands_v1_compile_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cc_arduino_cli_commands_v1_compile_proto_goTypes = []any{
	(*CompileRequest)(nil),                     // 0: cc.arduino.cli.commands.v1.CompileRequest
	(*CompileResponse)(nil),                    // 1: cc.arduino.cli.commands.v1.CompileResponse
	(*InstanceNeedsReinitializationError)(nil), // 2: cc.arduino.cli.commands.v1.InstanceNeedsReinitializationError
	(*BuilderResult)(nil),                      // 3: cc.arduino.cli.commands.v1.BuilderResult
	(*ExecutableSectionSize)(nil),              // 4: cc.arduino.cli.commands.v1.ExecutableSectionSize
	(*CompileDiagnostic)(nil),                  // 5: cc.arduino.cli.commands.v1.CompileDiagnostic
	(*CompileDiagnosticContext)(nil),           // 6: cc.arduino.cli.commands.v1.CompileDiagnosticContext
	(*CompileDiagnosticNote)(nil),              // 7: cc.arduino.cli.commands.v1.CompileDiagnosticNote
	nil,                                        // 8: cc.arduino.cli.commands.v1.CompileRequest.SourceOverrideEntry
	(*Instance)(nil),                           // 9: cc.arduino.cli.commands.v1.Instance
	(*TaskProgress)(nil),                       // 10: cc.arduino.cli.commands.v1.TaskProgress
	(*Library)(nil),                            // 11: cc.arduino.cli.commands.v1.Library
	(*InstalledPlatformReference)(nil),         // 12: cc.arduino.cli.commands.v1.InstalledPlatformReference
}
var file_cc_arduino_cli_commands_v1_compile_proto_depIdxs = []int32{
	9,  // 0: cc.arduino.cli.commands.v1.CompileRequest.instance:type_name -> cc.arduino.cli.commands.v1.Instance
	8,  // 1: cc.arduino.cli.commands.v1.CompileRequest.source_override:type_name -> cc.arduino.cli.commands.v1.CompileRequest.SourceOverrideEntry
	10, // 2: cc.arduino.cli.commands.v1.CompileResponse.progress:type_name -> cc.arduino.cli.commands.v1.TaskProgress
	3,  // 3: cc.arduino.cli.commands.v1.CompileResponse.result:type_name -> cc.arduino.cli.commands.v1.BuilderResult
	11, // 4: cc.arduino.cli.commands.v1.BuilderResult.used_libraries:type_name -> cc.arduino.cli.commands.v1.Library
	4,  // 5: cc.arduino.cli.commands.v1.BuilderResult.executable_sections_size:type_name -> cc.arduino.cli.commands.v1.ExecutableSectionSize
	12, // 6: cc.arduino.cli.commands.v1.BuilderResult.board_platform:type_name -> cc.arduino.cli.commands.v1.InstalledPlatformReference
	12, // 7: cc.arduino.cli.commands.v1.BuilderResult.build_platform:type_name -> cc.arduino.cli.commands.v1.InstalledPlatformReference
	5,  // 8: cc.arduino.cli.commands.v1.BuilderResult.diagnostics:type_name -> cc.arduino.cli.commands.v1.CompileDiagnostic
	6,  // 9: cc.arduino.cli.commands.v1.CompileDiagnostic.context:type_name -> cc.arduino.cli.commands.v1.CompileDiagnosticContext
	7,  // 10: cc.arduino.cli.commands.v1.CompileDiagnostic.notes:type_name -> cc.arduino.cli.commands.v1.CompileDiagnosticNote
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_cc_arduino_cli_commands_v1_compile_proto_init() }
func file_cc_arduino_cli_commands_v1_compile_proto_init() {
	if File_cc_arduino_cli_commands_v1_compile_proto != nil {
		return
	}
	file_cc_arduino_cli_commands_v1_common_proto_init()
	file_cc_arduino_cli_commands_v1_lib_proto_init()
	file_cc_arduino_cli_commands_v1_compile_proto_msgTypes[1].OneofWrappers = []any{
		(*compileResponse_OutStream)(nil),
		(*compileResponse_ErrStream)(nil),
		(*compileResponse_Progress)(nil),
		(*compileResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cc_arduino_cli_commands_v1_compile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cc_arduino_cli_commands_v1_compile_proto_goTypes,
		DependencyIndexes: file_cc_arduino_cli_commands_v1_compile_proto_depIdxs,
		MessageInfos:      file_cc_arduino_cli_commands_v1_compile_proto_msgTypes,
	}.Build()
	File_cc_arduino_cli_commands_v1_compile_proto = out.File
	file_cc_arduino_cli_commands_v1_compile_proto_rawDesc = nil
	file_cc_arduino_cli_commands_v1_compile_proto_goTypes = nil
	file_cc_arduino_cli_commands_v1_compile_proto_depIdxs = nil
}
