// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: cc/arduino/cli/commands/v1/core.proto

package commands

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlatformInstallRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance         *Instance              `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	xxx_hidden_PlatformPackage  *string                `protobuf:"bytes,2,opt,name=platform_package,json=platformPackage" json:"platform_package,omitempty"`
	xxx_hidden_Architecture     *string                `protobuf:"bytes,3,opt,name=architecture" json:"architecture,omitempty"`
	xxx_hidden_Version          *string                `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	xxx_hidden_SkipPostInstall  bool                   `protobuf:"varint,5,opt,name=skip_post_install,json=skipPostInstall" json:"skip_post_install,omitempty"`
	xxx_hidden_NoOverwrite      bool                   `protobuf:"varint,6,opt,name=no_overwrite,json=noOverwrite" json:"no_overwrite,omitempty"`
	xxx_hidden_SkipPreUninstall bool                   `protobuf:"varint,7,opt,name=skip_pre_uninstall,json=skipPreUninstall" json:"skip_pre_uninstall,omitempty"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *PlatformInstallRequest) Reset() {
	*x = PlatformInstallRequest{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformInstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformInstallRequest) ProtoMessage() {}

func (x *PlatformInstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlatformInstallRequest) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *PlatformInstallRequest) GetPlatformPackage() string {
	if x != nil {
		if x.xxx_hidden_PlatformPackage != nil {
			return *x.xxx_hidden_PlatformPackage
		}
		return ""
	}
	return ""
}

func (x *PlatformInstallRequest) GetArchitecture() string {
	if x != nil {
		if x.xxx_hidden_Architecture != nil {
			return *x.xxx_hidden_Architecture
		}
		return ""
	}
	return ""
}

func (x *PlatformInstallRequest) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *PlatformInstallRequest) GetSkipPostInstall() bool {
	if x != nil {
		return x.xxx_hidden_SkipPostInstall
	}
	return false
}

func (x *PlatformInstallRequest) GetNoOverwrite() bool {
	if x != nil {
		return x.xxx_hidden_NoOverwrite
	}
	return false
}

func (x *PlatformInstallRequest) GetSkipPreUninstall() bool {
	if x != nil {
		return x.xxx_hidden_SkipPreUninstall
	}
	return false
}

func (x *PlatformInstallRequest) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *PlatformInstallRequest) SetPlatformPackage(v string) {
	x.xxx_hidden_PlatformPackage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *PlatformInstallRequest) SetArchitecture(v string) {
	x.xxx_hidden_Architecture = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *PlatformInstallRequest) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *PlatformInstallRequest) SetSkipPostInstall(v bool) {
	x.xxx_hidden_SkipPostInstall = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *PlatformInstallRequest) SetNoOverwrite(v bool) {
	x.xxx_hidden_NoOverwrite = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *PlatformInstallRequest) SetSkipPreUninstall(v bool) {
	x.xxx_hidden_SkipPreUninstall = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *PlatformInstallRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *PlatformInstallRequest) HasPlatformPackage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PlatformInstallRequest) HasArchitecture() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PlatformInstallRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PlatformInstallRequest) HasSkipPostInstall() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *PlatformInstallRequest) HasNoOverwrite() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *PlatformInstallRequest) HasSkipPreUninstall() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *PlatformInstallRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

func (x *PlatformInstallRequest) ClearPlatformPackage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PlatformPackage = nil
}

func (x *PlatformInstallRequest) ClearArchitecture() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Architecture = nil
}

func (x *PlatformInstallRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Version = nil
}

func (x *PlatformInstallRequest) ClearSkipPostInstall() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_SkipPostInstall = false
}

func (x *PlatformInstallRequest) ClearNoOverwrite() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_NoOverwrite = false
}

func (x *PlatformInstallRequest) ClearSkipPreUninstall() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_SkipPreUninstall = false
}

type PlatformInstallRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Arduino Core Service instance from the `Init` response.
	Instance *Instance
	// Vendor name of the platform (e.g., `arduino`).
	PlatformPackage *string
	// Architecture name of the platform (e.g., `avr`).
	Architecture *string
	// Platform version to install.
	Version *string
	// Set to true to not run (eventual) post install scripts for trusted
	// platforms.
	SkipPostInstall *bool
	// Set to true to skip installation if a different version of the platform
	// is already installed.
	NoOverwrite *bool
	// Set to true to not run (eventual) pre uninstall scripts for trusted
	// platforms when performing platform upgrades.
	SkipPreUninstall *bool
}

func (b0 PlatformInstallRequest_builder) Build() *PlatformInstallRequest {
	m0 := &PlatformInstallRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	if b.PlatformPackage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_PlatformPackage = b.PlatformPackage
	}
	if b.Architecture != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Architecture = b.Architecture
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Version = b.Version
	}
	if b.SkipPostInstall != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_SkipPostInstall = *b.SkipPostInstall
	}
	if b.NoOverwrite != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_NoOverwrite = *b.NoOverwrite
	}
	if b.SkipPreUninstall != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_SkipPreUninstall = *b.SkipPreUninstall
	}
	return m0
}

type PlatformInstallResponse struct {
	state              protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_Message isPlatformInstallResponse_Message `protobuf_oneof:"message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PlatformInstallResponse) Reset() {
	*x = PlatformInstallResponse{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformInstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformInstallResponse) ProtoMessage() {}

func (x *PlatformInstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlatformInstallResponse) GetProgress() *DownloadProgress {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*platformInstallResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *PlatformInstallResponse) GetTaskProgress() *TaskProgress {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*platformInstallResponse_TaskProgress); ok {
			return x.TaskProgress
		}
	}
	return nil
}

func (x *PlatformInstallResponse) GetResult() *PlatformInstallResponse_Result {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*platformInstallResponse_Result_); ok {
			return x.Result
		}
	}
	return nil
}

func (x *PlatformInstallResponse) SetProgress(v *DownloadProgress) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &platformInstallResponse_Progress{v}
}

func (x *PlatformInstallResponse) SetTaskProgress(v *TaskProgress) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &platformInstallResponse_TaskProgress{v}
}

func (x *PlatformInstallResponse) SetResult(v *PlatformInstallResponse_Result) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &platformInstallResponse_Result_{v}
}

func (x *PlatformInstallResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *PlatformInstallResponse) HasProgress() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*platformInstallResponse_Progress)
	return ok
}

func (x *PlatformInstallResponse) HasTaskProgress() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*platformInstallResponse_TaskProgress)
	return ok
}

func (x *PlatformInstallResponse) HasResult() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*platformInstallResponse_Result_)
	return ok
}

func (x *PlatformInstallResponse) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *PlatformInstallResponse) ClearProgress() {
	if _, ok := x.xxx_hidden_Message.(*platformInstallResponse_Progress); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *PlatformInstallResponse) ClearTaskProgress() {
	if _, ok := x.xxx_hidden_Message.(*platformInstallResponse_TaskProgress); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *PlatformInstallResponse) ClearResult() {
	if _, ok := x.xxx_hidden_Message.(*platformInstallResponse_Result_); ok {
		x.xxx_hidden_Message = nil
	}
}

const PlatformInstallResponse_Message_not_set_case case_PlatformInstallResponse_Message = 0
const PlatformInstallResponse_Progress_case case_PlatformInstallResponse_Message = 1
const PlatformInstallResponse_TaskProgress_case case_PlatformInstallResponse_Message = 2
const PlatformInstallResponse_Result_case case_PlatformInstallResponse_Message = 3

func (x *PlatformInstallResponse) WhichMessage() case_PlatformInstallResponse_Message {
	if x == nil {
		return PlatformInstallResponse_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *platformInstallResponse_Progress:
		return PlatformInstallResponse_Progress_case
	case *platformInstallResponse_TaskProgress:
		return PlatformInstallResponse_TaskProgress_case
	case *platformInstallResponse_Result_:
		return PlatformInstallResponse_Result_case
	default:
		return PlatformInstallResponse_Message_not_set_case
	}
}

type PlatformInstallResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Message:
	// Progress of the downloads of the platform and tool files.
	Progress *DownloadProgress
	// Description of the current stage of the installation.
	TaskProgress *TaskProgress
	// The installation result.
	Result *PlatformInstallResponse_Result
	// -- end of xxx_hidden_Message
}

func (b0 PlatformInstallResponse_builder) Build() *PlatformInstallResponse {
	m0 := &PlatformInstallResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Progress != nil {
		x.xxx_hidden_Message = &platformInstallResponse_Progress{b.Progress}
	}
	if b.TaskProgress != nil {
		x.xxx_hidden_Message = &platformInstallResponse_TaskProgress{b.TaskProgress}
	}
	if b.Result != nil {
		x.xxx_hidden_Message = &platformInstallResponse_Result_{b.Result}
	}
	return m0
}

type case_PlatformInstallResponse_Message protoreflect.FieldNumber

func (x case_PlatformInstallResponse_Message) String() string {
	md := file_cc_arduino_cli_commands_v1_core_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isPlatformInstallResponse_Message interface {
	isPlatformInstallResponse_Message()
}

type platformInstallResponse_Progress struct {
	// Progress of the downloads of the platform and tool files.
	Progress *DownloadProgress `protobuf:"bytes,1,opt,name=progress,oneof"`
}

type platformInstallResponse_TaskProgress struct {
	// Description of the current stage of the installation.
	TaskProgress *TaskProgress `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,oneof"`
}

type platformInstallResponse_Result_ struct {
	// The installation result.
	Result *PlatformInstallResponse_Result `protobuf:"bytes,3,opt,name=result,oneof"`
}

func (*platformInstallResponse_Progress) isPlatformInstallResponse_Message() {}

func (*platformInstallResponse_TaskProgress) isPlatformInstallResponse_Message() {}

func (*platformInstallResponse_Result_) isPlatformInstallResponse_Message() {}

type PlatformLoadingError struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformLoadingError) Reset() {
	*x = PlatformLoadingError{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformLoadingError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformLoadingError) ProtoMessage() {}

func (x *PlatformLoadingError) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PlatformLoadingError_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PlatformLoadingError_builder) Build() *PlatformLoadingError {
	m0 := &PlatformLoadingError{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PlatformDownloadRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance        *Instance              `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	xxx_hidden_PlatformPackage *string                `protobuf:"bytes,2,opt,name=platform_package,json=platformPackage" json:"platform_package,omitempty"`
	xxx_hidden_Architecture    *string                `protobuf:"bytes,3,opt,name=architecture" json:"architecture,omitempty"`
	xxx_hidden_Version         *string                `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *PlatformDownloadRequest) Reset() {
	*x = PlatformDownloadRequest{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformDownloadRequest) ProtoMessage() {}

func (x *PlatformDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlatformDownloadRequest) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *PlatformDownloadRequest) GetPlatformPackage() string {
	if x != nil {
		if x.xxx_hidden_PlatformPackage != nil {
			return *x.xxx_hidden_PlatformPackage
		}
		return ""
	}
	return ""
}

func (x *PlatformDownloadRequest) GetArchitecture() string {
	if x != nil {
		if x.xxx_hidden_Architecture != nil {
			return *x.xxx_hidden_Architecture
		}
		return ""
	}
	return ""
}

func (x *PlatformDownloadRequest) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *PlatformDownloadRequest) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *PlatformDownloadRequest) SetPlatformPackage(v string) {
	x.xxx_hidden_PlatformPackage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *PlatformDownloadRequest) SetArchitecture(v string) {
	x.xxx_hidden_Architecture = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *PlatformDownloadRequest) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *PlatformDownloadRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *PlatformDownloadRequest) HasPlatformPackage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PlatformDownloadRequest) HasArchitecture() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PlatformDownloadRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PlatformDownloadRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

func (x *PlatformDownloadRequest) ClearPlatformPackage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PlatformPackage = nil
}

func (x *PlatformDownloadRequest) ClearArchitecture() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Architecture = nil
}

func (x *PlatformDownloadRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Version = nil
}

type PlatformDownloadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Arduino Core Service instance from the `Init` response.
	Instance *Instance
	// Vendor name of the platform (e.g., `arduino`).
	PlatformPackage *string
	// Architecture name of the platform (e.g., `avr`).
	Architecture *string
	// Platform version to download.
	Version *string
}

func (b0 PlatformDownloadRequest_builder) Build() *PlatformDownloadRequest {
	m0 := &PlatformDownloadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	if b.PlatformPackage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_PlatformPackage = b.PlatformPackage
	}
	if b.Architecture != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Architecture = b.Architecture
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Version = b.Version
	}
	return m0
}

type PlatformDownloadResponse struct {
	state              protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_Message isPlatformDownloadResponse_Message `protobuf_oneof:"message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PlatformDownloadResponse) Reset() {
	*x = PlatformDownloadResponse{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformDownloadResponse) ProtoMessage() {}

func (x *PlatformDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlatformDownloadResponse) GetProgress() *DownloadProgress {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*platformDownloadResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *PlatformDownloadResponse) GetResult() *PlatformDownloadResponse_Result {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*platformDownloadResponse_Result_); ok {
			return x.Result
		}
	}
	return nil
}

func (x *PlatformDownloadResponse) SetProgress(v *DownloadProgress) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &platformDownloadResponse_Progress{v}
}

func (x *PlatformDownloadResponse) SetResult(v *PlatformDownloadResponse_Result) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &platformDownloadResponse_Result_{v}
}

func (x *PlatformDownloadResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *PlatformDownloadResponse) HasProgress() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*platformDownloadResponse_Progress)
	return ok
}

func (x *PlatformDownloadResponse) HasResult() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*platformDownloadResponse_Result_)
	return ok
}

func (x *PlatformDownloadResponse) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *PlatformDownloadResponse) ClearProgress() {
	if _, ok := x.xxx_hidden_Message.(*platformDownloadResponse_Progress); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *PlatformDownloadResponse) ClearResult() {
	if _, ok := x.xxx_hidden_Message.(*platformDownloadResponse_Result_); ok {
		x.xxx_hidden_Message = nil
	}
}

const PlatformDownloadResponse_Message_not_set_case case_PlatformDownloadResponse_Message = 0
const PlatformDownloadResponse_Progress_case case_PlatformDownloadResponse_Message = 1
const PlatformDownloadResponse_Result_case case_PlatformDownloadResponse_Message = 2

func (x *PlatformDownloadResponse) WhichMessage() case_PlatformDownloadResponse_Message {
	if x == nil {
		return PlatformDownloadResponse_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *platformDownloadResponse_Progress:
		return PlatformDownloadResponse_Progress_case
	case *platformDownloadResponse_Result_:
		return PlatformDownloadResponse_Result_case
	default:
		return PlatformDownloadResponse_Message_not_set_case
	}
}

type PlatformDownloadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Message:
	// Progress of the downloads of platform and tool files.
	Progress *DownloadProgress
	// The download result.
	Result *PlatformDownloadResponse_Result
	// -- end of xxx_hidden_Message
}

func (b0 PlatformDownloadResponse_builder) Build() *PlatformDownloadResponse {
	m0 := &PlatformDownloadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Progress != nil {
		x.xxx_hidden_Message = &platformDownloadResponse_Progress{b.Progress}
	}
	if b.Result != nil {
		x.xxx_hidden_Message = &platformDownloadResponse_Result_{b.Result}
	}
	return m0
}

type case_PlatformDownloadResponse_Message protoreflect.FieldNumber

func (x case_PlatformDownloadResponse_Message) String() string {
	md := file_cc_arduino_cli_commands_v1_core_proto_msgTypes[4].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isPlatformDownloadResponse_Message interface {
	isPlatformDownloadResponse_Message()
}

type platformDownloadResponse_Progress struct {
	// Progress of the downloads of platform and tool files.
	Progress *DownloadProgress `protobuf:"bytes,1,opt,name=progress,oneof"`
}

type platformDownloadResponse_Result_ struct {
	// The download result.
	Result *PlatformDownloadResponse_Result `protobuf:"bytes,2,opt,name=result,oneof"`
}

func (*platformDownloadResponse_Progress) isPlatformDownloadResponse_Message() {}

func (*platformDownloadResponse_Result_) isPlatformDownloadResponse_Message() {}

type PlatformUninstallRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance         *Instance              `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	xxx_hidden_PlatformPackage  *string                `protobuf:"bytes,2,opt,name=platform_package,json=platformPackage" json:"platform_package,omitempty"`
	xxx_hidden_Architecture     *string                `protobuf:"bytes,3,opt,name=architecture" json:"architecture,omitempty"`
	xxx_hidden_SkipPreUninstall bool                   `protobuf:"varint,4,opt,name=skip_pre_uninstall,json=skipPreUninstall" json:"skip_pre_uninstall,omitempty"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *PlatformUninstallRequest) Reset() {
	*x = PlatformUninstallRequest{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformUninstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformUninstallRequest) ProtoMessage() {}

func (x *PlatformUninstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlatformUninstallRequest) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *PlatformUninstallRequest) GetPlatformPackage() string {
	if x != nil {
		if x.xxx_hidden_PlatformPackage != nil {
			return *x.xxx_hidden_PlatformPackage
		}
		return ""
	}
	return ""
}

func (x *PlatformUninstallRequest) GetArchitecture() string {
	if x != nil {
		if x.xxx_hidden_Architecture != nil {
			return *x.xxx_hidden_Architecture
		}
		return ""
	}
	return ""
}

func (x *PlatformUninstallRequest) GetSkipPreUninstall() bool {
	if x != nil {
		return x.xxx_hidden_SkipPreUninstall
	}
	return false
}

func (x *PlatformUninstallRequest) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *PlatformUninstallRequest) SetPlatformPackage(v string) {
	x.xxx_hidden_PlatformPackage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *PlatformUninstallRequest) SetArchitecture(v string) {
	x.xxx_hidden_Architecture = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *PlatformUninstallRequest) SetSkipPreUninstall(v bool) {
	x.xxx_hidden_SkipPreUninstall = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *PlatformUninstallRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *PlatformUninstallRequest) HasPlatformPackage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PlatformUninstallRequest) HasArchitecture() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PlatformUninstallRequest) HasSkipPreUninstall() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PlatformUninstallRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

func (x *PlatformUninstallRequest) ClearPlatformPackage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PlatformPackage = nil
}

func (x *PlatformUninstallRequest) ClearArchitecture() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Architecture = nil
}

func (x *PlatformUninstallRequest) ClearSkipPreUninstall() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_SkipPreUninstall = false
}

type PlatformUninstallRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Arduino Core Service instance from the `Init` response.
	Instance *Instance
	// Vendor name of the platform (e.g., `arduino`).
	PlatformPackage *string
	// Architecture name of the platform (e.g., `avr`).
	Architecture *string
	// Set to true to not run (eventual) pre uninstall scripts for trusted
	// platforms.
	SkipPreUninstall *bool
}

func (b0 PlatformUninstallRequest_builder) Build() *PlatformUninstallRequest {
	m0 := &PlatformUninstallRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	if b.PlatformPackage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_PlatformPackage = b.PlatformPackage
	}
	if b.Architecture != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Architecture = b.Architecture
	}
	if b.SkipPreUninstall != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_SkipPreUninstall = *b.SkipPreUninstall
	}
	return m0
}

type PlatformUninstallResponse struct {
	state              protoimpl.MessageState              `protogen:"opaque.v1"`
	xxx_hidden_Message isPlatformUninstallResponse_Message `protobuf_oneof:"message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PlatformUninstallResponse) Reset() {
	*x = PlatformUninstallResponse{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformUninstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformUninstallResponse) ProtoMessage() {}

func (x *PlatformUninstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlatformUninstallResponse) GetTaskProgress() *TaskProgress {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*platformUninstallResponse_TaskProgress); ok {
			return x.TaskProgress
		}
	}
	return nil
}

func (x *PlatformUninstallResponse) GetResult() *PlatformUninstallResponse_Result {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*platformUninstallResponse_Result_); ok {
			return x.Result
		}
	}
	return nil
}

func (x *PlatformUninstallResponse) SetTaskProgress(v *TaskProgress) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &platformUninstallResponse_TaskProgress{v}
}

func (x *PlatformUninstallResponse) SetResult(v *PlatformUninstallResponse_Result) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &platformUninstallResponse_Result_{v}
}

func (x *PlatformUninstallResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *PlatformUninstallResponse) HasTaskProgress() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*platformUninstallResponse_TaskProgress)
	return ok
}

func (x *PlatformUninstallResponse) HasResult() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*platformUninstallResponse_Result_)
	return ok
}

func (x *PlatformUninstallResponse) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *PlatformUninstallResponse) ClearTaskProgress() {
	if _, ok := x.xxx_hidden_Message.(*platformUninstallResponse_TaskProgress); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *PlatformUninstallResponse) ClearResult() {
	if _, ok := x.xxx_hidden_Message.(*platformUninstallResponse_Result_); ok {
		x.xxx_hidden_Message = nil
	}
}

const PlatformUninstallResponse_Message_not_set_case case_PlatformUninstallResponse_Message = 0
const PlatformUninstallResponse_TaskProgress_case case_PlatformUninstallResponse_Message = 1
const PlatformUninstallResponse_Result_case case_PlatformUninstallResponse_Message = 2

func (x *PlatformUninstallResponse) WhichMessage() case_PlatformUninstallResponse_Message {
	if x == nil {
		return PlatformUninstallResponse_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *platformUninstallResponse_TaskProgress:
		return PlatformUninstallResponse_TaskProgress_case
	case *platformUninstallResponse_Result_:
		return PlatformUninstallResponse_Result_case
	default:
		return PlatformUninstallResponse_Message_not_set_case
	}
}

type PlatformUninstallResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Message:
	// Description of the current stage of the uninstall.
	TaskProgress *TaskProgress
	// The uninstall result.
	Result *PlatformUninstallResponse_Result
	// -- end of xxx_hidden_Message
}

func (b0 PlatformUninstallResponse_builder) Build() *PlatformUninstallResponse {
	m0 := &PlatformUninstallResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TaskProgress != nil {
		x.xxx_hidden_Message = &platformUninstallResponse_TaskProgress{b.TaskProgress}
	}
	if b.Result != nil {
		x.xxx_hidden_Message = &platformUninstallResponse_Result_{b.Result}
	}
	return m0
}

type case_PlatformUninstallResponse_Message protoreflect.FieldNumber

func (x case_PlatformUninstallResponse_Message) String() string {
	md := file_cc_arduino_cli_commands_v1_core_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isPlatformUninstallResponse_Message interface {
	isPlatformUninstallResponse_Message()
}

type platformUninstallResponse_TaskProgress struct {
	// Description of the current stage of the uninstall.
	TaskProgress *TaskProgress `protobuf:"bytes,1,opt,name=task_progress,json=taskProgress,oneof"`
}

type platformUninstallResponse_Result_ struct {
	// The uninstall result.
	Result *PlatformUninstallResponse_Result `protobuf:"bytes,2,opt,name=result,oneof"`
}

func (*platformUninstallResponse_TaskProgress) isPlatformUninstallResponse_Message() {}

func (*platformUninstallResponse_Result_) isPlatformUninstallResponse_Message() {}

// AlreadyAtLatestVersionError is returned when an upgrade is not possible
// because already at latest version.
type AlreadyAtLatestVersionError struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlreadyAtLatestVersionError) Reset() {
	*x = AlreadyAtLatestVersionError{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlreadyAtLatestVersionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlreadyAtLatestVersionError) ProtoMessage() {}

func (x *AlreadyAtLatestVersionError) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AlreadyAtLatestVersionError_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 AlreadyAtLatestVersionError_builder) Build() *AlreadyAtLatestVersionError {
	m0 := &AlreadyAtLatestVersionError{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PlatformUpgradeRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance         *Instance              `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	xxx_hidden_PlatformPackage  *string                `protobuf:"bytes,2,opt,name=platform_package,json=platformPackage" json:"platform_package,omitempty"`
	xxx_hidden_Architecture     *string                `protobuf:"bytes,3,opt,name=architecture" json:"architecture,omitempty"`
	xxx_hidden_SkipPostInstall  bool                   `protobuf:"varint,4,opt,name=skip_post_install,json=skipPostInstall" json:"skip_post_install,omitempty"`
	xxx_hidden_SkipPreUninstall bool                   `protobuf:"varint,5,opt,name=skip_pre_uninstall,json=skipPreUninstall" json:"skip_pre_uninstall,omitempty"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *PlatformUpgradeRequest) Reset() {
	*x = PlatformUpgradeRequest{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformUpgradeRequest) ProtoMessage() {}

func (x *PlatformUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlatformUpgradeRequest) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *PlatformUpgradeRequest) GetPlatformPackage() string {
	if x != nil {
		if x.xxx_hidden_PlatformPackage != nil {
			return *x.xxx_hidden_PlatformPackage
		}
		return ""
	}
	return ""
}

func (x *PlatformUpgradeRequest) GetArchitecture() string {
	if x != nil {
		if x.xxx_hidden_Architecture != nil {
			return *x.xxx_hidden_Architecture
		}
		return ""
	}
	return ""
}

func (x *PlatformUpgradeRequest) GetSkipPostInstall() bool {
	if x != nil {
		return x.xxx_hidden_SkipPostInstall
	}
	return false
}

func (x *PlatformUpgradeRequest) GetSkipPreUninstall() bool {
	if x != nil {
		return x.xxx_hidden_SkipPreUninstall
	}
	return false
}

func (x *PlatformUpgradeRequest) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *PlatformUpgradeRequest) SetPlatformPackage(v string) {
	x.xxx_hidden_PlatformPackage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *PlatformUpgradeRequest) SetArchitecture(v string) {
	x.xxx_hidden_Architecture = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *PlatformUpgradeRequest) SetSkipPostInstall(v bool) {
	x.xxx_hidden_SkipPostInstall = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *PlatformUpgradeRequest) SetSkipPreUninstall(v bool) {
	x.xxx_hidden_SkipPreUninstall = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *PlatformUpgradeRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *PlatformUpgradeRequest) HasPlatformPackage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PlatformUpgradeRequest) HasArchitecture() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PlatformUpgradeRequest) HasSkipPostInstall() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PlatformUpgradeRequest) HasSkipPreUninstall() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *PlatformUpgradeRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

func (x *PlatformUpgradeRequest) ClearPlatformPackage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PlatformPackage = nil
}

func (x *PlatformUpgradeRequest) ClearArchitecture() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Architecture = nil
}

func (x *PlatformUpgradeRequest) ClearSkipPostInstall() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_SkipPostInstall = false
}

func (x *PlatformUpgradeRequest) ClearSkipPreUninstall() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_SkipPreUninstall = false
}

type PlatformUpgradeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Arduino Core Service instance from the `Init` response.
	Instance *Instance
	// Vendor name of the platform (e.g., `arduino`).
	PlatformPackage *string
	// Architecture name of the platform (e.g., `avr`).
	Architecture *string
	// Set to true to not run (eventual) post install scripts for trusted
	// platforms.
	SkipPostInstall *bool
	// Set to true to not run (eventual) pre uninstall scripts for trusted
	// platforms when performing platform upgrades.
	SkipPreUninstall *bool
}

func (b0 PlatformUpgradeRequest_builder) Build() *PlatformUpgradeRequest {
	m0 := &PlatformUpgradeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	if b.PlatformPackage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_PlatformPackage = b.PlatformPackage
	}
	if b.Architecture != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Architecture = b.Architecture
	}
	if b.SkipPostInstall != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_SkipPostInstall = *b.SkipPostInstall
	}
	if b.SkipPreUninstall != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_SkipPreUninstall = *b.SkipPreUninstall
	}
	return m0
}

type PlatformUpgradeResponse struct {
	state              protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_Message isPlatformUpgradeResponse_Message `protobuf_oneof:"message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PlatformUpgradeResponse) Reset() {
	*x = PlatformUpgradeResponse{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformUpgradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformUpgradeResponse) ProtoMessage() {}

func (x *PlatformUpgradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlatformUpgradeResponse) GetProgress() *DownloadProgress {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*platformUpgradeResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *PlatformUpgradeResponse) GetTaskProgress() *TaskProgress {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*platformUpgradeResponse_TaskProgress); ok {
			return x.TaskProgress
		}
	}
	return nil
}

func (x *PlatformUpgradeResponse) GetResult() *PlatformUpgradeResponse_Result {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*platformUpgradeResponse_Result_); ok {
			return x.Result
		}
	}
	return nil
}

func (x *PlatformUpgradeResponse) SetProgress(v *DownloadProgress) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &platformUpgradeResponse_Progress{v}
}

func (x *PlatformUpgradeResponse) SetTaskProgress(v *TaskProgress) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &platformUpgradeResponse_TaskProgress{v}
}

func (x *PlatformUpgradeResponse) SetResult(v *PlatformUpgradeResponse_Result) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &platformUpgradeResponse_Result_{v}
}

func (x *PlatformUpgradeResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *PlatformUpgradeResponse) HasProgress() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*platformUpgradeResponse_Progress)
	return ok
}

func (x *PlatformUpgradeResponse) HasTaskProgress() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*platformUpgradeResponse_TaskProgress)
	return ok
}

func (x *PlatformUpgradeResponse) HasResult() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*platformUpgradeResponse_Result_)
	return ok
}

func (x *PlatformUpgradeResponse) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *PlatformUpgradeResponse) ClearProgress() {
	if _, ok := x.xxx_hidden_Message.(*platformUpgradeResponse_Progress); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *PlatformUpgradeResponse) ClearTaskProgress() {
	if _, ok := x.xxx_hidden_Message.(*platformUpgradeResponse_TaskProgress); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *PlatformUpgradeResponse) ClearResult() {
	if _, ok := x.xxx_hidden_Message.(*platformUpgradeResponse_Result_); ok {
		x.xxx_hidden_Message = nil
	}
}

const PlatformUpgradeResponse_Message_not_set_case case_PlatformUpgradeResponse_Message = 0
const PlatformUpgradeResponse_Progress_case case_PlatformUpgradeResponse_Message = 1
const PlatformUpgradeResponse_TaskProgress_case case_PlatformUpgradeResponse_Message = 2
const PlatformUpgradeResponse_Result_case case_PlatformUpgradeResponse_Message = 3

func (x *PlatformUpgradeResponse) WhichMessage() case_PlatformUpgradeResponse_Message {
	if x == nil {
		return PlatformUpgradeResponse_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *platformUpgradeResponse_Progress:
		return PlatformUpgradeResponse_Progress_case
	case *platformUpgradeResponse_TaskProgress:
		return PlatformUpgradeResponse_TaskProgress_case
	case *platformUpgradeResponse_Result_:
		return PlatformUpgradeResponse_Result_case
	default:
		return PlatformUpgradeResponse_Message_not_set_case
	}
}

type PlatformUpgradeResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Message:
	// Progress of the downloads of the platform and tool files.
	Progress *DownloadProgress
	// Description of the current stage of the upgrade.
	TaskProgress *TaskProgress
	// The upgrade result.
	Result *PlatformUpgradeResponse_Result
	// -- end of xxx_hidden_Message
}

func (b0 PlatformUpgradeResponse_builder) Build() *PlatformUpgradeResponse {
	m0 := &PlatformUpgradeResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Progress != nil {
		x.xxx_hidden_Message = &platformUpgradeResponse_Progress{b.Progress}
	}
	if b.TaskProgress != nil {
		x.xxx_hidden_Message = &platformUpgradeResponse_TaskProgress{b.TaskProgress}
	}
	if b.Result != nil {
		x.xxx_hidden_Message = &platformUpgradeResponse_Result_{b.Result}
	}
	return m0
}

type case_PlatformUpgradeResponse_Message protoreflect.FieldNumber

func (x case_PlatformUpgradeResponse_Message) String() string {
	md := file_cc_arduino_cli_commands_v1_core_proto_msgTypes[9].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isPlatformUpgradeResponse_Message interface {
	isPlatformUpgradeResponse_Message()
}

type platformUpgradeResponse_Progress struct {
	// Progress of the downloads of the platform and tool files.
	Progress *DownloadProgress `protobuf:"bytes,1,opt,name=progress,oneof"`
}

type platformUpgradeResponse_TaskProgress struct {
	// Description of the current stage of the upgrade.
	TaskProgress *TaskProgress `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,oneof"`
}

type platformUpgradeResponse_Result_ struct {
	// The upgrade result.
	Result *PlatformUpgradeResponse_Result `protobuf:"bytes,3,opt,name=result,oneof"`
}

func (*platformUpgradeResponse_Progress) isPlatformUpgradeResponse_Message() {}

func (*platformUpgradeResponse_TaskProgress) isPlatformUpgradeResponse_Message() {}

func (*platformUpgradeResponse_Result_) isPlatformUpgradeResponse_Message() {}

type PlatformSearchRequest struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance          *Instance              `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	xxx_hidden_SearchArgs        *string                `protobuf:"bytes,2,opt,name=search_args,json=searchArgs" json:"search_args,omitempty"`
	xxx_hidden_ManuallyInstalled bool                   `protobuf:"varint,3,opt,name=manually_installed,json=manuallyInstalled" json:"manually_installed,omitempty"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *PlatformSearchRequest) Reset() {
	*x = PlatformSearchRequest{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformSearchRequest) ProtoMessage() {}

func (x *PlatformSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlatformSearchRequest) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *PlatformSearchRequest) GetSearchArgs() string {
	if x != nil {
		if x.xxx_hidden_SearchArgs != nil {
			return *x.xxx_hidden_SearchArgs
		}
		return ""
	}
	return ""
}

func (x *PlatformSearchRequest) GetManuallyInstalled() bool {
	if x != nil {
		return x.xxx_hidden_ManuallyInstalled
	}
	return false
}

func (x *PlatformSearchRequest) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *PlatformSearchRequest) SetSearchArgs(v string) {
	x.xxx_hidden_SearchArgs = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *PlatformSearchRequest) SetManuallyInstalled(v bool) {
	x.xxx_hidden_ManuallyInstalled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *PlatformSearchRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *PlatformSearchRequest) HasSearchArgs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PlatformSearchRequest) HasManuallyInstalled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PlatformSearchRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

func (x *PlatformSearchRequest) ClearSearchArgs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SearchArgs = nil
}

func (x *PlatformSearchRequest) ClearManuallyInstalled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ManuallyInstalled = false
}

type PlatformSearchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Arduino Core Service instance from the `Init` response.
	Instance *Instance
	// Keywords for the search.
	SearchArgs *string
	// Whether to show manually installed platforms. `false` causes to skip
	// manually installed platforms.
	ManuallyInstalled *bool
}

func (b0 PlatformSearchRequest_builder) Build() *PlatformSearchRequest {
	m0 := &PlatformSearchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	if b.SearchArgs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_SearchArgs = b.SearchArgs
	}
	if b.ManuallyInstalled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ManuallyInstalled = *b.ManuallyInstalled
	}
	return m0
}

type PlatformSearchResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SearchOutput *[]*PlatformSummary    `protobuf:"bytes,1,rep,name=search_output,json=searchOutput" json:"search_output,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PlatformSearchResponse) Reset() {
	*x = PlatformSearchResponse{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformSearchResponse) ProtoMessage() {}

func (x *PlatformSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlatformSearchResponse) GetSearchOutput() []*PlatformSummary {
	if x != nil {
		if x.xxx_hidden_SearchOutput != nil {
			return *x.xxx_hidden_SearchOutput
		}
	}
	return nil
}

func (x *PlatformSearchResponse) SetSearchOutput(v []*PlatformSummary) {
	x.xxx_hidden_SearchOutput = &v
}

type PlatformSearchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Results of the search.
	SearchOutput []*PlatformSummary
}

func (b0 PlatformSearchResponse_builder) Build() *PlatformSearchResponse {
	m0 := &PlatformSearchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SearchOutput = &b.SearchOutput
	return m0
}

type PlatformInstallResponse_Result struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformInstallResponse_Result) Reset() {
	*x = PlatformInstallResponse_Result{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformInstallResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformInstallResponse_Result) ProtoMessage() {}

func (x *PlatformInstallResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PlatformInstallResponse_Result_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PlatformInstallResponse_Result_builder) Build() *PlatformInstallResponse_Result {
	m0 := &PlatformInstallResponse_Result{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PlatformDownloadResponse_Result struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformDownloadResponse_Result) Reset() {
	*x = PlatformDownloadResponse_Result{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformDownloadResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformDownloadResponse_Result) ProtoMessage() {}

func (x *PlatformDownloadResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PlatformDownloadResponse_Result_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PlatformDownloadResponse_Result_builder) Build() *PlatformDownloadResponse_Result {
	m0 := &PlatformDownloadResponse_Result{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PlatformUninstallResponse_Result struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformUninstallResponse_Result) Reset() {
	*x = PlatformUninstallResponse_Result{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformUninstallResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformUninstallResponse_Result) ProtoMessage() {}

func (x *PlatformUninstallResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PlatformUninstallResponse_Result_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PlatformUninstallResponse_Result_builder) Build() *PlatformUninstallResponse_Result {
	m0 := &PlatformUninstallResponse_Result{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PlatformUpgradeResponse_Result struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Platform *Platform              `protobuf:"bytes,1,opt,name=platform" json:"platform,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlatformUpgradeResponse_Result) Reset() {
	*x = PlatformUpgradeResponse_Result{}
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformUpgradeResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformUpgradeResponse_Result) ProtoMessage() {}

func (x *PlatformUpgradeResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PlatformUpgradeResponse_Result) GetPlatform() *Platform {
	if x != nil {
		return x.xxx_hidden_Platform
	}
	return nil
}

func (x *PlatformUpgradeResponse_Result) SetPlatform(v *Platform) {
	x.xxx_hidden_Platform = v
}

func (x *PlatformUpgradeResponse_Result) HasPlatform() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Platform != nil
}

func (x *PlatformUpgradeResponse_Result) ClearPlatform() {
	x.xxx_hidden_Platform = nil
}

type PlatformUpgradeResponse_Result_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The upgraded platform.
	Platform *Platform
}

func (b0 PlatformUpgradeResponse_Result_builder) Build() *PlatformUpgradeResponse_Result {
	m0 := &PlatformUpgradeResponse_Result{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Platform = b.Platform
	return m0
}

var File_cc_arduino_cli_commands_v1_core_proto protoreflect.FileDescriptor

var file_cc_arduino_cli_commands_v1_core_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x69,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75,
	0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x2e, 0x76, 0x31, 0x1a, 0x27, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f,
	0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f,
	0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xc0, 0x02, 0x0a, 0x16, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63,
	0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x10,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x69,
	0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x70, 0x6f,
	0x73, 0x74, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0f, 0x73, 0x6b, 0x69, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x6f, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6e, 0x6f, 0x4f, 0x76, 0x65, 0x72, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x70, 0x72, 0x65,
	0x5f, 0x75, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x10, 0x73, 0x6b, 0x69, 0x70, 0x50, 0x72, 0x65, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6c, 0x6c, 0x22, 0xa1, 0x02, 0x0a, 0x17, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2c, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x48, 0x00,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x4f, 0x0a, 0x0d, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63,
	0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x0c, 0x74,
	0x61, 0x73, 0x6b, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x54, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x63, 0x63,
	0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x1a, 0x08, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x4c, 0x6f, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xc4,
	0x01, 0x0a, 0x17, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63,
	0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x10,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x69,
	0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xd2, 0x01, 0x0a, 0x18, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e,
	0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x55,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b,
	0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x08, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42,
	0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xd9, 0x01, 0x0a, 0x18, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x63, 0x2e, 0x61,
	0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x72, 0x63, 0x68,
	0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x6b, 0x69, 0x70,
	0x5f, 0x70, 0x72, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x73, 0x6b, 0x69, 0x70, 0x50, 0x72, 0x65, 0x55, 0x6e, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x22, 0xd9, 0x01, 0x0a, 0x19, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0d, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x70, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x63,
	0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x56, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69,
	0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x6e, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x08, 0x0a,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x41, 0x74, 0x4c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x83, 0x02, 0x0a, 0x16, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x70,
	0x67, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x08,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x29,
	0x0a, 0x10, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x72, 0x63,
	0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2a, 0x0a,
	0x11, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x73, 0x6b, 0x69, 0x70, 0x50, 0x6f,
	0x73, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x6b, 0x69,
	0x70, 0x5f, 0x70, 0x72, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x73, 0x6b, 0x69, 0x70, 0x50, 0x72, 0x65, 0x55, 0x6e,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x22, 0xe3, 0x02, 0x0a, 0x17, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69,
	0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x4f, 0x0a, 0x0d, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75,
	0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x48, 0x00, 0x52, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x54, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x3a, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x4a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x40, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e,
	0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa9, 0x01,
	0x0a, 0x15, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x63, 0x2e, 0x61,
	0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x72, 0x67, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x6d, 0x61,
	0x6e, 0x75, 0x61, 0x6c, 0x6c, 0x79, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x6c, 0x79,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x22, 0x6a, 0x0a, 0x16, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x63, 0x2e,
	0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x50, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x72, 0x64, 0x75,
	0x69, 0x6e, 0x6f, 0x2d, 0x63, 0x6c, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x63, 0x2f, 0x61,
	0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x92,
	0x03, 0x05, 0xd2, 0x3e, 0x02, 0x10, 0x03, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x70, 0xe8, 0x07,
}

var file_cc_arduino_cli_commands_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_cc_arduino_cli_commands_v1_core_proto_goTypes = []any{
	(*PlatformInstallRequest)(nil),           // 0: cc.arduino.cli.commands.v1.PlatformInstallRequest
	(*PlatformInstallResponse)(nil),          // 1: cc.arduino.cli.commands.v1.PlatformInstallResponse
	(*PlatformLoadingError)(nil),             // 2: cc.arduino.cli.commands.v1.PlatformLoadingError
	(*PlatformDownloadRequest)(nil),          // 3: cc.arduino.cli.commands.v1.PlatformDownloadRequest
	(*PlatformDownloadResponse)(nil),         // 4: cc.arduino.cli.commands.v1.PlatformDownloadResponse
	(*PlatformUninstallRequest)(nil),         // 5: cc.arduino.cli.commands.v1.PlatformUninstallRequest
	(*PlatformUninstallResponse)(nil),        // 6: cc.arduino.cli.commands.v1.PlatformUninstallResponse
	(*AlreadyAtLatestVersionError)(nil),      // 7: cc.arduino.cli.commands.v1.AlreadyAtLatestVersionError
	(*PlatformUpgradeRequest)(nil),           // 8: cc.arduino.cli.commands.v1.PlatformUpgradeRequest
	(*PlatformUpgradeResponse)(nil),          // 9: cc.arduino.cli.commands.v1.PlatformUpgradeResponse
	(*PlatformSearchRequest)(nil),            // 10: cc.arduino.cli.commands.v1.PlatformSearchRequest
	(*PlatformSearchResponse)(nil),           // 11: cc.arduino.cli.commands.v1.PlatformSearchResponse
	(*PlatformInstallResponse_Result)(nil),   // 12: cc.arduino.cli.commands.v1.PlatformInstallResponse.Result
	(*PlatformDownloadResponse_Result)(nil),  // 13: cc.arduino.cli.commands.v1.PlatformDownloadResponse.Result
	(*PlatformUninstallResponse_Result)(nil), // 14: cc.arduino.cli.commands.v1.PlatformUninstallResponse.Result
	(*PlatformUpgradeResponse_Result)(nil),   // 15: cc.arduino.cli.commands.v1.PlatformUpgradeResponse.Result
	(*Instance)(nil),                         // 16: cc.arduino.cli.commands.v1.Instance
	(*DownloadProgress)(nil),                 // 17: cc.arduino.cli.commands.v1.DownloadProgress
	(*TaskProgress)(nil),                     // 18: cc.arduino.cli.commands.v1.TaskProgress
	(*PlatformSummary)(nil),                  // 19: cc.arduino.cli.commands.v1.PlatformSummary
	(*Platform)(nil),                         // 20: cc.arduino.cli.commands.v1.Platform
}
var file_cc_arduino_cli_commands_v1_core_proto_depIdxs = []int32{
	16, // 0: cc.arduino.cli.commands.v1.PlatformInstallRequest.instance:type_name -> cc.arduino.cli.commands.v1.Instance
	17, // 1: cc.arduino.cli.commands.v1.PlatformInstallResponse.progress:type_name -> cc.arduino.cli.commands.v1.DownloadProgress
	18, // 2: cc.arduino.cli.commands.v1.PlatformInstallResponse.task_progress:type_name -> cc.arduino.cli.commands.v1.TaskProgress
	12, // 3: cc.arduino.cli.commands.v1.PlatformInstallResponse.result:type_name -> cc.arduino.cli.commands.v1.PlatformInstallResponse.Result
	16, // 4: cc.arduino.cli.commands.v1.PlatformDownloadRequest.instance:type_name -> cc.arduino.cli.commands.v1.Instance
	17, // 5: cc.arduino.cli.commands.v1.PlatformDownloadResponse.progress:type_name -> cc.arduino.cli.commands.v1.DownloadProgress
	13, // 6: cc.arduino.cli.commands.v1.PlatformDownloadResponse.result:type_name -> cc.arduino.cli.commands.v1.PlatformDownloadResponse.Result
	16, // 7: cc.arduino.cli.commands.v1.PlatformUninstallRequest.instance:type_name -> cc.arduino.cli.commands.v1.Instance
	18, // 8: cc.arduino.cli.commands.v1.PlatformUninstallResponse.task_progress:type_name -> cc.arduino.cli.commands.v1.TaskProgress
	14, // 9: cc.arduino.cli.commands.v1.PlatformUninstallResponse.result:type_name -> cc.arduino.cli.commands.v1.PlatformUninstallResponse.Result
	16, // 10: cc.arduino.cli.commands.v1.PlatformUpgradeRequest.instance:type_name -> cc.arduino.cli.commands.v1.Instance
	17, // 11: cc.arduino.cli.commands.v1.PlatformUpgradeResponse.progress:type_name -> cc.arduino.cli.commands.v1.DownloadProgress
	18, // 12: cc.arduino.cli.commands.v1.PlatformUpgradeResponse.task_progress:type_name -> cc.arduino.cli.commands.v1.TaskProgress
	15, // 13: cc.arduino.cli.commands.v1.PlatformUpgradeResponse.result:type_name -> cc.arduino.cli.commands.v1.PlatformUpgradeResponse.Result
	16, // 14: cc.arduino.cli.commands.v1.PlatformSearchRequest.instance:type_name -> cc.arduino.cli.commands.v1.Instance
	19, // 15: cc.arduino.cli.commands.v1.PlatformSearchResponse.search_output:type_name -> cc.arduino.cli.commands.v1.PlatformSummary
	20, // 16: cc.arduino.cli.commands.v1.PlatformUpgradeResponse.Result.platform:type_name -> cc.arduino.cli.commands.v1.Platform
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_cc_arduino_cli_commands_v1_core_proto_init() }
func file_cc_arduino_cli_commands_v1_core_proto_init() {
	if File_cc_arduino_cli_commands_v1_core_proto != nil {
		return
	}
	file_cc_arduino_cli_commands_v1_common_proto_init()
	file_cc_arduino_cli_commands_v1_core_proto_msgTypes[1].OneofWrappers = []any{
		(*platformInstallResponse_Progress)(nil),
		(*platformInstallResponse_TaskProgress)(nil),
		(*platformInstallResponse_Result_)(nil),
	}
	file_cc_arduino_cli_commands_v1_core_proto_msgTypes[4].OneofWrappers = []any{
		(*platformDownloadResponse_Progress)(nil),
		(*platformDownloadResponse_Result_)(nil),
	}
	file_cc_arduino_cli_commands_v1_core_proto_msgTypes[6].OneofWrappers = []any{
		(*platformUninstallResponse_TaskProgress)(nil),
		(*platformUninstallResponse_Result_)(nil),
	}
	file_cc_arduino_cli_commands_v1_core_proto_msgTypes[9].OneofWrappers = []any{
		(*platformUpgradeResponse_Progress)(nil),
		(*platformUpgradeResponse_TaskProgress)(nil),
		(*platformUpgradeResponse_Result_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cc_arduino_cli_commands_v1_core_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cc_arduino_cli_commands_v1_core_proto_goTypes,
		DependencyIndexes: file_cc_arduino_cli_commands_v1_core_proto_depIdxs,
		MessageInfos:      file_cc_arduino_cli_commands_v1_core_proto_msgTypes,
	}.Build()
	File_cc_arduino_cli_commands_v1_core_proto = out.File
	file_cc_arduino_cli_commands_v1_core_proto_rawDesc = nil
	file_cc_arduino_cli_commands_v1_core_proto_goTypes = nil
	file_cc_arduino_cli_commands_v1_core_proto_depIdxs = nil
}
