// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: cc/arduino/cli/commands/v1/debug.proto

package commands

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The top-level message sent by the client for the `Debug` method.
// Multiple `DebugRequest` messages can be sent but the first message
// must contain a `GetDebugConfigRequest` message to initialize the debug
// session. All subsequent messages must contain bytes to be sent to the debug
// session and must not contain a `GetDebugConfigRequest` message.
type DebugRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DebugRequest  *GetDebugConfigRequest `protobuf:"bytes,1,opt,name=debug_request,json=debugRequest" json:"debug_request,omitempty"`
	xxx_hidden_Data          []byte                 `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	xxx_hidden_SendInterrupt bool                   `protobuf:"varint,3,opt,name=send_interrupt,json=sendInterrupt" json:"send_interrupt,omitempty"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DebugRequest) Reset() {
	*x = DebugRequest{}
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugRequest) ProtoMessage() {}

func (x *DebugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DebugRequest) GetDebugRequest() *GetDebugConfigRequest {
	if x != nil {
		return x.xxx_hidden_DebugRequest
	}
	return nil
}

func (x *DebugRequest) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *DebugRequest) GetSendInterrupt() bool {
	if x != nil {
		return x.xxx_hidden_SendInterrupt
	}
	return false
}

func (x *DebugRequest) SetDebugRequest(v *GetDebugConfigRequest) {
	x.xxx_hidden_DebugRequest = v
}

func (x *DebugRequest) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *DebugRequest) SetSendInterrupt(v bool) {
	x.xxx_hidden_SendInterrupt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *DebugRequest) HasDebugRequest() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DebugRequest != nil
}

func (x *DebugRequest) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DebugRequest) HasSendInterrupt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DebugRequest) ClearDebugRequest() {
	x.xxx_hidden_DebugRequest = nil
}

func (x *DebugRequest) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

func (x *DebugRequest) ClearSendInterrupt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SendInterrupt = false
}

type DebugRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Provides information to the debug that specifies which is the target.
	// The first `DebugRequest` message must contain a `GetDebugConfigRequest`
	// message.
	DebugRequest *GetDebugConfigRequest
	// The data to be sent to the target being monitored.
	Data []byte
	// Set this to true to send and Interrupt signal to the debugger process.
	SendInterrupt *bool
}

func (b0 DebugRequest_builder) Build() *DebugRequest {
	m0 := &DebugRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DebugRequest = b.DebugRequest
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Data = b.Data
	}
	if b.SendInterrupt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_SendInterrupt = *b.SendInterrupt
	}
	return m0
}

// The streaming response may contain chunks of data from the debugger or an
// error.
type DebugResponse struct {
	state              protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Message isDebugResponse_Message `protobuf_oneof:"message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DebugResponse) Reset() {
	*x = DebugResponse{}
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugResponse) ProtoMessage() {}

func (x *DebugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DebugResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*debugResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *DebugResponse) GetResult() *DebugResponse_Result {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*debugResponse_Result_); ok {
			return x.Result
		}
	}
	return nil
}

func (x *DebugResponse) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Message = &debugResponse_Data{v}
}

func (x *DebugResponse) SetResult(v *DebugResponse_Result) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &debugResponse_Result_{v}
}

func (x *DebugResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *DebugResponse) HasData() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*debugResponse_Data)
	return ok
}

func (x *DebugResponse) HasResult() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*debugResponse_Result_)
	return ok
}

func (x *DebugResponse) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *DebugResponse) ClearData() {
	if _, ok := x.xxx_hidden_Message.(*debugResponse_Data); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *DebugResponse) ClearResult() {
	if _, ok := x.xxx_hidden_Message.(*debugResponse_Result_); ok {
		x.xxx_hidden_Message = nil
	}
}

const DebugResponse_Message_not_set_case case_DebugResponse_Message = 0
const DebugResponse_Data_case case_DebugResponse_Message = 1
const DebugResponse_Result_case case_DebugResponse_Message = 2

func (x *DebugResponse) WhichMessage() case_DebugResponse_Message {
	if x == nil {
		return DebugResponse_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *debugResponse_Data:
		return DebugResponse_Data_case
	case *debugResponse_Result_:
		return DebugResponse_Result_case
	default:
		return DebugResponse_Message_not_set_case
	}
}

type DebugResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Message:
	// Incoming data from the debugger tool.
	Data []byte
	// Debugging result.
	Result *DebugResponse_Result
	// -- end of xxx_hidden_Message
}

func (b0 DebugResponse_builder) Build() *DebugResponse {
	m0 := &DebugResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		x.xxx_hidden_Message = &debugResponse_Data{b.Data}
	}
	if b.Result != nil {
		x.xxx_hidden_Message = &debugResponse_Result_{b.Result}
	}
	return m0
}

type case_DebugResponse_Message protoreflect.FieldNumber

func (x case_DebugResponse_Message) String() string {
	md := file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isDebugResponse_Message interface {
	isDebugResponse_Message()
}

type debugResponse_Data struct {
	// Incoming data from the debugger tool.
	Data []byte `protobuf:"bytes,1,opt,name=data,oneof"`
}

type debugResponse_Result_ struct {
	// Debugging result.
	Result *DebugResponse_Result `protobuf:"bytes,2,opt,name=result,oneof"`
}

func (*debugResponse_Data) isDebugResponse_Message() {}

func (*debugResponse_Result_) isDebugResponse_Message() {}

type IsDebugSupportedRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance        *Instance              `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	xxx_hidden_Fqbn            *string                `protobuf:"bytes,2,opt,name=fqbn" json:"fqbn,omitempty"`
	xxx_hidden_Port            *Port                  `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	xxx_hidden_Interpreter     *string                `protobuf:"bytes,4,opt,name=interpreter" json:"interpreter,omitempty"`
	xxx_hidden_Programmer      *string                `protobuf:"bytes,5,opt,name=programmer" json:"programmer,omitempty"`
	xxx_hidden_DebugProperties []string               `protobuf:"bytes,6,rep,name=debug_properties,json=debugProperties" json:"debug_properties,omitempty"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *IsDebugSupportedRequest) Reset() {
	*x = IsDebugSupportedRequest{}
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsDebugSupportedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDebugSupportedRequest) ProtoMessage() {}

func (x *IsDebugSupportedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IsDebugSupportedRequest) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *IsDebugSupportedRequest) GetFqbn() string {
	if x != nil {
		if x.xxx_hidden_Fqbn != nil {
			return *x.xxx_hidden_Fqbn
		}
		return ""
	}
	return ""
}

func (x *IsDebugSupportedRequest) GetPort() *Port {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return nil
}

func (x *IsDebugSupportedRequest) GetInterpreter() string {
	if x != nil {
		if x.xxx_hidden_Interpreter != nil {
			return *x.xxx_hidden_Interpreter
		}
		return ""
	}
	return ""
}

func (x *IsDebugSupportedRequest) GetProgrammer() string {
	if x != nil {
		if x.xxx_hidden_Programmer != nil {
			return *x.xxx_hidden_Programmer
		}
		return ""
	}
	return ""
}

func (x *IsDebugSupportedRequest) GetDebugProperties() []string {
	if x != nil {
		return x.xxx_hidden_DebugProperties
	}
	return nil
}

func (x *IsDebugSupportedRequest) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *IsDebugSupportedRequest) SetFqbn(v string) {
	x.xxx_hidden_Fqbn = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *IsDebugSupportedRequest) SetPort(v *Port) {
	x.xxx_hidden_Port = v
}

func (x *IsDebugSupportedRequest) SetInterpreter(v string) {
	x.xxx_hidden_Interpreter = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *IsDebugSupportedRequest) SetProgrammer(v string) {
	x.xxx_hidden_Programmer = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *IsDebugSupportedRequest) SetDebugProperties(v []string) {
	x.xxx_hidden_DebugProperties = v
}

func (x *IsDebugSupportedRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *IsDebugSupportedRequest) HasFqbn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *IsDebugSupportedRequest) HasPort() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Port != nil
}

func (x *IsDebugSupportedRequest) HasInterpreter() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *IsDebugSupportedRequest) HasProgrammer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *IsDebugSupportedRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

func (x *IsDebugSupportedRequest) ClearFqbn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Fqbn = nil
}

func (x *IsDebugSupportedRequest) ClearPort() {
	x.xxx_hidden_Port = nil
}

func (x *IsDebugSupportedRequest) ClearInterpreter() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Interpreter = nil
}

func (x *IsDebugSupportedRequest) ClearProgrammer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Programmer = nil
}

type IsDebugSupportedRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Arduino Core Service instance from the `Init` response.
	Instance *Instance
	// Fully qualified board name of the board in use (e.g.,
	// `arduino:samd:mkr1000`).
	Fqbn *string
	// Port of the debugger (optional).
	Port *Port
	// Which GDB command interpreter to use.
	Interpreter *string
	// The programmer to use for debugging.
	Programmer *string
	// List of custom debug properties.
	DebugProperties []string
}

func (b0 IsDebugSupportedRequest_builder) Build() *IsDebugSupportedRequest {
	m0 := &IsDebugSupportedRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	if b.Fqbn != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Fqbn = b.Fqbn
	}
	x.xxx_hidden_Port = b.Port
	if b.Interpreter != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Interpreter = b.Interpreter
	}
	if b.Programmer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Programmer = b.Programmer
	}
	x.xxx_hidden_DebugProperties = b.DebugProperties
	return m0
}

type IsDebugSupportedResponse struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DebuggingSupported bool                   `protobuf:"varint,1,opt,name=debugging_supported,json=debuggingSupported" json:"debugging_supported,omitempty"`
	xxx_hidden_DebugFqbn          *string                `protobuf:"bytes,2,opt,name=debug_fqbn,json=debugFqbn" json:"debug_fqbn,omitempty"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *IsDebugSupportedResponse) Reset() {
	*x = IsDebugSupportedResponse{}
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsDebugSupportedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDebugSupportedResponse) ProtoMessage() {}

func (x *IsDebugSupportedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IsDebugSupportedResponse) GetDebuggingSupported() bool {
	if x != nil {
		return x.xxx_hidden_DebuggingSupported
	}
	return false
}

func (x *IsDebugSupportedResponse) GetDebugFqbn() string {
	if x != nil {
		if x.xxx_hidden_DebugFqbn != nil {
			return *x.xxx_hidden_DebugFqbn
		}
		return ""
	}
	return ""
}

func (x *IsDebugSupportedResponse) SetDebuggingSupported(v bool) {
	x.xxx_hidden_DebuggingSupported = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *IsDebugSupportedResponse) SetDebugFqbn(v string) {
	x.xxx_hidden_DebugFqbn = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *IsDebugSupportedResponse) HasDebuggingSupported() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *IsDebugSupportedResponse) HasDebugFqbn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *IsDebugSupportedResponse) ClearDebuggingSupported() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DebuggingSupported = false
}

func (x *IsDebugSupportedResponse) ClearDebugFqbn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DebugFqbn = nil
}

type IsDebugSupportedResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// True if debugging is supported.
	DebuggingSupported *bool
	// This is the same FQBN given in the IsDebugSupportedRequest but cleaned
	// up of the board options that do not affect the debugger configuration.
	// It may be used by clients/IDE to group slightly different boards option
	// selections under the same debug configuration.
	DebugFqbn *string
}

func (b0 IsDebugSupportedResponse_builder) Build() *IsDebugSupportedResponse {
	m0 := &IsDebugSupportedResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DebuggingSupported != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_DebuggingSupported = *b.DebuggingSupported
	}
	if b.DebugFqbn != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_DebugFqbn = b.DebugFqbn
	}
	return m0
}

type GetDebugConfigRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance        *Instance              `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	xxx_hidden_Fqbn            *string                `protobuf:"bytes,2,opt,name=fqbn" json:"fqbn,omitempty"`
	xxx_hidden_SketchPath      *string                `protobuf:"bytes,3,opt,name=sketch_path,json=sketchPath" json:"sketch_path,omitempty"`
	xxx_hidden_Port            *Port                  `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
	xxx_hidden_Interpreter     *string                `protobuf:"bytes,5,opt,name=interpreter" json:"interpreter,omitempty"`
	xxx_hidden_ImportDir       *string                `protobuf:"bytes,8,opt,name=import_dir,json=importDir" json:"import_dir,omitempty"`
	xxx_hidden_Programmer      *string                `protobuf:"bytes,9,opt,name=programmer" json:"programmer,omitempty"`
	xxx_hidden_DebugProperties []string               `protobuf:"bytes,10,rep,name=debug_properties,json=debugProperties" json:"debug_properties,omitempty"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GetDebugConfigRequest) Reset() {
	*x = GetDebugConfigRequest{}
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDebugConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebugConfigRequest) ProtoMessage() {}

func (x *GetDebugConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetDebugConfigRequest) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *GetDebugConfigRequest) GetFqbn() string {
	if x != nil {
		if x.xxx_hidden_Fqbn != nil {
			return *x.xxx_hidden_Fqbn
		}
		return ""
	}
	return ""
}

func (x *GetDebugConfigRequest) GetSketchPath() string {
	if x != nil {
		if x.xxx_hidden_SketchPath != nil {
			return *x.xxx_hidden_SketchPath
		}
		return ""
	}
	return ""
}

func (x *GetDebugConfigRequest) GetPort() *Port {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return nil
}

func (x *GetDebugConfigRequest) GetInterpreter() string {
	if x != nil {
		if x.xxx_hidden_Interpreter != nil {
			return *x.xxx_hidden_Interpreter
		}
		return ""
	}
	return ""
}

func (x *GetDebugConfigRequest) GetImportDir() string {
	if x != nil {
		if x.xxx_hidden_ImportDir != nil {
			return *x.xxx_hidden_ImportDir
		}
		return ""
	}
	return ""
}

func (x *GetDebugConfigRequest) GetProgrammer() string {
	if x != nil {
		if x.xxx_hidden_Programmer != nil {
			return *x.xxx_hidden_Programmer
		}
		return ""
	}
	return ""
}

func (x *GetDebugConfigRequest) GetDebugProperties() []string {
	if x != nil {
		return x.xxx_hidden_DebugProperties
	}
	return nil
}

func (x *GetDebugConfigRequest) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *GetDebugConfigRequest) SetFqbn(v string) {
	x.xxx_hidden_Fqbn = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *GetDebugConfigRequest) SetSketchPath(v string) {
	x.xxx_hidden_SketchPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *GetDebugConfigRequest) SetPort(v *Port) {
	x.xxx_hidden_Port = v
}

func (x *GetDebugConfigRequest) SetInterpreter(v string) {
	x.xxx_hidden_Interpreter = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *GetDebugConfigRequest) SetImportDir(v string) {
	x.xxx_hidden_ImportDir = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *GetDebugConfigRequest) SetProgrammer(v string) {
	x.xxx_hidden_Programmer = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *GetDebugConfigRequest) SetDebugProperties(v []string) {
	x.xxx_hidden_DebugProperties = v
}

func (x *GetDebugConfigRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *GetDebugConfigRequest) HasFqbn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetDebugConfigRequest) HasSketchPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetDebugConfigRequest) HasPort() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Port != nil
}

func (x *GetDebugConfigRequest) HasInterpreter() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *GetDebugConfigRequest) HasImportDir() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *GetDebugConfigRequest) HasProgrammer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *GetDebugConfigRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

func (x *GetDebugConfigRequest) ClearFqbn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Fqbn = nil
}

func (x *GetDebugConfigRequest) ClearSketchPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SketchPath = nil
}

func (x *GetDebugConfigRequest) ClearPort() {
	x.xxx_hidden_Port = nil
}

func (x *GetDebugConfigRequest) ClearInterpreter() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Interpreter = nil
}

func (x *GetDebugConfigRequest) ClearImportDir() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ImportDir = nil
}

func (x *GetDebugConfigRequest) ClearProgrammer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Programmer = nil
}

type GetDebugConfigRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Arduino Core Service instance from the `Init` response.
	Instance *Instance
	// Fully qualified board name of the board in use
	// (e.g., `arduino:samd:mkr1000`). If this is omitted, the FQBN attached to
	// the sketch will be used.
	Fqbn *string
	// Path to the sketch that is running on the board. The compiled executable
	// is expected to be located under this path.
	SketchPath *string
	// Port of the debugger (optional).
	Port *Port
	// Which GDB command interpreter to use.
	Interpreter *string
	// Directory containing the compiled executable. If `import_dir` is not
	// specified, the executable is assumed to be in
	// `{sketch_path}/build/{fqbn}/`.
	ImportDir *string
	// The programmer to use for debugging.
	Programmer *string
	// List of custom debug properties.
	DebugProperties []string
}

func (b0 GetDebugConfigRequest_builder) Build() *GetDebugConfigRequest {
	m0 := &GetDebugConfigRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	if b.Fqbn != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Fqbn = b.Fqbn
	}
	if b.SketchPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_SketchPath = b.SketchPath
	}
	x.xxx_hidden_Port = b.Port
	if b.Interpreter != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Interpreter = b.Interpreter
	}
	if b.ImportDir != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_ImportDir = b.ImportDir
	}
	if b.Programmer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_Programmer = b.Programmer
	}
	x.xxx_hidden_DebugProperties = b.DebugProperties
	return m0
}

type GetDebugConfigResponse struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Executable             *string                `protobuf:"bytes,1,opt,name=executable" json:"executable,omitempty"`
	xxx_hidden_Toolchain              *string                `protobuf:"bytes,2,opt,name=toolchain" json:"toolchain,omitempty"`
	xxx_hidden_ToolchainPath          *string                `protobuf:"bytes,3,opt,name=toolchain_path,json=toolchainPath" json:"toolchain_path,omitempty"`
	xxx_hidden_ToolchainPrefix        *string                `protobuf:"bytes,4,opt,name=toolchain_prefix,json=toolchainPrefix" json:"toolchain_prefix,omitempty"`
	xxx_hidden_Server                 *string                `protobuf:"bytes,5,opt,name=server" json:"server,omitempty"`
	xxx_hidden_ServerPath             *string                `protobuf:"bytes,6,opt,name=server_path,json=serverPath" json:"server_path,omitempty"`
	xxx_hidden_ToolchainConfiguration *anypb.Any             `protobuf:"bytes,7,opt,name=toolchain_configuration,json=toolchainConfiguration" json:"toolchain_configuration,omitempty"`
	xxx_hidden_ServerConfiguration    *anypb.Any             `protobuf:"bytes,8,opt,name=server_configuration,json=serverConfiguration" json:"server_configuration,omitempty"`
	xxx_hidden_CustomConfigs          map[string]string      `protobuf:"bytes,9,rep,name=custom_configs,json=customConfigs" json:"custom_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_SvdFile                *string                `protobuf:"bytes,10,opt,name=svd_file,json=svdFile" json:"svd_file,omitempty"`
	xxx_hidden_Programmer             *string                `protobuf:"bytes,11,opt,name=programmer" json:"programmer,omitempty"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *GetDebugConfigResponse) Reset() {
	*x = GetDebugConfigResponse{}
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDebugConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebugConfigResponse) ProtoMessage() {}

func (x *GetDebugConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetDebugConfigResponse) GetExecutable() string {
	if x != nil {
		if x.xxx_hidden_Executable != nil {
			return *x.xxx_hidden_Executable
		}
		return ""
	}
	return ""
}

func (x *GetDebugConfigResponse) GetToolchain() string {
	if x != nil {
		if x.xxx_hidden_Toolchain != nil {
			return *x.xxx_hidden_Toolchain
		}
		return ""
	}
	return ""
}

func (x *GetDebugConfigResponse) GetToolchainPath() string {
	if x != nil {
		if x.xxx_hidden_ToolchainPath != nil {
			return *x.xxx_hidden_ToolchainPath
		}
		return ""
	}
	return ""
}

func (x *GetDebugConfigResponse) GetToolchainPrefix() string {
	if x != nil {
		if x.xxx_hidden_ToolchainPrefix != nil {
			return *x.xxx_hidden_ToolchainPrefix
		}
		return ""
	}
	return ""
}

func (x *GetDebugConfigResponse) GetServer() string {
	if x != nil {
		if x.xxx_hidden_Server != nil {
			return *x.xxx_hidden_Server
		}
		return ""
	}
	return ""
}

func (x *GetDebugConfigResponse) GetServerPath() string {
	if x != nil {
		if x.xxx_hidden_ServerPath != nil {
			return *x.xxx_hidden_ServerPath
		}
		return ""
	}
	return ""
}

func (x *GetDebugConfigResponse) GetToolchainConfiguration() *anypb.Any {
	if x != nil {
		return x.xxx_hidden_ToolchainConfiguration
	}
	return nil
}

func (x *GetDebugConfigResponse) GetServerConfiguration() *anypb.Any {
	if x != nil {
		return x.xxx_hidden_ServerConfiguration
	}
	return nil
}

func (x *GetDebugConfigResponse) GetCustomConfigs() map[string]string {
	if x != nil {
		return x.xxx_hidden_CustomConfigs
	}
	return nil
}

func (x *GetDebugConfigResponse) GetSvdFile() string {
	if x != nil {
		if x.xxx_hidden_SvdFile != nil {
			return *x.xxx_hidden_SvdFile
		}
		return ""
	}
	return ""
}

func (x *GetDebugConfigResponse) GetProgrammer() string {
	if x != nil {
		if x.xxx_hidden_Programmer != nil {
			return *x.xxx_hidden_Programmer
		}
		return ""
	}
	return ""
}

func (x *GetDebugConfigResponse) SetExecutable(v string) {
	x.xxx_hidden_Executable = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 11)
}

func (x *GetDebugConfigResponse) SetToolchain(v string) {
	x.xxx_hidden_Toolchain = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 11)
}

func (x *GetDebugConfigResponse) SetToolchainPath(v string) {
	x.xxx_hidden_ToolchainPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 11)
}

func (x *GetDebugConfigResponse) SetToolchainPrefix(v string) {
	x.xxx_hidden_ToolchainPrefix = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 11)
}

func (x *GetDebugConfigResponse) SetServer(v string) {
	x.xxx_hidden_Server = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 11)
}

func (x *GetDebugConfigResponse) SetServerPath(v string) {
	x.xxx_hidden_ServerPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 11)
}

func (x *GetDebugConfigResponse) SetToolchainConfiguration(v *anypb.Any) {
	x.xxx_hidden_ToolchainConfiguration = v
}

func (x *GetDebugConfigResponse) SetServerConfiguration(v *anypb.Any) {
	x.xxx_hidden_ServerConfiguration = v
}

func (x *GetDebugConfigResponse) SetCustomConfigs(v map[string]string) {
	x.xxx_hidden_CustomConfigs = v
}

func (x *GetDebugConfigResponse) SetSvdFile(v string) {
	x.xxx_hidden_SvdFile = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 11)
}

func (x *GetDebugConfigResponse) SetProgrammer(v string) {
	x.xxx_hidden_Programmer = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 11)
}

func (x *GetDebugConfigResponse) HasExecutable() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetDebugConfigResponse) HasToolchain() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetDebugConfigResponse) HasToolchainPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetDebugConfigResponse) HasToolchainPrefix() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GetDebugConfigResponse) HasServer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *GetDebugConfigResponse) HasServerPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *GetDebugConfigResponse) HasToolchainConfiguration() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ToolchainConfiguration != nil
}

func (x *GetDebugConfigResponse) HasServerConfiguration() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ServerConfiguration != nil
}

func (x *GetDebugConfigResponse) HasSvdFile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *GetDebugConfigResponse) HasProgrammer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *GetDebugConfigResponse) ClearExecutable() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Executable = nil
}

func (x *GetDebugConfigResponse) ClearToolchain() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Toolchain = nil
}

func (x *GetDebugConfigResponse) ClearToolchainPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ToolchainPath = nil
}

func (x *GetDebugConfigResponse) ClearToolchainPrefix() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ToolchainPrefix = nil
}

func (x *GetDebugConfigResponse) ClearServer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Server = nil
}

func (x *GetDebugConfigResponse) ClearServerPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ServerPath = nil
}

func (x *GetDebugConfigResponse) ClearToolchainConfiguration() {
	x.xxx_hidden_ToolchainConfiguration = nil
}

func (x *GetDebugConfigResponse) ClearServerConfiguration() {
	x.xxx_hidden_ServerConfiguration = nil
}

func (x *GetDebugConfigResponse) ClearSvdFile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_SvdFile = nil
}

func (x *GetDebugConfigResponse) ClearProgrammer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_Programmer = nil
}

type GetDebugConfigResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The executable binary to debug.
	Executable *string
	// The toolchain type used for the build (for example "gcc").
	Toolchain *string
	// The toolchain directory.
	ToolchainPath *string
	// The toolchain architecture prefix (for example "arm-none-eabi").
	ToolchainPrefix *string
	// The GDB server type used to connect to the programmer/board (for example
	// "openocd").
	Server *string
	// The GDB server directory.
	ServerPath *string
	// Extra configuration parameters wrt toolchain.
	ToolchainConfiguration *anypb.Any
	// Extra configuration parameters wrt GDB server.
	ServerConfiguration *anypb.Any
	// Custom debugger configurations (not handled directly by Arduino CLI but
	// provided for 3rd party plugins/debuggers). The map keys identifies which
	// 3rd party plugin/debugger is referred, the map string values contains a
	// JSON configuration for it.
	CustomConfigs map[string]string
	// the SVD file to use.
	SvdFile *string
	// The programmer specified in the request.
	Programmer *string
}

func (b0 GetDebugConfigResponse_builder) Build() *GetDebugConfigResponse {
	m0 := &GetDebugConfigResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Executable != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 11)
		x.xxx_hidden_Executable = b.Executable
	}
	if b.Toolchain != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 11)
		x.xxx_hidden_Toolchain = b.Toolchain
	}
	if b.ToolchainPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 11)
		x.xxx_hidden_ToolchainPath = b.ToolchainPath
	}
	if b.ToolchainPrefix != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 11)
		x.xxx_hidden_ToolchainPrefix = b.ToolchainPrefix
	}
	if b.Server != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 11)
		x.xxx_hidden_Server = b.Server
	}
	if b.ServerPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 11)
		x.xxx_hidden_ServerPath = b.ServerPath
	}
	x.xxx_hidden_ToolchainConfiguration = b.ToolchainConfiguration
	x.xxx_hidden_ServerConfiguration = b.ServerConfiguration
	x.xxx_hidden_CustomConfigs = b.CustomConfigs
	if b.SvdFile != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 11)
		x.xxx_hidden_SvdFile = b.SvdFile
	}
	if b.Programmer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 11)
		x.xxx_hidden_Programmer = b.Programmer
	}
	return m0
}

// Configurations specific for the 'gcc' toolchain.
type DebugGCCToolchainConfiguration struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugGCCToolchainConfiguration) Reset() {
	*x = DebugGCCToolchainConfiguration{}
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugGCCToolchainConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugGCCToolchainConfiguration) ProtoMessage() {}

func (x *DebugGCCToolchainConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DebugGCCToolchainConfiguration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DebugGCCToolchainConfiguration_builder) Build() *DebugGCCToolchainConfiguration {
	m0 := &DebugGCCToolchainConfiguration{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Configuration specific for the 'openocd` server.
type DebugOpenOCDServerConfiguration struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path        *string                `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	xxx_hidden_ScriptsDir  *string                `protobuf:"bytes,2,opt,name=scripts_dir,json=scriptsDir" json:"scripts_dir,omitempty"`
	xxx_hidden_Scripts     []string               `protobuf:"bytes,3,rep,name=scripts" json:"scripts,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DebugOpenOCDServerConfiguration) Reset() {
	*x = DebugOpenOCDServerConfiguration{}
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugOpenOCDServerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugOpenOCDServerConfiguration) ProtoMessage() {}

func (x *DebugOpenOCDServerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DebugOpenOCDServerConfiguration) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *DebugOpenOCDServerConfiguration) GetScriptsDir() string {
	if x != nil {
		if x.xxx_hidden_ScriptsDir != nil {
			return *x.xxx_hidden_ScriptsDir
		}
		return ""
	}
	return ""
}

func (x *DebugOpenOCDServerConfiguration) GetScripts() []string {
	if x != nil {
		return x.xxx_hidden_Scripts
	}
	return nil
}

func (x *DebugOpenOCDServerConfiguration) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *DebugOpenOCDServerConfiguration) SetScriptsDir(v string) {
	x.xxx_hidden_ScriptsDir = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *DebugOpenOCDServerConfiguration) SetScripts(v []string) {
	x.xxx_hidden_Scripts = v
}

func (x *DebugOpenOCDServerConfiguration) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DebugOpenOCDServerConfiguration) HasScriptsDir() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DebugOpenOCDServerConfiguration) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Path = nil
}

func (x *DebugOpenOCDServerConfiguration) ClearScriptsDir() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ScriptsDir = nil
}

type DebugOpenOCDServerConfiguration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Path to openocd.
	Path *string
	// Path to openocd scripts.
	ScriptsDir *string
	// List of scripts to execute by openocd.
	Scripts []string
}

func (b0 DebugOpenOCDServerConfiguration_builder) Build() *DebugOpenOCDServerConfiguration {
	m0 := &DebugOpenOCDServerConfiguration{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Path = b.Path
	}
	if b.ScriptsDir != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ScriptsDir = b.ScriptsDir
	}
	x.xxx_hidden_Scripts = b.Scripts
	return m0
}

type DebugResponse_Result struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Error       *string                `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DebugResponse_Result) Reset() {
	*x = DebugResponse_Result{}
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugResponse_Result) ProtoMessage() {}

func (x *DebugResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DebugResponse_Result) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *DebugResponse_Result) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DebugResponse_Result) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DebugResponse_Result) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Error = nil
}

type DebugResponse_Result_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Incoming error output from the debugger tool.
	Error *string
}

func (b0 DebugResponse_Result_builder) Build() *DebugResponse_Result {
	m0 := &DebugResponse_Result{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

var File_cc_arduino_cli_commands_v1_debug_proto protoreflect.FileDescriptor

var file_cc_arduino_cli_commands_v1_debug_proto_rawDesc = []byte{
	0x0a, 0x26, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x69,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x62,
	0x75, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64,
	0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x73, 0x2e, 0x76, 0x31, 0x1a, 0x27, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f,
	0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25, 0x63,
	0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x67, 0x6f, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x0c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x56, 0x0a, 0x0d, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x63, 0x2e,
	0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x62, 0x75, 0x67,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0c, 0x64,
	0x65, 0x62, 0x75, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x25, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x75, 0x70,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x72, 0x75, 0x70, 0x74, 0x22, 0x9c, 0x01, 0x0a, 0x0d, 0x44, 0x65, 0x62, 0x75, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x4a,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30,
	0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x62, 0x75,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x1e, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x92, 0x02, 0x0a, 0x17, 0x49, 0x73, 0x44, 0x65, 0x62, 0x75,
	0x67, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x40, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f,
	0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x71, 0x62, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x66, 0x71, 0x62, 0x6e, 0x12, 0x34, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69,
	0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x12,
	0x29, 0x0a, 0x10, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x65, 0x62, 0x75, 0x67,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x22, 0x6a, 0x0a, 0x18, 0x49, 0x73,
	0x44, 0x65, 0x62, 0x75, 0x67, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x64, 0x65, 0x62, 0x75, 0x67, 0x67,
	0x69, 0x6e, 0x67, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x12, 0x64, 0x65, 0x62, 0x75, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x75,
	0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x62, 0x75, 0x67,
	0x5f, 0x66, 0x71, 0x62, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x62,
	0x75, 0x67, 0x46, 0x71, 0x62, 0x6e, 0x22, 0xd0, 0x02, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x62, 0x75, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x40, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e,
	0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x71, 0x62, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x71, 0x62, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6b, 0x65,
	0x74, 0x63, 0x68, 0x50, 0x61, 0x74, 0x68, 0x12, 0x34, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69,
	0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x69, 0x72, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x12, 0x29,
	0x0a, 0x10, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69,
	0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x22, 0xe4, 0x04, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x62, 0x75, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x6f, 0x6f, 0x6c,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x12, 0x29, 0x0a, 0x10, 0x74, 0x6f, 0x6f,
	0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x50, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x61, 0x74, 0x68, 0x12, 0x4d, 0x0a,
	0x17, 0x74, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x52, 0x16, 0x74, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x14,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x52, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x6c, 0x0a, 0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x45, 0x2e,
	0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x62, 0x75, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x76, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x76, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x1a, 0x40,
	0x0a, 0x12, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x20, 0x0a, 0x1e, 0x44, 0x65, 0x62, 0x75, 0x67, 0x47, 0x43, 0x43, 0x54, 0x6f, 0x6f, 0x6c,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x70, 0x0a, 0x1f, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4f, 0x70, 0x65, 0x6e, 0x4f,
	0x43, 0x44, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x73, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x44, 0x69, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x73, 0x42, 0x50, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69,
	0x6e, 0x6f, 0x2d, 0x63, 0x6c, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x63, 0x2f, 0x61, 0x72,
	0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x92, 0x03,
	0x05, 0xd2, 0x3e, 0x02, 0x10, 0x03, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x70, 0xe8, 0x07,
}

var file_cc_arduino_cli_commands_v1_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cc_arduino_cli_commands_v1_debug_proto_goTypes = []any{
	(*DebugRequest)(nil),                    // 0: cc.arduino.cli.commands.v1.DebugRequest
	(*DebugResponse)(nil),                   // 1: cc.arduino.cli.commands.v1.DebugResponse
	(*IsDebugSupportedRequest)(nil),         // 2: cc.arduino.cli.commands.v1.IsDebugSupportedRequest
	(*IsDebugSupportedResponse)(nil),        // 3: cc.arduino.cli.commands.v1.IsDebugSupportedResponse
	(*GetDebugConfigRequest)(nil),           // 4: cc.arduino.cli.commands.v1.GetDebugConfigRequest
	(*GetDebugConfigResponse)(nil),          // 5: cc.arduino.cli.commands.v1.GetDebugConfigResponse
	(*DebugGCCToolchainConfiguration)(nil),  // 6: cc.arduino.cli.commands.v1.DebugGCCToolchainConfiguration
	(*DebugOpenOCDServerConfiguration)(nil), // 7: cc.arduino.cli.commands.v1.DebugOpenOCDServerConfiguration
	(*DebugResponse_Result)(nil),            // 8: cc.arduino.cli.commands.v1.DebugResponse.Result
	nil,                                     // 9: cc.arduino.cli.commands.v1.GetDebugConfigResponse.CustomConfigsEntry
	(*Instance)(nil),                        // 10: cc.arduino.cli.commands.v1.Instance
	(*Port)(nil),                            // 11: cc.arduino.cli.commands.v1.Port
	(*anypb.Any)(nil),                       // 12: google.protobuf.Any
}
var file_cc_arduino_cli_commands_v1_debug_proto_depIdxs = []int32{
	4,  // 0: cc.arduino.cli.commands.v1.DebugRequest.debug_request:type_name -> cc.arduino.cli.commands.v1.GetDebugConfigRequest
	8,  // 1: cc.arduino.cli.commands.v1.DebugResponse.result:type_name -> cc.arduino.cli.commands.v1.DebugResponse.Result
	10, // 2: cc.arduino.cli.commands.v1.IsDebugSupportedRequest.instance:type_name -> cc.arduino.cli.commands.v1.Instance
	11, // 3: cc.arduino.cli.commands.v1.IsDebugSupportedRequest.port:type_name -> cc.arduino.cli.commands.v1.Port
	10, // 4: cc.arduino.cli.commands.v1.GetDebugConfigRequest.instance:type_name -> cc.arduino.cli.commands.v1.Instance
	11, // 5: cc.arduino.cli.commands.v1.GetDebugConfigRequest.port:type_name -> cc.arduino.cli.commands.v1.Port
	12, // 6: cc.arduino.cli.commands.v1.GetDebugConfigResponse.toolchain_configuration:type_name -> google.protobuf.Any
	12, // 7: cc.arduino.cli.commands.v1.GetDebugConfigResponse.server_configuration:type_name -> google.protobuf.Any
	9,  // 8: cc.arduino.cli.commands.v1.GetDebugConfigResponse.custom_configs:type_name -> cc.arduino.cli.commands.v1.GetDebugConfigResponse.CustomConfigsEntry
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_cc_arduino_cli_commands_v1_debug_proto_init() }
func file_cc_arduino_cli_commands_v1_debug_proto_init() {
	if File_cc_arduino_cli_commands_v1_debug_proto != nil {
		return
	}
	file_cc_arduino_cli_commands_v1_common_proto_init()
	file_cc_arduino_cli_commands_v1_port_proto_init()
	file_cc_arduino_cli_commands_v1_debug_proto_msgTypes[1].OneofWrappers = []any{
		(*debugResponse_Data)(nil),
		(*debugResponse_Result_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cc_arduino_cli_commands_v1_debug_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cc_arduino_cli_commands_v1_debug_proto_goTypes,
		DependencyIndexes: file_cc_arduino_cli_commands_v1_debug_proto_depIdxs,
		MessageInfos:      file_cc_arduino_cli_commands_v1_debug_proto_msgTypes,
	}.Build()
	File_cc_arduino_cli_commands_v1_debug_proto = out.File
	file_cc_arduino_cli_commands_v1_debug_proto_rawDesc = nil
	file_cc_arduino_cli_commands_v1_debug_proto_goTypes = nil
	file_cc_arduino_cli_commands_v1_debug_proto_depIdxs = nil
}
