// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: cc/arduino/cli/commands/v1/settings.proto

package commands

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration to apply to the given instance.
// Any missing field will be kept at the default value.
type Configuration struct {
	state                   protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Directories  *Configuration_Directories  `protobuf:"bytes,1,opt,name=directories" json:"directories,omitempty"`
	xxx_hidden_Network      *Configuration_Network      `protobuf:"bytes,2,opt,name=network" json:"network,omitempty"`
	xxx_hidden_Sketch       *Configuration_Sketch       `protobuf:"bytes,3,opt,name=sketch" json:"sketch,omitempty"`
	xxx_hidden_BuildCache   *Configuration_BuildCache   `protobuf:"bytes,4,opt,name=build_cache,json=buildCache" json:"build_cache,omitempty"`
	xxx_hidden_BoardManager *Configuration_BoardManager `protobuf:"bytes,5,opt,name=board_manager,json=boardManager" json:"board_manager,omitempty"`
	xxx_hidden_Daemon       *Configuration_Daemon       `protobuf:"bytes,6,opt,name=daemon" json:"daemon,omitempty"`
	xxx_hidden_Output       *Configuration_Output       `protobuf:"bytes,7,opt,name=output" json:"output,omitempty"`
	xxx_hidden_Logging      *Configuration_Logging      `protobuf:"bytes,8,opt,name=logging" json:"logging,omitempty"`
	xxx_hidden_Library      *Configuration_Library      `protobuf:"bytes,9,opt,name=library" json:"library,omitempty"`
	xxx_hidden_Updater      *Configuration_Updater      `protobuf:"bytes,10,opt,name=updater" json:"updater,omitempty"`
	xxx_hidden_Locale       *string                     `protobuf:"bytes,100,opt,name=locale" json:"locale,omitempty"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration) GetDirectories() *Configuration_Directories {
	if x != nil {
		return x.xxx_hidden_Directories
	}
	return nil
}

func (x *Configuration) GetNetwork() *Configuration_Network {
	if x != nil {
		return x.xxx_hidden_Network
	}
	return nil
}

func (x *Configuration) GetSketch() *Configuration_Sketch {
	if x != nil {
		return x.xxx_hidden_Sketch
	}
	return nil
}

func (x *Configuration) GetBuildCache() *Configuration_BuildCache {
	if x != nil {
		return x.xxx_hidden_BuildCache
	}
	return nil
}

func (x *Configuration) GetBoardManager() *Configuration_BoardManager {
	if x != nil {
		return x.xxx_hidden_BoardManager
	}
	return nil
}

func (x *Configuration) GetDaemon() *Configuration_Daemon {
	if x != nil {
		return x.xxx_hidden_Daemon
	}
	return nil
}

func (x *Configuration) GetOutput() *Configuration_Output {
	if x != nil {
		return x.xxx_hidden_Output
	}
	return nil
}

func (x *Configuration) GetLogging() *Configuration_Logging {
	if x != nil {
		return x.xxx_hidden_Logging
	}
	return nil
}

func (x *Configuration) GetLibrary() *Configuration_Library {
	if x != nil {
		return x.xxx_hidden_Library
	}
	return nil
}

func (x *Configuration) GetUpdater() *Configuration_Updater {
	if x != nil {
		return x.xxx_hidden_Updater
	}
	return nil
}

func (x *Configuration) GetLocale() string {
	if x != nil {
		if x.xxx_hidden_Locale != nil {
			return *x.xxx_hidden_Locale
		}
		return ""
	}
	return ""
}

func (x *Configuration) SetDirectories(v *Configuration_Directories) {
	x.xxx_hidden_Directories = v
}

func (x *Configuration) SetNetwork(v *Configuration_Network) {
	x.xxx_hidden_Network = v
}

func (x *Configuration) SetSketch(v *Configuration_Sketch) {
	x.xxx_hidden_Sketch = v
}

func (x *Configuration) SetBuildCache(v *Configuration_BuildCache) {
	x.xxx_hidden_BuildCache = v
}

func (x *Configuration) SetBoardManager(v *Configuration_BoardManager) {
	x.xxx_hidden_BoardManager = v
}

func (x *Configuration) SetDaemon(v *Configuration_Daemon) {
	x.xxx_hidden_Daemon = v
}

func (x *Configuration) SetOutput(v *Configuration_Output) {
	x.xxx_hidden_Output = v
}

func (x *Configuration) SetLogging(v *Configuration_Logging) {
	x.xxx_hidden_Logging = v
}

func (x *Configuration) SetLibrary(v *Configuration_Library) {
	x.xxx_hidden_Library = v
}

func (x *Configuration) SetUpdater(v *Configuration_Updater) {
	x.xxx_hidden_Updater = v
}

func (x *Configuration) SetLocale(v string) {
	x.xxx_hidden_Locale = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 11)
}

func (x *Configuration) HasDirectories() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Directories != nil
}

func (x *Configuration) HasNetwork() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Network != nil
}

func (x *Configuration) HasSketch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sketch != nil
}

func (x *Configuration) HasBuildCache() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BuildCache != nil
}

func (x *Configuration) HasBoardManager() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BoardManager != nil
}

func (x *Configuration) HasDaemon() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Daemon != nil
}

func (x *Configuration) HasOutput() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Output != nil
}

func (x *Configuration) HasLogging() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Logging != nil
}

func (x *Configuration) HasLibrary() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Library != nil
}

func (x *Configuration) HasUpdater() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Updater != nil
}

func (x *Configuration) HasLocale() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *Configuration) ClearDirectories() {
	x.xxx_hidden_Directories = nil
}

func (x *Configuration) ClearNetwork() {
	x.xxx_hidden_Network = nil
}

func (x *Configuration) ClearSketch() {
	x.xxx_hidden_Sketch = nil
}

func (x *Configuration) ClearBuildCache() {
	x.xxx_hidden_BuildCache = nil
}

func (x *Configuration) ClearBoardManager() {
	x.xxx_hidden_BoardManager = nil
}

func (x *Configuration) ClearDaemon() {
	x.xxx_hidden_Daemon = nil
}

func (x *Configuration) ClearOutput() {
	x.xxx_hidden_Output = nil
}

func (x *Configuration) ClearLogging() {
	x.xxx_hidden_Logging = nil
}

func (x *Configuration) ClearLibrary() {
	x.xxx_hidden_Library = nil
}

func (x *Configuration) ClearUpdater() {
	x.xxx_hidden_Updater = nil
}

func (x *Configuration) ClearLocale() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_Locale = nil
}

type Configuration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The directories configuration.
	Directories *Configuration_Directories
	// The network configuration.
	Network *Configuration_Network
	// The sketch configuration.
	Sketch *Configuration_Sketch
	// The build cache configuration.
	BuildCache *Configuration_BuildCache
	// The board manager configuration.
	BoardManager *Configuration_BoardManager
	// The daemon configuration.
	Daemon *Configuration_Daemon
	// The console output configuration.
	Output *Configuration_Output
	// The logging configuration.
	Logging *Configuration_Logging
	// The library configuration.
	Library *Configuration_Library
	// The updater configuration.
	Updater *Configuration_Updater
	// optional
	Locale *string
}

func (b0 Configuration_builder) Build() *Configuration {
	m0 := &Configuration{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Directories = b.Directories
	x.xxx_hidden_Network = b.Network
	x.xxx_hidden_Sketch = b.Sketch
	x.xxx_hidden_BuildCache = b.BuildCache
	x.xxx_hidden_BoardManager = b.BoardManager
	x.xxx_hidden_Daemon = b.Daemon
	x.xxx_hidden_Output = b.Output
	x.xxx_hidden_Logging = b.Logging
	x.xxx_hidden_Library = b.Library
	x.xxx_hidden_Updater = b.Updater
	if b.Locale != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 11)
		x.xxx_hidden_Locale = b.Locale
	}
	return m0
}

type ConfigurationGetRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationGetRequest) Reset() {
	*x = ConfigurationGetRequest{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationGetRequest) ProtoMessage() {}

func (x *ConfigurationGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConfigurationGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ConfigurationGetRequest_builder) Build() *ConfigurationGetRequest {
	m0 := &ConfigurationGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ConfigurationGetResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Configuration *Configuration         `protobuf:"bytes,1,opt,name=configuration" json:"configuration,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ConfigurationGetResponse) Reset() {
	*x = ConfigurationGetResponse{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationGetResponse) ProtoMessage() {}

func (x *ConfigurationGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigurationGetResponse) GetConfiguration() *Configuration {
	if x != nil {
		return x.xxx_hidden_Configuration
	}
	return nil
}

func (x *ConfigurationGetResponse) SetConfiguration(v *Configuration) {
	x.xxx_hidden_Configuration = v
}

func (x *ConfigurationGetResponse) HasConfiguration() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Configuration != nil
}

func (x *ConfigurationGetResponse) ClearConfiguration() {
	x.xxx_hidden_Configuration = nil
}

type ConfigurationGetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The current configuration.
	Configuration *Configuration
}

func (b0 ConfigurationGetResponse_builder) Build() *ConfigurationGetResponse {
	m0 := &ConfigurationGetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Configuration = b.Configuration
	return m0
}

type ConfigurationSaveRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SettingsFormat *string                `protobuf:"bytes,1,opt,name=settings_format,json=settingsFormat" json:"settings_format,omitempty"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ConfigurationSaveRequest) Reset() {
	*x = ConfigurationSaveRequest{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationSaveRequest) ProtoMessage() {}

func (x *ConfigurationSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigurationSaveRequest) GetSettingsFormat() string {
	if x != nil {
		if x.xxx_hidden_SettingsFormat != nil {
			return *x.xxx_hidden_SettingsFormat
		}
		return ""
	}
	return ""
}

func (x *ConfigurationSaveRequest) SetSettingsFormat(v string) {
	x.xxx_hidden_SettingsFormat = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ConfigurationSaveRequest) HasSettingsFormat() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConfigurationSaveRequest) ClearSettingsFormat() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SettingsFormat = nil
}

type ConfigurationSaveRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The format of the encoded settings, allowed values are "json" and "yaml".
	SettingsFormat *string
}

func (b0 ConfigurationSaveRequest_builder) Build() *ConfigurationSaveRequest {
	m0 := &ConfigurationSaveRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SettingsFormat != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_SettingsFormat = b.SettingsFormat
	}
	return m0
}

type ConfigurationSaveResponse struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EncodedSettings *string                `protobuf:"bytes,1,opt,name=encoded_settings,json=encodedSettings" json:"encoded_settings,omitempty"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ConfigurationSaveResponse) Reset() {
	*x = ConfigurationSaveResponse{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationSaveResponse) ProtoMessage() {}

func (x *ConfigurationSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigurationSaveResponse) GetEncodedSettings() string {
	if x != nil {
		if x.xxx_hidden_EncodedSettings != nil {
			return *x.xxx_hidden_EncodedSettings
		}
		return ""
	}
	return ""
}

func (x *ConfigurationSaveResponse) SetEncodedSettings(v string) {
	x.xxx_hidden_EncodedSettings = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ConfigurationSaveResponse) HasEncodedSettings() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConfigurationSaveResponse) ClearEncodedSettings() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EncodedSettings = nil
}

type ConfigurationSaveResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The encoded settings.
	EncodedSettings *string
}

func (b0 ConfigurationSaveResponse_builder) Build() *ConfigurationSaveResponse {
	m0 := &ConfigurationSaveResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EncodedSettings != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_EncodedSettings = b.EncodedSettings
	}
	return m0
}

type ConfigurationOpenRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EncodedSettings *string                `protobuf:"bytes,1,opt,name=encoded_settings,json=encodedSettings" json:"encoded_settings,omitempty"`
	xxx_hidden_SettingsFormat  *string                `protobuf:"bytes,2,opt,name=settings_format,json=settingsFormat" json:"settings_format,omitempty"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ConfigurationOpenRequest) Reset() {
	*x = ConfigurationOpenRequest{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationOpenRequest) ProtoMessage() {}

func (x *ConfigurationOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigurationOpenRequest) GetEncodedSettings() string {
	if x != nil {
		if x.xxx_hidden_EncodedSettings != nil {
			return *x.xxx_hidden_EncodedSettings
		}
		return ""
	}
	return ""
}

func (x *ConfigurationOpenRequest) GetSettingsFormat() string {
	if x != nil {
		if x.xxx_hidden_SettingsFormat != nil {
			return *x.xxx_hidden_SettingsFormat
		}
		return ""
	}
	return ""
}

func (x *ConfigurationOpenRequest) SetEncodedSettings(v string) {
	x.xxx_hidden_EncodedSettings = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ConfigurationOpenRequest) SetSettingsFormat(v string) {
	x.xxx_hidden_SettingsFormat = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ConfigurationOpenRequest) HasEncodedSettings() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConfigurationOpenRequest) HasSettingsFormat() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConfigurationOpenRequest) ClearEncodedSettings() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EncodedSettings = nil
}

func (x *ConfigurationOpenRequest) ClearSettingsFormat() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SettingsFormat = nil
}

type ConfigurationOpenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The encoded settings.
	EncodedSettings *string
	// The format of the encoded settings, allowed values are "json" and "yaml".
	SettingsFormat *string
}

func (b0 ConfigurationOpenRequest_builder) Build() *ConfigurationOpenRequest {
	m0 := &ConfigurationOpenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EncodedSettings != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_EncodedSettings = b.EncodedSettings
	}
	if b.SettingsFormat != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_SettingsFormat = b.SettingsFormat
	}
	return m0
}

type ConfigurationOpenResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Warnings []string               `protobuf:"bytes,1,rep,name=warnings" json:"warnings,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfigurationOpenResponse) Reset() {
	*x = ConfigurationOpenResponse{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationOpenResponse) ProtoMessage() {}

func (x *ConfigurationOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigurationOpenResponse) GetWarnings() []string {
	if x != nil {
		return x.xxx_hidden_Warnings
	}
	return nil
}

func (x *ConfigurationOpenResponse) SetWarnings(v []string) {
	x.xxx_hidden_Warnings = v
}

type ConfigurationOpenResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Warnings that occurred while opening the configuration (e.g. unknown keys,
	// or invalid values).
	Warnings []string
}

func (b0 ConfigurationOpenResponse_builder) Build() *ConfigurationOpenResponse {
	m0 := &ConfigurationOpenResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Warnings = b.Warnings
	return m0
}

type SettingsGetValueRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	xxx_hidden_ValueFormat *string                `protobuf:"bytes,2,opt,name=value_format,json=valueFormat" json:"value_format,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SettingsGetValueRequest) Reset() {
	*x = SettingsGetValueRequest{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsGetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsGetValueRequest) ProtoMessage() {}

func (x *SettingsGetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SettingsGetValueRequest) GetKey() string {
	if x != nil {
		if x.xxx_hidden_Key != nil {
			return *x.xxx_hidden_Key
		}
		return ""
	}
	return ""
}

func (x *SettingsGetValueRequest) GetValueFormat() string {
	if x != nil {
		if x.xxx_hidden_ValueFormat != nil {
			return *x.xxx_hidden_ValueFormat
		}
		return ""
	}
	return ""
}

func (x *SettingsGetValueRequest) SetKey(v string) {
	x.xxx_hidden_Key = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SettingsGetValueRequest) SetValueFormat(v string) {
	x.xxx_hidden_ValueFormat = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SettingsGetValueRequest) HasKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SettingsGetValueRequest) HasValueFormat() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SettingsGetValueRequest) ClearKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Key = nil
}

func (x *SettingsGetValueRequest) ClearValueFormat() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ValueFormat = nil
}

type SettingsGetValueRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The key to get.
	Key *string
	// The format of the encoded_value (default is "json", allowed values are
	// "json" and "yaml).
	ValueFormat *string
}

func (b0 SettingsGetValueRequest_builder) Build() *SettingsGetValueRequest {
	m0 := &SettingsGetValueRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Key != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Key = b.Key
	}
	if b.ValueFormat != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ValueFormat = b.ValueFormat
	}
	return m0
}

type SettingsGetValueResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EncodedValue *string                `protobuf:"bytes,1,opt,name=encoded_value,json=encodedValue" json:"encoded_value,omitempty"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SettingsGetValueResponse) Reset() {
	*x = SettingsGetValueResponse{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsGetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsGetValueResponse) ProtoMessage() {}

func (x *SettingsGetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SettingsGetValueResponse) GetEncodedValue() string {
	if x != nil {
		if x.xxx_hidden_EncodedValue != nil {
			return *x.xxx_hidden_EncodedValue
		}
		return ""
	}
	return ""
}

func (x *SettingsGetValueResponse) SetEncodedValue(v string) {
	x.xxx_hidden_EncodedValue = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SettingsGetValueResponse) HasEncodedValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SettingsGetValueResponse) ClearEncodedValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EncodedValue = nil
}

type SettingsGetValueResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The value of the key (encoded).
	EncodedValue *string
}

func (b0 SettingsGetValueResponse_builder) Build() *SettingsGetValueResponse {
	m0 := &SettingsGetValueResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EncodedValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_EncodedValue = b.EncodedValue
	}
	return m0
}

type SettingsSetValueRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key          *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	xxx_hidden_EncodedValue *string                `protobuf:"bytes,2,opt,name=encoded_value,json=encodedValue" json:"encoded_value,omitempty"`
	xxx_hidden_ValueFormat  *string                `protobuf:"bytes,3,opt,name=value_format,json=valueFormat" json:"value_format,omitempty"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SettingsSetValueRequest) Reset() {
	*x = SettingsSetValueRequest{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsSetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsSetValueRequest) ProtoMessage() {}

func (x *SettingsSetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SettingsSetValueRequest) GetKey() string {
	if x != nil {
		if x.xxx_hidden_Key != nil {
			return *x.xxx_hidden_Key
		}
		return ""
	}
	return ""
}

func (x *SettingsSetValueRequest) GetEncodedValue() string {
	if x != nil {
		if x.xxx_hidden_EncodedValue != nil {
			return *x.xxx_hidden_EncodedValue
		}
		return ""
	}
	return ""
}

func (x *SettingsSetValueRequest) GetValueFormat() string {
	if x != nil {
		if x.xxx_hidden_ValueFormat != nil {
			return *x.xxx_hidden_ValueFormat
		}
		return ""
	}
	return ""
}

func (x *SettingsSetValueRequest) SetKey(v string) {
	x.xxx_hidden_Key = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *SettingsSetValueRequest) SetEncodedValue(v string) {
	x.xxx_hidden_EncodedValue = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *SettingsSetValueRequest) SetValueFormat(v string) {
	x.xxx_hidden_ValueFormat = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *SettingsSetValueRequest) HasKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SettingsSetValueRequest) HasEncodedValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SettingsSetValueRequest) HasValueFormat() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SettingsSetValueRequest) ClearKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Key = nil
}

func (x *SettingsSetValueRequest) ClearEncodedValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EncodedValue = nil
}

func (x *SettingsSetValueRequest) ClearValueFormat() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ValueFormat = nil
}

type SettingsSetValueRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The key to change.
	Key *string
	// The new value (encoded), no objects, only scalar or array of scalars are
	// allowed.
	EncodedValue *string
	// The format of the encoded_value (default is "json", allowed values are
	// "json", "yaml" and "cli").
	ValueFormat *string
}

func (b0 SettingsSetValueRequest_builder) Build() *SettingsSetValueRequest {
	m0 := &SettingsSetValueRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Key != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Key = b.Key
	}
	if b.EncodedValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_EncodedValue = b.EncodedValue
	}
	if b.ValueFormat != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ValueFormat = b.ValueFormat
	}
	return m0
}

type SettingsSetValueResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsSetValueResponse) Reset() {
	*x = SettingsSetValueResponse{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsSetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsSetValueResponse) ProtoMessage() {}

func (x *SettingsSetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SettingsSetValueResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SettingsSetValueResponse_builder) Build() *SettingsSetValueResponse {
	m0 := &SettingsSetValueResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SettingsEnumerateRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsEnumerateRequest) Reset() {
	*x = SettingsEnumerateRequest{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsEnumerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsEnumerateRequest) ProtoMessage() {}

func (x *SettingsEnumerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SettingsEnumerateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SettingsEnumerateRequest_builder) Build() *SettingsEnumerateRequest {
	m0 := &SettingsEnumerateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SettingsEnumerateResponse struct {
	state              protoimpl.MessageState              `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*SettingsEnumerateResponse_Entry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SettingsEnumerateResponse) Reset() {
	*x = SettingsEnumerateResponse{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsEnumerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsEnumerateResponse) ProtoMessage() {}

func (x *SettingsEnumerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SettingsEnumerateResponse) GetEntries() []*SettingsEnumerateResponse_Entry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *SettingsEnumerateResponse) SetEntries(v []*SettingsEnumerateResponse_Entry) {
	x.xxx_hidden_Entries = &v
}

type SettingsEnumerateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The list of key/value pairs.
	Entries []*SettingsEnumerateResponse_Entry
}

func (b0 SettingsEnumerateResponse_builder) Build() *SettingsEnumerateResponse {
	m0 := &SettingsEnumerateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

type Configuration_Directories struct {
	state                  protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_Data        *string                            `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	xxx_hidden_User        *string                            `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	xxx_hidden_Downloads   *string                            `protobuf:"bytes,3,opt,name=downloads" json:"downloads,omitempty"`
	xxx_hidden_Builtin     *Configuration_Directories_Builtin `protobuf:"bytes,4,opt,name=builtin" json:"builtin,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Configuration_Directories) Reset() {
	*x = Configuration_Directories{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_Directories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_Directories) ProtoMessage() {}

func (x *Configuration_Directories) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_Directories) GetData() string {
	if x != nil {
		if x.xxx_hidden_Data != nil {
			return *x.xxx_hidden_Data
		}
		return ""
	}
	return ""
}

func (x *Configuration_Directories) GetUser() string {
	if x != nil {
		if x.xxx_hidden_User != nil {
			return *x.xxx_hidden_User
		}
		return ""
	}
	return ""
}

func (x *Configuration_Directories) GetDownloads() string {
	if x != nil {
		if x.xxx_hidden_Downloads != nil {
			return *x.xxx_hidden_Downloads
		}
		return ""
	}
	return ""
}

func (x *Configuration_Directories) GetBuiltin() *Configuration_Directories_Builtin {
	if x != nil {
		return x.xxx_hidden_Builtin
	}
	return nil
}

func (x *Configuration_Directories) SetData(v string) {
	x.xxx_hidden_Data = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Configuration_Directories) SetUser(v string) {
	x.xxx_hidden_User = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Configuration_Directories) SetDownloads(v string) {
	x.xxx_hidden_Downloads = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Configuration_Directories) SetBuiltin(v *Configuration_Directories_Builtin) {
	x.xxx_hidden_Builtin = v
}

func (x *Configuration_Directories) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Configuration_Directories) HasUser() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Configuration_Directories) HasDownloads() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Configuration_Directories) HasBuiltin() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Builtin != nil
}

func (x *Configuration_Directories) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

func (x *Configuration_Directories) ClearUser() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_User = nil
}

func (x *Configuration_Directories) ClearDownloads() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Downloads = nil
}

func (x *Configuration_Directories) ClearBuiltin() {
	x.xxx_hidden_Builtin = nil
}

type Configuration_Directories_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Data directory.
	Data *string
	// User directory.
	User *string
	// Downloads directory.
	Downloads *string
	// optional
	Builtin *Configuration_Directories_Builtin
}

func (b0 Configuration_Directories_builder) Build() *Configuration_Directories {
	m0 := &Configuration_Directories{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Data = b.Data
	}
	if b.User != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_User = b.User
	}
	if b.Downloads != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Downloads = b.Downloads
	}
	x.xxx_hidden_Builtin = b.Builtin
	return m0
}

type Configuration_Network struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ExtraUserAgent *string                `protobuf:"bytes,1,opt,name=extra_user_agent,json=extraUserAgent" json:"extra_user_agent,omitempty"`
	xxx_hidden_Proxy          *string                `protobuf:"bytes,2,opt,name=proxy" json:"proxy,omitempty"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Configuration_Network) Reset() {
	*x = Configuration_Network{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_Network) ProtoMessage() {}

func (x *Configuration_Network) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_Network) GetExtraUserAgent() string {
	if x != nil {
		if x.xxx_hidden_ExtraUserAgent != nil {
			return *x.xxx_hidden_ExtraUserAgent
		}
		return ""
	}
	return ""
}

func (x *Configuration_Network) GetProxy() string {
	if x != nil {
		if x.xxx_hidden_Proxy != nil {
			return *x.xxx_hidden_Proxy
		}
		return ""
	}
	return ""
}

func (x *Configuration_Network) SetExtraUserAgent(v string) {
	x.xxx_hidden_ExtraUserAgent = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Configuration_Network) SetProxy(v string) {
	x.xxx_hidden_Proxy = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Configuration_Network) HasExtraUserAgent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Configuration_Network) HasProxy() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Configuration_Network) ClearExtraUserAgent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ExtraUserAgent = nil
}

func (x *Configuration_Network) ClearProxy() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Proxy = nil
}

type Configuration_Network_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// optional
	ExtraUserAgent *string
	// optional
	Proxy *string
}

func (b0 Configuration_Network_builder) Build() *Configuration_Network {
	m0 := &Configuration_Network{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ExtraUserAgent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_ExtraUserAgent = b.ExtraUserAgent
	}
	if b.Proxy != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Proxy = b.Proxy
	}
	return m0
}

type Configuration_Sketch struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AlwaysExportBinaries bool                   `protobuf:"varint,1,opt,name=always_export_binaries,json=alwaysExportBinaries" json:"always_export_binaries,omitempty"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *Configuration_Sketch) Reset() {
	*x = Configuration_Sketch{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_Sketch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_Sketch) ProtoMessage() {}

func (x *Configuration_Sketch) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_Sketch) GetAlwaysExportBinaries() bool {
	if x != nil {
		return x.xxx_hidden_AlwaysExportBinaries
	}
	return false
}

func (x *Configuration_Sketch) SetAlwaysExportBinaries(v bool) {
	x.xxx_hidden_AlwaysExportBinaries = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Configuration_Sketch) HasAlwaysExportBinaries() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Configuration_Sketch) ClearAlwaysExportBinaries() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AlwaysExportBinaries = false
}

type Configuration_Sketch_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Set to true to always export binaries to the sketch directory.
	AlwaysExportBinaries *bool
}

func (b0 Configuration_Sketch_builder) Build() *Configuration_Sketch {
	m0 := &Configuration_Sketch{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AlwaysExportBinaries != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_AlwaysExportBinaries = *b.AlwaysExportBinaries
	}
	return m0
}

type Configuration_BuildCache struct {
	state                              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CompilationsBeforePurge uint64                 `protobuf:"varint,1,opt,name=compilations_before_purge,json=compilationsBeforePurge" json:"compilations_before_purge,omitempty"`
	xxx_hidden_TtlSecs                 uint64                 `protobuf:"varint,2,opt,name=ttl_secs,json=ttlSecs" json:"ttl_secs,omitempty"`
	XXX_raceDetectHookData             protoimpl.RaceDetectHookData
	XXX_presence                       [1]uint32
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *Configuration_BuildCache) Reset() {
	*x = Configuration_BuildCache{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_BuildCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_BuildCache) ProtoMessage() {}

func (x *Configuration_BuildCache) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_BuildCache) GetCompilationsBeforePurge() uint64 {
	if x != nil {
		return x.xxx_hidden_CompilationsBeforePurge
	}
	return 0
}

func (x *Configuration_BuildCache) GetTtlSecs() uint64 {
	if x != nil {
		return x.xxx_hidden_TtlSecs
	}
	return 0
}

func (x *Configuration_BuildCache) SetCompilationsBeforePurge(v uint64) {
	x.xxx_hidden_CompilationsBeforePurge = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Configuration_BuildCache) SetTtlSecs(v uint64) {
	x.xxx_hidden_TtlSecs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Configuration_BuildCache) HasCompilationsBeforePurge() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Configuration_BuildCache) HasTtlSecs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Configuration_BuildCache) ClearCompilationsBeforePurge() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CompilationsBeforePurge = 0
}

func (x *Configuration_BuildCache) ClearTtlSecs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TtlSecs = 0
}

type Configuration_BuildCache_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The minimum number of compilations before the cache is purged.
	CompilationsBeforePurge *uint64
	// Time to live of the cache in seconds.
	TtlSecs *uint64
}

func (b0 Configuration_BuildCache_builder) Build() *Configuration_BuildCache {
	m0 := &Configuration_BuildCache{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CompilationsBeforePurge != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_CompilationsBeforePurge = *b.CompilationsBeforePurge
	}
	if b.TtlSecs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_TtlSecs = *b.TtlSecs
	}
	return m0
}

type Configuration_BoardManager struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AdditionalUrls []string               `protobuf:"bytes,1,rep,name=additional_urls,json=additionalUrls" json:"additional_urls,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Configuration_BoardManager) Reset() {
	*x = Configuration_BoardManager{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_BoardManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_BoardManager) ProtoMessage() {}

func (x *Configuration_BoardManager) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_BoardManager) GetAdditionalUrls() []string {
	if x != nil {
		return x.xxx_hidden_AdditionalUrls
	}
	return nil
}

func (x *Configuration_BoardManager) SetAdditionalUrls(v []string) {
	x.xxx_hidden_AdditionalUrls = v
}

type Configuration_BoardManager_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Additional URLs to be used for the board manager.
	AdditionalUrls []string
}

func (b0 Configuration_BoardManager_builder) Build() *Configuration_BoardManager {
	m0 := &Configuration_BoardManager{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AdditionalUrls = b.AdditionalUrls
	return m0
}

type Configuration_Daemon struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Port        *string                `protobuf:"bytes,1,opt,name=port" json:"port,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Configuration_Daemon) Reset() {
	*x = Configuration_Daemon{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_Daemon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_Daemon) ProtoMessage() {}

func (x *Configuration_Daemon) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_Daemon) GetPort() string {
	if x != nil {
		if x.xxx_hidden_Port != nil {
			return *x.xxx_hidden_Port
		}
		return ""
	}
	return ""
}

func (x *Configuration_Daemon) SetPort(v string) {
	x.xxx_hidden_Port = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Configuration_Daemon) HasPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Configuration_Daemon) ClearPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Port = nil
}

type Configuration_Daemon_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The TCP port of the daemon.
	Port *string
}

func (b0 Configuration_Daemon_builder) Build() *Configuration_Daemon {
	m0 := &Configuration_Daemon{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Port != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Port = b.Port
	}
	return m0
}

type Configuration_Output struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NoColor     bool                   `protobuf:"varint,1,opt,name=no_color,json=noColor" json:"no_color,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Configuration_Output) Reset() {
	*x = Configuration_Output{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_Output) ProtoMessage() {}

func (x *Configuration_Output) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_Output) GetNoColor() bool {
	if x != nil {
		return x.xxx_hidden_NoColor
	}
	return false
}

func (x *Configuration_Output) SetNoColor(v bool) {
	x.xxx_hidden_NoColor = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Configuration_Output) HasNoColor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Configuration_Output) ClearNoColor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_NoColor = false
}

type Configuration_Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Set to true to disable coloring of the output.
	NoColor *bool
}

func (b0 Configuration_Output_builder) Build() *Configuration_Output {
	m0 := &Configuration_Output{}
	b, x := &b0, m0
	_, _ = b, x
	if b.NoColor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_NoColor = *b.NoColor
	}
	return m0
}

type Configuration_Logging struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Level       *string                `protobuf:"bytes,1,opt,name=level" json:"level,omitempty"`
	xxx_hidden_Format      *string                `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	xxx_hidden_File        *string                `protobuf:"bytes,3,opt,name=file" json:"file,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Configuration_Logging) Reset() {
	*x = Configuration_Logging{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_Logging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_Logging) ProtoMessage() {}

func (x *Configuration_Logging) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_Logging) GetLevel() string {
	if x != nil {
		if x.xxx_hidden_Level != nil {
			return *x.xxx_hidden_Level
		}
		return ""
	}
	return ""
}

func (x *Configuration_Logging) GetFormat() string {
	if x != nil {
		if x.xxx_hidden_Format != nil {
			return *x.xxx_hidden_Format
		}
		return ""
	}
	return ""
}

func (x *Configuration_Logging) GetFile() string {
	if x != nil {
		if x.xxx_hidden_File != nil {
			return *x.xxx_hidden_File
		}
		return ""
	}
	return ""
}

func (x *Configuration_Logging) SetLevel(v string) {
	x.xxx_hidden_Level = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Configuration_Logging) SetFormat(v string) {
	x.xxx_hidden_Format = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Configuration_Logging) SetFile(v string) {
	x.xxx_hidden_File = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Configuration_Logging) HasLevel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Configuration_Logging) HasFormat() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Configuration_Logging) HasFile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Configuration_Logging) ClearLevel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Level = nil
}

func (x *Configuration_Logging) ClearFormat() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Format = nil
}

func (x *Configuration_Logging) ClearFile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_File = nil
}

type Configuration_Logging_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The logging level.
	Level *string
	// The logging format.
	Format *string
	// optional
	File *string
}

func (b0 Configuration_Logging_builder) Build() *Configuration_Logging {
	m0 := &Configuration_Logging{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Level != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Level = b.Level
	}
	if b.Format != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Format = b.Format
	}
	if b.File != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_File = b.File
	}
	return m0
}

type Configuration_Library struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EnableUnsafeInstall bool                   `protobuf:"varint,1,opt,name=enable_unsafe_install,json=enableUnsafeInstall" json:"enable_unsafe_install,omitempty"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *Configuration_Library) Reset() {
	*x = Configuration_Library{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_Library) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_Library) ProtoMessage() {}

func (x *Configuration_Library) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_Library) GetEnableUnsafeInstall() bool {
	if x != nil {
		return x.xxx_hidden_EnableUnsafeInstall
	}
	return false
}

func (x *Configuration_Library) SetEnableUnsafeInstall(v bool) {
	x.xxx_hidden_EnableUnsafeInstall = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Configuration_Library) HasEnableUnsafeInstall() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Configuration_Library) ClearEnableUnsafeInstall() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EnableUnsafeInstall = false
}

type Configuration_Library_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Set to true to enable library installation from zip archives or git
	// repositories.
	EnableUnsafeInstall *bool
}

func (b0 Configuration_Library_builder) Build() *Configuration_Library {
	m0 := &Configuration_Library{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EnableUnsafeInstall != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_EnableUnsafeInstall = *b.EnableUnsafeInstall
	}
	return m0
}

type Configuration_Updater struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EnableNotification bool                   `protobuf:"varint,1,opt,name=enable_notification,json=enableNotification" json:"enable_notification,omitempty"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Configuration_Updater) Reset() {
	*x = Configuration_Updater{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_Updater) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_Updater) ProtoMessage() {}

func (x *Configuration_Updater) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_Updater) GetEnableNotification() bool {
	if x != nil {
		return x.xxx_hidden_EnableNotification
	}
	return false
}

func (x *Configuration_Updater) SetEnableNotification(v bool) {
	x.xxx_hidden_EnableNotification = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Configuration_Updater) HasEnableNotification() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Configuration_Updater) ClearEnableNotification() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EnableNotification = false
}

type Configuration_Updater_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Set to true to enable notifications for updates.
	EnableNotification *bool
}

func (b0 Configuration_Updater_builder) Build() *Configuration_Updater {
	m0 := &Configuration_Updater{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EnableNotification != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_EnableNotification = *b.EnableNotification
	}
	return m0
}

type Configuration_Directories_Builtin struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Libraries   *string                `protobuf:"bytes,1,opt,name=libraries" json:"libraries,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Configuration_Directories_Builtin) Reset() {
	*x = Configuration_Directories_Builtin{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_Directories_Builtin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_Directories_Builtin) ProtoMessage() {}

func (x *Configuration_Directories_Builtin) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_Directories_Builtin) GetLibraries() string {
	if x != nil {
		if x.xxx_hidden_Libraries != nil {
			return *x.xxx_hidden_Libraries
		}
		return ""
	}
	return ""
}

func (x *Configuration_Directories_Builtin) SetLibraries(v string) {
	x.xxx_hidden_Libraries = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Configuration_Directories_Builtin) HasLibraries() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Configuration_Directories_Builtin) ClearLibraries() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Libraries = nil
}

type Configuration_Directories_Builtin_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// optional
	Libraries *string
}

func (b0 Configuration_Directories_Builtin_builder) Build() *Configuration_Directories_Builtin {
	m0 := &Configuration_Directories_Builtin{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Libraries != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Libraries = b.Libraries
	}
	return m0
}

type SettingsEnumerateResponse_Entry struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	xxx_hidden_Type        *string                `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SettingsEnumerateResponse_Entry) Reset() {
	*x = SettingsEnumerateResponse_Entry{}
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsEnumerateResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsEnumerateResponse_Entry) ProtoMessage() {}

func (x *SettingsEnumerateResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_settings_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SettingsEnumerateResponse_Entry) GetKey() string {
	if x != nil {
		if x.xxx_hidden_Key != nil {
			return *x.xxx_hidden_Key
		}
		return ""
	}
	return ""
}

func (x *SettingsEnumerateResponse_Entry) GetType() string {
	if x != nil {
		if x.xxx_hidden_Type != nil {
			return *x.xxx_hidden_Type
		}
		return ""
	}
	return ""
}

func (x *SettingsEnumerateResponse_Entry) SetKey(v string) {
	x.xxx_hidden_Key = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SettingsEnumerateResponse_Entry) SetType(v string) {
	x.xxx_hidden_Type = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SettingsEnumerateResponse_Entry) HasKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SettingsEnumerateResponse_Entry) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SettingsEnumerateResponse_Entry) ClearKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Key = nil
}

func (x *SettingsEnumerateResponse_Entry) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = nil
}

type SettingsEnumerateResponse_Entry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The key.
	Key *string
	// The key type.
	Type *string
}

func (b0 SettingsEnumerateResponse_Entry_builder) Build() *SettingsEnumerateResponse_Entry {
	m0 := &SettingsEnumerateResponse_Entry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Key != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Key = b.Key
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Type = b.Type
	}
	return m0
}

var File_cc_arduino_cli_commands_v1_settings_proto protoreflect.FileDescriptor

var file_cc_arduino_cli_commands_v1_settings_proto_rawDesc = []byte{
	0x0a, 0x29, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x69,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x63, 0x63, 0x2e,
	0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x5f, 0x66, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd2, 0x0c, 0x0a, 0x0d, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x57, 0x0a, 0x0b,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x35, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63,
	0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x0b, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75,
	0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x12, 0x48, 0x0a, 0x06, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x30, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e,
	0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x6b,
	0x65, 0x74, 0x63, 0x68, 0x52, 0x06, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x12, 0x55, 0x0a, 0x0b,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x34, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63,
	0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x12, 0x5b, 0x0a, 0x0d, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x63, 0x63, 0x2e,
	0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x52, 0x0c, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x12, 0x48, 0x0a, 0x06, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x30, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x52, 0x06, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x63, 0x63, 0x2e,
	0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x4b, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69,
	0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e,
	0x67, 0x12, 0x4b, 0x0a, 0x07, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e,
	0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69,
	0x62, 0x72, 0x61, 0x72, 0x79, 0x52, 0x07, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x12, 0x4b,
	0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x31, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x72, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x65, 0x1a, 0xd5, 0x01, 0x0a, 0x0b, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x64,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x12, 0x57, 0x0a, 0x07, 0x62, 0x75, 0x69,
	0x6c, 0x74, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x63, 0x63, 0x2e,
	0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x74,
	0x69, 0x6e, 0x1a, 0x27, 0x0a, 0x07, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x49, 0x0a, 0x07, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x28, 0x0a, 0x10, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x65, 0x78, 0x74, 0x72, 0x61, 0x55, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x1a, 0x3e, 0x0a, 0x06, 0x53, 0x6b, 0x65, 0x74, 0x63, 0x68,
	0x12, 0x34, 0x0a, 0x16, 0x61, 0x6c, 0x77, 0x61, 0x79, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x5f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x14, 0x61, 0x6c, 0x77, 0x61, 0x79, 0x73, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x63, 0x0a, 0x0a, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x12, 0x3a, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x5f, 0x70, 0x75, 0x72, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x17, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x50, 0x75, 0x72, 0x67, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x74, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x74, 0x74, 0x6c, 0x53, 0x65, 0x63, 0x73, 0x1a, 0x37, 0x0a, 0x0c, 0x42,
	0x6f, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x61,
	0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x55, 0x72, 0x6c, 0x73, 0x1a, 0x1c, 0x0a, 0x06, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x1a, 0x23, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x6e, 0x6f, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x6e, 0x6f, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x1a, 0x4b, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x67, 0x69,
	0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x1a, 0x3d, 0x0a, 0x07, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x12,
	0x32, 0x0a, 0x15, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x75, 0x6e, 0x73, 0x61, 0x66, 0x65,
	0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x55, 0x6e, 0x73, 0x61, 0x66, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x1a, 0x3a, 0x0a, 0x07, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x12, 0x2f,
	0x0a, 0x13, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x19, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6b, 0x0a, 0x18, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x43, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x46, 0x0a, 0x19,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x61, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x22, 0x6e, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x29, 0x0a, 0x10, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x6e, 0x63, 0x6f,
	0x64, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x22, 0x37, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x4e, 0x0a,
	0x17, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x3f, 0x0a,
	0x18, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x73,
	0x0a, 0x17, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x65,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x53,
	0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1a, 0x0a, 0x18, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa1, 0x01, 0x0a, 0x19,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x63, 0x63, 0x2e,
	0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x45, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x1a, 0x2d, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42,
	0x50, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72,
	0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2d, 0x63, 0x6c,
	0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f,
	0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31,
	0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x92, 0x03, 0x05, 0xd2, 0x3e, 0x02, 0x10,
	0x03, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
}

var file_cc_arduino_cli_commands_v1_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_cc_arduino_cli_commands_v1_settings_proto_goTypes = []any{
	(*Configuration)(nil),                     // 0: cc.arduino.cli.commands.v1.Configuration
	(*ConfigurationGetRequest)(nil),           // 1: cc.arduino.cli.commands.v1.ConfigurationGetRequest
	(*ConfigurationGetResponse)(nil),          // 2: cc.arduino.cli.commands.v1.ConfigurationGetResponse
	(*ConfigurationSaveRequest)(nil),          // 3: cc.arduino.cli.commands.v1.ConfigurationSaveRequest
	(*ConfigurationSaveResponse)(nil),         // 4: cc.arduino.cli.commands.v1.ConfigurationSaveResponse
	(*ConfigurationOpenRequest)(nil),          // 5: cc.arduino.cli.commands.v1.ConfigurationOpenRequest
	(*ConfigurationOpenResponse)(nil),         // 6: cc.arduino.cli.commands.v1.ConfigurationOpenResponse
	(*SettingsGetValueRequest)(nil),           // 7: cc.arduino.cli.commands.v1.SettingsGetValueRequest
	(*SettingsGetValueResponse)(nil),          // 8: cc.arduino.cli.commands.v1.SettingsGetValueResponse
	(*SettingsSetValueRequest)(nil),           // 9: cc.arduino.cli.commands.v1.SettingsSetValueRequest
	(*SettingsSetValueResponse)(nil),          // 10: cc.arduino.cli.commands.v1.SettingsSetValueResponse
	(*SettingsEnumerateRequest)(nil),          // 11: cc.arduino.cli.commands.v1.SettingsEnumerateRequest
	(*SettingsEnumerateResponse)(nil),         // 12: cc.arduino.cli.commands.v1.SettingsEnumerateResponse
	(*Configuration_Directories)(nil),         // 13: cc.arduino.cli.commands.v1.Configuration.Directories
	(*Configuration_Network)(nil),             // 14: cc.arduino.cli.commands.v1.Configuration.Network
	(*Configuration_Sketch)(nil),              // 15: cc.arduino.cli.commands.v1.Configuration.Sketch
	(*Configuration_BuildCache)(nil),          // 16: cc.arduino.cli.commands.v1.Configuration.BuildCache
	(*Configuration_BoardManager)(nil),        // 17: cc.arduino.cli.commands.v1.Configuration.BoardManager
	(*Configuration_Daemon)(nil),              // 18: cc.arduino.cli.commands.v1.Configuration.Daemon
	(*Configuration_Output)(nil),              // 19: cc.arduino.cli.commands.v1.Configuration.Output
	(*Configuration_Logging)(nil),             // 20: cc.arduino.cli.commands.v1.Configuration.Logging
	(*Configuration_Library)(nil),             // 21: cc.arduino.cli.commands.v1.Configuration.Library
	(*Configuration_Updater)(nil),             // 22: cc.arduino.cli.commands.v1.Configuration.Updater
	(*Configuration_Directories_Builtin)(nil), // 23: cc.arduino.cli.commands.v1.Configuration.Directories.Builtin
	(*SettingsEnumerateResponse_Entry)(nil),   // 24: cc.arduino.cli.commands.v1.SettingsEnumerateResponse.Entry
}
var file_cc_arduino_cli_commands_v1_settings_proto_depIdxs = []int32{
	13, // 0: cc.arduino.cli.commands.v1.Configuration.directories:type_name -> cc.arduino.cli.commands.v1.Configuration.Directories
	14, // 1: cc.arduino.cli.commands.v1.Configuration.network:type_name -> cc.arduino.cli.commands.v1.Configuration.Network
	15, // 2: cc.arduino.cli.commands.v1.Configuration.sketch:type_name -> cc.arduino.cli.commands.v1.Configuration.Sketch
	16, // 3: cc.arduino.cli.commands.v1.Configuration.build_cache:type_name -> cc.arduino.cli.commands.v1.Configuration.BuildCache
	17, // 4: cc.arduino.cli.commands.v1.Configuration.board_manager:type_name -> cc.arduino.cli.commands.v1.Configuration.BoardManager
	18, // 5: cc.arduino.cli.commands.v1.Configuration.daemon:type_name -> cc.arduino.cli.commands.v1.Configuration.Daemon
	19, // 6: cc.arduino.cli.commands.v1.Configuration.output:type_name -> cc.arduino.cli.commands.v1.Configuration.Output
	20, // 7: cc.arduino.cli.commands.v1.Configuration.logging:type_name -> cc.arduino.cli.commands.v1.Configuration.Logging
	21, // 8: cc.arduino.cli.commands.v1.Configuration.library:type_name -> cc.arduino.cli.commands.v1.Configuration.Library
	22, // 9: cc.arduino.cli.commands.v1.Configuration.updater:type_name -> cc.arduino.cli.commands.v1.Configuration.Updater
	0,  // 10: cc.arduino.cli.commands.v1.ConfigurationGetResponse.configuration:type_name -> cc.arduino.cli.commands.v1.Configuration
	24, // 11: cc.arduino.cli.commands.v1.SettingsEnumerateResponse.entries:type_name -> cc.arduino.cli.commands.v1.SettingsEnumerateResponse.Entry
	23, // 12: cc.arduino.cli.commands.v1.Configuration.Directories.builtin:type_name -> cc.arduino.cli.commands.v1.Configuration.Directories.Builtin
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cc_arduino_cli_commands_v1_settings_proto_init() }
func file_cc_arduino_cli_commands_v1_settings_proto_init() {
	if File_cc_arduino_cli_commands_v1_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cc_arduino_cli_commands_v1_settings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cc_arduino_cli_commands_v1_settings_proto_goTypes,
		DependencyIndexes: file_cc_arduino_cli_commands_v1_settings_proto_depIdxs,
		MessageInfos:      file_cc_arduino_cli_commands_v1_settings_proto_msgTypes,
	}.Build()
	File_cc_arduino_cli_commands_v1_settings_proto = out.File
	file_cc_arduino_cli_commands_v1_settings_proto_rawDesc = nil
	file_cc_arduino_cli_commands_v1_settings_proto_goTypes = nil
	file_cc_arduino_cli_commands_v1_settings_proto_depIdxs = nil
}
