// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: cc/arduino/cli/commands/v1/upload.proto

package commands

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance         *Instance              `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	xxx_hidden_Fqbn             *string                `protobuf:"bytes,2,opt,name=fqbn" json:"fqbn,omitempty"`
	xxx_hidden_SketchPath       *string                `protobuf:"bytes,3,opt,name=sketch_path,json=sketchPath" json:"sketch_path,omitempty"`
	xxx_hidden_Port             *Port                  `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
	xxx_hidden_Verbose          bool                   `protobuf:"varint,5,opt,name=verbose" json:"verbose,omitempty"`
	xxx_hidden_Verify           bool                   `protobuf:"varint,6,opt,name=verify" json:"verify,omitempty"`
	xxx_hidden_ImportFile       *string                `protobuf:"bytes,7,opt,name=import_file,json=importFile" json:"import_file,omitempty"`
	xxx_hidden_ImportDir        *string                `protobuf:"bytes,8,opt,name=import_dir,json=importDir" json:"import_dir,omitempty"`
	xxx_hidden_Programmer       *string                `protobuf:"bytes,9,opt,name=programmer" json:"programmer,omitempty"`
	xxx_hidden_DryRun           bool                   `protobuf:"varint,10,opt,name=dry_run,json=dryRun" json:"dry_run,omitempty"`
	xxx_hidden_UserFields       map[string]string      `protobuf:"bytes,11,rep,name=user_fields,json=userFields" json:"user_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_UploadProperties []string               `protobuf:"bytes,12,rep,name=upload_properties,json=uploadProperties" json:"upload_properties,omitempty"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadRequest) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *UploadRequest) GetFqbn() string {
	if x != nil {
		if x.xxx_hidden_Fqbn != nil {
			return *x.xxx_hidden_Fqbn
		}
		return ""
	}
	return ""
}

func (x *UploadRequest) GetSketchPath() string {
	if x != nil {
		if x.xxx_hidden_SketchPath != nil {
			return *x.xxx_hidden_SketchPath
		}
		return ""
	}
	return ""
}

func (x *UploadRequest) GetPort() *Port {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return nil
}

func (x *UploadRequest) GetVerbose() bool {
	if x != nil {
		return x.xxx_hidden_Verbose
	}
	return false
}

func (x *UploadRequest) GetVerify() bool {
	if x != nil {
		return x.xxx_hidden_Verify
	}
	return false
}

func (x *UploadRequest) GetImportFile() string {
	if x != nil {
		if x.xxx_hidden_ImportFile != nil {
			return *x.xxx_hidden_ImportFile
		}
		return ""
	}
	return ""
}

func (x *UploadRequest) GetImportDir() string {
	if x != nil {
		if x.xxx_hidden_ImportDir != nil {
			return *x.xxx_hidden_ImportDir
		}
		return ""
	}
	return ""
}

func (x *UploadRequest) GetProgrammer() string {
	if x != nil {
		if x.xxx_hidden_Programmer != nil {
			return *x.xxx_hidden_Programmer
		}
		return ""
	}
	return ""
}

func (x *UploadRequest) GetDryRun() bool {
	if x != nil {
		return x.xxx_hidden_DryRun
	}
	return false
}

func (x *UploadRequest) GetUserFields() map[string]string {
	if x != nil {
		return x.xxx_hidden_UserFields
	}
	return nil
}

func (x *UploadRequest) GetUploadProperties() []string {
	if x != nil {
		return x.xxx_hidden_UploadProperties
	}
	return nil
}

func (x *UploadRequest) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *UploadRequest) SetFqbn(v string) {
	x.xxx_hidden_Fqbn = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 12)
}

func (x *UploadRequest) SetSketchPath(v string) {
	x.xxx_hidden_SketchPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 12)
}

func (x *UploadRequest) SetPort(v *Port) {
	x.xxx_hidden_Port = v
}

func (x *UploadRequest) SetVerbose(v bool) {
	x.xxx_hidden_Verbose = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *UploadRequest) SetVerify(v bool) {
	x.xxx_hidden_Verify = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *UploadRequest) SetImportFile(v string) {
	x.xxx_hidden_ImportFile = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 12)
}

func (x *UploadRequest) SetImportDir(v string) {
	x.xxx_hidden_ImportDir = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 12)
}

func (x *UploadRequest) SetProgrammer(v string) {
	x.xxx_hidden_Programmer = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 12)
}

func (x *UploadRequest) SetDryRun(v bool) {
	x.xxx_hidden_DryRun = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 12)
}

func (x *UploadRequest) SetUserFields(v map[string]string) {
	x.xxx_hidden_UserFields = v
}

func (x *UploadRequest) SetUploadProperties(v []string) {
	x.xxx_hidden_UploadProperties = v
}

func (x *UploadRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *UploadRequest) HasFqbn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UploadRequest) HasSketchPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UploadRequest) HasPort() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Port != nil
}

func (x *UploadRequest) HasVerbose() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UploadRequest) HasVerify() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *UploadRequest) HasImportFile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *UploadRequest) HasImportDir() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *UploadRequest) HasProgrammer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *UploadRequest) HasDryRun() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *UploadRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

func (x *UploadRequest) ClearFqbn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Fqbn = nil
}

func (x *UploadRequest) ClearSketchPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SketchPath = nil
}

func (x *UploadRequest) ClearPort() {
	x.xxx_hidden_Port = nil
}

func (x *UploadRequest) ClearVerbose() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Verbose = false
}

func (x *UploadRequest) ClearVerify() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Verify = false
}

func (x *UploadRequest) ClearImportFile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_ImportFile = nil
}

func (x *UploadRequest) ClearImportDir() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_ImportDir = nil
}

func (x *UploadRequest) ClearProgrammer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Programmer = nil
}

func (x *UploadRequest) ClearDryRun() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_DryRun = false
}

type UploadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Arduino Core Service instance from the `Init` response.
	Instance *Instance
	// Fully qualified board name of the target board (e.g., `arduino:avr:uno`).
	// If this field is not defined, the FQBN of the board attached to the sketch
	// via the `BoardAttach` method is used.
	Fqbn *string
	// Path where the sketch to be uploaded is stored. Unless the `import_file`
	// field is defined, the compiled binary is assumed to be at the location and
	// filename under this path where it is saved by the `Compile` method.
	SketchPath *string
	// The port of the board.
	Port *Port
	// Whether to turn on verbose output during the upload.
	Verbose *bool
	// After upload, verify that the contents of the memory on the board match the
	// uploaded binary.
	Verify *bool
	// When `import_file` is specified, it overrides the `import_dir` and
	// `sketch_path` params.
	ImportFile *string
	// Custom path to a directory containing compiled files. When `import_dir` is
	// not specified, the standard build directory under `sketch_path` is used.
	ImportDir *string
	// The programmer to use for upload. If set an UploadUsingProgrammer is
	// triggered instead of a normal upload. The UploadUsingProgrammer call may
	// also be used for explicit error check.
	Programmer *string
	// If set to true, the actual upload will not be performed but a trace output
	// will be printed stdout. This is for debugging purposes.
	DryRun *bool
	// User provided fields usually used by upload tools that need authentication
	// or in any case fields that can be customized by the user at upload time
	// and cannot be known previously.
	// For more info:
	// https://arduino.github.io/arduino-cli/latest/platform-specification/#user-provided-fields
	UserFields map[string]string
	// List of custom upload properties.
	UploadProperties []string
}

func (b0 UploadRequest_builder) Build() *UploadRequest {
	m0 := &UploadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	if b.Fqbn != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 12)
		x.xxx_hidden_Fqbn = b.Fqbn
	}
	if b.SketchPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 12)
		x.xxx_hidden_SketchPath = b.SketchPath
	}
	x.xxx_hidden_Port = b.Port
	if b.Verbose != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_Verbose = *b.Verbose
	}
	if b.Verify != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_Verify = *b.Verify
	}
	if b.ImportFile != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 12)
		x.xxx_hidden_ImportFile = b.ImportFile
	}
	if b.ImportDir != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 12)
		x.xxx_hidden_ImportDir = b.ImportDir
	}
	if b.Programmer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 12)
		x.xxx_hidden_Programmer = b.Programmer
	}
	if b.DryRun != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 12)
		x.xxx_hidden_DryRun = *b.DryRun
	}
	x.xxx_hidden_UserFields = b.UserFields
	x.xxx_hidden_UploadProperties = b.UploadProperties
	return m0
}

type UploadResponse struct {
	state              protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Message isUploadResponse_Message `protobuf_oneof:"message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadResponse) GetOutStream() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*uploadResponse_OutStream); ok {
			return x.OutStream
		}
	}
	return nil
}

func (x *UploadResponse) GetErrStream() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*uploadResponse_ErrStream); ok {
			return x.ErrStream
		}
	}
	return nil
}

func (x *UploadResponse) GetResult() *UploadResult {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*uploadResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *UploadResponse) SetOutStream(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Message = &uploadResponse_OutStream{v}
}

func (x *UploadResponse) SetErrStream(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Message = &uploadResponse_ErrStream{v}
}

func (x *UploadResponse) SetResult(v *UploadResult) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &uploadResponse_Result{v}
}

func (x *UploadResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *UploadResponse) HasOutStream() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*uploadResponse_OutStream)
	return ok
}

func (x *UploadResponse) HasErrStream() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*uploadResponse_ErrStream)
	return ok
}

func (x *UploadResponse) HasResult() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*uploadResponse_Result)
	return ok
}

func (x *UploadResponse) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *UploadResponse) ClearOutStream() {
	if _, ok := x.xxx_hidden_Message.(*uploadResponse_OutStream); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *UploadResponse) ClearErrStream() {
	if _, ok := x.xxx_hidden_Message.(*uploadResponse_ErrStream); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *UploadResponse) ClearResult() {
	if _, ok := x.xxx_hidden_Message.(*uploadResponse_Result); ok {
		x.xxx_hidden_Message = nil
	}
}

const UploadResponse_Message_not_set_case case_UploadResponse_Message = 0
const UploadResponse_OutStream_case case_UploadResponse_Message = 1
const UploadResponse_ErrStream_case case_UploadResponse_Message = 2
const UploadResponse_Result_case case_UploadResponse_Message = 3

func (x *UploadResponse) WhichMessage() case_UploadResponse_Message {
	if x == nil {
		return UploadResponse_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *uploadResponse_OutStream:
		return UploadResponse_OutStream_case
	case *uploadResponse_ErrStream:
		return UploadResponse_ErrStream_case
	case *uploadResponse_Result:
		return UploadResponse_Result_case
	default:
		return UploadResponse_Message_not_set_case
	}
}

type UploadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Message:
	// The output of the upload process.
	OutStream []byte
	// The error output of the upload process.
	ErrStream []byte
	// The upload result.
	Result *UploadResult
	// -- end of xxx_hidden_Message
}

func (b0 UploadResponse_builder) Build() *UploadResponse {
	m0 := &UploadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.OutStream != nil {
		x.xxx_hidden_Message = &uploadResponse_OutStream{b.OutStream}
	}
	if b.ErrStream != nil {
		x.xxx_hidden_Message = &uploadResponse_ErrStream{b.ErrStream}
	}
	if b.Result != nil {
		x.xxx_hidden_Message = &uploadResponse_Result{b.Result}
	}
	return m0
}

type case_UploadResponse_Message protoreflect.FieldNumber

func (x case_UploadResponse_Message) String() string {
	md := file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUploadResponse_Message interface {
	isUploadResponse_Message()
}

type uploadResponse_OutStream struct {
	// The output of the upload process.
	OutStream []byte `protobuf:"bytes,1,opt,name=out_stream,json=outStream,oneof"`
}

type uploadResponse_ErrStream struct {
	// The error output of the upload process.
	ErrStream []byte `protobuf:"bytes,2,opt,name=err_stream,json=errStream,oneof"`
}

type uploadResponse_Result struct {
	// The upload result.
	Result *UploadResult `protobuf:"bytes,3,opt,name=result,oneof"`
}

func (*uploadResponse_OutStream) isUploadResponse_Message() {}

func (*uploadResponse_ErrStream) isUploadResponse_Message() {}

func (*uploadResponse_Result) isUploadResponse_Message() {}

type UploadResult struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UpdatedUploadPort *Port                  `protobuf:"bytes,1,opt,name=updated_upload_port,json=updatedUploadPort" json:"updated_upload_port,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *UploadResult) Reset() {
	*x = UploadResult{}
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResult) ProtoMessage() {}

func (x *UploadResult) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadResult) GetUpdatedUploadPort() *Port {
	if x != nil {
		return x.xxx_hidden_UpdatedUploadPort
	}
	return nil
}

func (x *UploadResult) SetUpdatedUploadPort(v *Port) {
	x.xxx_hidden_UpdatedUploadPort = v
}

func (x *UploadResult) HasUpdatedUploadPort() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedUploadPort != nil
}

func (x *UploadResult) ClearUpdatedUploadPort() {
	x.xxx_hidden_UpdatedUploadPort = nil
}

type UploadResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// When a board requires a port disconnection to perform the upload, this
	// field returns the port where the board reconnects after the upload.
	UpdatedUploadPort *Port
}

func (b0 UploadResult_builder) Build() *UploadResult {
	m0 := &UploadResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UpdatedUploadPort = b.UpdatedUploadPort
	return m0
}

type ProgrammerIsRequiredForUploadError struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgrammerIsRequiredForUploadError) Reset() {
	*x = ProgrammerIsRequiredForUploadError{}
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgrammerIsRequiredForUploadError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgrammerIsRequiredForUploadError) ProtoMessage() {}

func (x *ProgrammerIsRequiredForUploadError) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ProgrammerIsRequiredForUploadError_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ProgrammerIsRequiredForUploadError_builder) Build() *ProgrammerIsRequiredForUploadError {
	m0 := &ProgrammerIsRequiredForUploadError{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type UploadUsingProgrammerRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance         *Instance              `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	xxx_hidden_Fqbn             *string                `protobuf:"bytes,2,opt,name=fqbn" json:"fqbn,omitempty"`
	xxx_hidden_SketchPath       *string                `protobuf:"bytes,3,opt,name=sketch_path,json=sketchPath" json:"sketch_path,omitempty"`
	xxx_hidden_Port             *Port                  `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
	xxx_hidden_Verbose          bool                   `protobuf:"varint,5,opt,name=verbose" json:"verbose,omitempty"`
	xxx_hidden_Verify           bool                   `protobuf:"varint,6,opt,name=verify" json:"verify,omitempty"`
	xxx_hidden_ImportFile       *string                `protobuf:"bytes,7,opt,name=import_file,json=importFile" json:"import_file,omitempty"`
	xxx_hidden_ImportDir        *string                `protobuf:"bytes,8,opt,name=import_dir,json=importDir" json:"import_dir,omitempty"`
	xxx_hidden_Programmer       *string                `protobuf:"bytes,9,opt,name=programmer" json:"programmer,omitempty"`
	xxx_hidden_DryRun           bool                   `protobuf:"varint,10,opt,name=dry_run,json=dryRun" json:"dry_run,omitempty"`
	xxx_hidden_UserFields       map[string]string      `protobuf:"bytes,11,rep,name=user_fields,json=userFields" json:"user_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_UploadProperties []string               `protobuf:"bytes,12,rep,name=upload_properties,json=uploadProperties" json:"upload_properties,omitempty"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UploadUsingProgrammerRequest) Reset() {
	*x = UploadUsingProgrammerRequest{}
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadUsingProgrammerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadUsingProgrammerRequest) ProtoMessage() {}

func (x *UploadUsingProgrammerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadUsingProgrammerRequest) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *UploadUsingProgrammerRequest) GetFqbn() string {
	if x != nil {
		if x.xxx_hidden_Fqbn != nil {
			return *x.xxx_hidden_Fqbn
		}
		return ""
	}
	return ""
}

func (x *UploadUsingProgrammerRequest) GetSketchPath() string {
	if x != nil {
		if x.xxx_hidden_SketchPath != nil {
			return *x.xxx_hidden_SketchPath
		}
		return ""
	}
	return ""
}

func (x *UploadUsingProgrammerRequest) GetPort() *Port {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return nil
}

func (x *UploadUsingProgrammerRequest) GetVerbose() bool {
	if x != nil {
		return x.xxx_hidden_Verbose
	}
	return false
}

func (x *UploadUsingProgrammerRequest) GetVerify() bool {
	if x != nil {
		return x.xxx_hidden_Verify
	}
	return false
}

func (x *UploadUsingProgrammerRequest) GetImportFile() string {
	if x != nil {
		if x.xxx_hidden_ImportFile != nil {
			return *x.xxx_hidden_ImportFile
		}
		return ""
	}
	return ""
}

func (x *UploadUsingProgrammerRequest) GetImportDir() string {
	if x != nil {
		if x.xxx_hidden_ImportDir != nil {
			return *x.xxx_hidden_ImportDir
		}
		return ""
	}
	return ""
}

func (x *UploadUsingProgrammerRequest) GetProgrammer() string {
	if x != nil {
		if x.xxx_hidden_Programmer != nil {
			return *x.xxx_hidden_Programmer
		}
		return ""
	}
	return ""
}

func (x *UploadUsingProgrammerRequest) GetDryRun() bool {
	if x != nil {
		return x.xxx_hidden_DryRun
	}
	return false
}

func (x *UploadUsingProgrammerRequest) GetUserFields() map[string]string {
	if x != nil {
		return x.xxx_hidden_UserFields
	}
	return nil
}

func (x *UploadUsingProgrammerRequest) GetUploadProperties() []string {
	if x != nil {
		return x.xxx_hidden_UploadProperties
	}
	return nil
}

func (x *UploadUsingProgrammerRequest) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *UploadUsingProgrammerRequest) SetFqbn(v string) {
	x.xxx_hidden_Fqbn = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 12)
}

func (x *UploadUsingProgrammerRequest) SetSketchPath(v string) {
	x.xxx_hidden_SketchPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 12)
}

func (x *UploadUsingProgrammerRequest) SetPort(v *Port) {
	x.xxx_hidden_Port = v
}

func (x *UploadUsingProgrammerRequest) SetVerbose(v bool) {
	x.xxx_hidden_Verbose = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *UploadUsingProgrammerRequest) SetVerify(v bool) {
	x.xxx_hidden_Verify = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *UploadUsingProgrammerRequest) SetImportFile(v string) {
	x.xxx_hidden_ImportFile = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 12)
}

func (x *UploadUsingProgrammerRequest) SetImportDir(v string) {
	x.xxx_hidden_ImportDir = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 12)
}

func (x *UploadUsingProgrammerRequest) SetProgrammer(v string) {
	x.xxx_hidden_Programmer = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 12)
}

func (x *UploadUsingProgrammerRequest) SetDryRun(v bool) {
	x.xxx_hidden_DryRun = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 12)
}

func (x *UploadUsingProgrammerRequest) SetUserFields(v map[string]string) {
	x.xxx_hidden_UserFields = v
}

func (x *UploadUsingProgrammerRequest) SetUploadProperties(v []string) {
	x.xxx_hidden_UploadProperties = v
}

func (x *UploadUsingProgrammerRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *UploadUsingProgrammerRequest) HasFqbn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UploadUsingProgrammerRequest) HasSketchPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UploadUsingProgrammerRequest) HasPort() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Port != nil
}

func (x *UploadUsingProgrammerRequest) HasVerbose() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UploadUsingProgrammerRequest) HasVerify() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *UploadUsingProgrammerRequest) HasImportFile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *UploadUsingProgrammerRequest) HasImportDir() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *UploadUsingProgrammerRequest) HasProgrammer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *UploadUsingProgrammerRequest) HasDryRun() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *UploadUsingProgrammerRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

func (x *UploadUsingProgrammerRequest) ClearFqbn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Fqbn = nil
}

func (x *UploadUsingProgrammerRequest) ClearSketchPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SketchPath = nil
}

func (x *UploadUsingProgrammerRequest) ClearPort() {
	x.xxx_hidden_Port = nil
}

func (x *UploadUsingProgrammerRequest) ClearVerbose() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Verbose = false
}

func (x *UploadUsingProgrammerRequest) ClearVerify() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Verify = false
}

func (x *UploadUsingProgrammerRequest) ClearImportFile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_ImportFile = nil
}

func (x *UploadUsingProgrammerRequest) ClearImportDir() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_ImportDir = nil
}

func (x *UploadUsingProgrammerRequest) ClearProgrammer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Programmer = nil
}

func (x *UploadUsingProgrammerRequest) ClearDryRun() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_DryRun = false
}

type UploadUsingProgrammerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Arduino Core Service instance from the `Init` response.
	Instance *Instance
	// Fully qualified board name of the target board (e.g., `arduino:avr:uno`).
	// If this field is not defined, the FQBN of the board attached to the sketch
	// via the `BoardAttach` method is used.
	Fqbn *string
	// Path where the sketch to be uploaded is stored. Unless the `import_file`
	// field is defined, the compiled binary is assumed to be at the location and
	// filename under this path where it is saved by the `Compile` method.
	SketchPath *string
	// The port of the board.
	Port *Port
	// Whether to turn on verbose output during the upload.
	Verbose *bool
	// After upload, verify that the contents of the memory on the board match the
	// uploaded binary.
	Verify *bool
	// When `import_file` is specified, it overrides the `import_dir` and
	// `sketch_path` params.
	ImportFile *string
	// Custom path to a directory containing compiled files. When `import_dir` is
	// not specified, the standard build directory under `sketch_path` is used.
	ImportDir *string
	// The programmer to use for upload.
	Programmer *string
	// If set to true, the actual upload will not be performed but a trace output
	// will be printed stdout. This is for debugging purposes.
	DryRun *bool
	// User provided fields usually used by upload tools that need authentication
	// or in any case fields that can be customized by the user at upload time
	// and cannot be known previously.
	// For more info:
	// https://arduino.github.io/arduino-cli/latest/platform-specification/#user-provided-fields
	UserFields map[string]string
	// List of custom upload properties.
	UploadProperties []string
}

func (b0 UploadUsingProgrammerRequest_builder) Build() *UploadUsingProgrammerRequest {
	m0 := &UploadUsingProgrammerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	if b.Fqbn != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 12)
		x.xxx_hidden_Fqbn = b.Fqbn
	}
	if b.SketchPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 12)
		x.xxx_hidden_SketchPath = b.SketchPath
	}
	x.xxx_hidden_Port = b.Port
	if b.Verbose != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_Verbose = *b.Verbose
	}
	if b.Verify != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_Verify = *b.Verify
	}
	if b.ImportFile != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 12)
		x.xxx_hidden_ImportFile = b.ImportFile
	}
	if b.ImportDir != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 12)
		x.xxx_hidden_ImportDir = b.ImportDir
	}
	if b.Programmer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 12)
		x.xxx_hidden_Programmer = b.Programmer
	}
	if b.DryRun != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 12)
		x.xxx_hidden_DryRun = *b.DryRun
	}
	x.xxx_hidden_UserFields = b.UserFields
	x.xxx_hidden_UploadProperties = b.UploadProperties
	return m0
}

type UploadUsingProgrammerResponse struct {
	state              protoimpl.MessageState                  `protogen:"opaque.v1"`
	xxx_hidden_Message isUploadUsingProgrammerResponse_Message `protobuf_oneof:"message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadUsingProgrammerResponse) Reset() {
	*x = UploadUsingProgrammerResponse{}
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadUsingProgrammerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadUsingProgrammerResponse) ProtoMessage() {}

func (x *UploadUsingProgrammerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadUsingProgrammerResponse) GetOutStream() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*uploadUsingProgrammerResponse_OutStream); ok {
			return x.OutStream
		}
	}
	return nil
}

func (x *UploadUsingProgrammerResponse) GetErrStream() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*uploadUsingProgrammerResponse_ErrStream); ok {
			return x.ErrStream
		}
	}
	return nil
}

func (x *UploadUsingProgrammerResponse) SetOutStream(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Message = &uploadUsingProgrammerResponse_OutStream{v}
}

func (x *UploadUsingProgrammerResponse) SetErrStream(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Message = &uploadUsingProgrammerResponse_ErrStream{v}
}

func (x *UploadUsingProgrammerResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *UploadUsingProgrammerResponse) HasOutStream() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*uploadUsingProgrammerResponse_OutStream)
	return ok
}

func (x *UploadUsingProgrammerResponse) HasErrStream() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*uploadUsingProgrammerResponse_ErrStream)
	return ok
}

func (x *UploadUsingProgrammerResponse) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *UploadUsingProgrammerResponse) ClearOutStream() {
	if _, ok := x.xxx_hidden_Message.(*uploadUsingProgrammerResponse_OutStream); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *UploadUsingProgrammerResponse) ClearErrStream() {
	if _, ok := x.xxx_hidden_Message.(*uploadUsingProgrammerResponse_ErrStream); ok {
		x.xxx_hidden_Message = nil
	}
}

const UploadUsingProgrammerResponse_Message_not_set_case case_UploadUsingProgrammerResponse_Message = 0
const UploadUsingProgrammerResponse_OutStream_case case_UploadUsingProgrammerResponse_Message = 1
const UploadUsingProgrammerResponse_ErrStream_case case_UploadUsingProgrammerResponse_Message = 2

func (x *UploadUsingProgrammerResponse) WhichMessage() case_UploadUsingProgrammerResponse_Message {
	if x == nil {
		return UploadUsingProgrammerResponse_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *uploadUsingProgrammerResponse_OutStream:
		return UploadUsingProgrammerResponse_OutStream_case
	case *uploadUsingProgrammerResponse_ErrStream:
		return UploadUsingProgrammerResponse_ErrStream_case
	default:
		return UploadUsingProgrammerResponse_Message_not_set_case
	}
}

type UploadUsingProgrammerResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Message:
	// The output of the upload process.
	OutStream []byte
	// The error output of the upload process.
	ErrStream []byte
	// -- end of xxx_hidden_Message
}

func (b0 UploadUsingProgrammerResponse_builder) Build() *UploadUsingProgrammerResponse {
	m0 := &UploadUsingProgrammerResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.OutStream != nil {
		x.xxx_hidden_Message = &uploadUsingProgrammerResponse_OutStream{b.OutStream}
	}
	if b.ErrStream != nil {
		x.xxx_hidden_Message = &uploadUsingProgrammerResponse_ErrStream{b.ErrStream}
	}
	return m0
}

type case_UploadUsingProgrammerResponse_Message protoreflect.FieldNumber

func (x case_UploadUsingProgrammerResponse_Message) String() string {
	md := file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[5].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUploadUsingProgrammerResponse_Message interface {
	isUploadUsingProgrammerResponse_Message()
}

type uploadUsingProgrammerResponse_OutStream struct {
	// The output of the upload process.
	OutStream []byte `protobuf:"bytes,1,opt,name=out_stream,json=outStream,oneof"`
}

type uploadUsingProgrammerResponse_ErrStream struct {
	// The error output of the upload process.
	ErrStream []byte `protobuf:"bytes,2,opt,name=err_stream,json=errStream,oneof"`
}

func (*uploadUsingProgrammerResponse_OutStream) isUploadUsingProgrammerResponse_Message() {}

func (*uploadUsingProgrammerResponse_ErrStream) isUploadUsingProgrammerResponse_Message() {}

type BurnBootloaderRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance         *Instance              `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	xxx_hidden_Fqbn             *string                `protobuf:"bytes,2,opt,name=fqbn" json:"fqbn,omitempty"`
	xxx_hidden_Port             *Port                  `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	xxx_hidden_Verbose          bool                   `protobuf:"varint,4,opt,name=verbose" json:"verbose,omitempty"`
	xxx_hidden_Verify           bool                   `protobuf:"varint,5,opt,name=verify" json:"verify,omitempty"`
	xxx_hidden_Programmer       *string                `protobuf:"bytes,6,opt,name=programmer" json:"programmer,omitempty"`
	xxx_hidden_DryRun           bool                   `protobuf:"varint,7,opt,name=dry_run,json=dryRun" json:"dry_run,omitempty"`
	xxx_hidden_UserFields       map[string]string      `protobuf:"bytes,11,rep,name=user_fields,json=userFields" json:"user_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_UploadProperties []string               `protobuf:"bytes,12,rep,name=upload_properties,json=uploadProperties" json:"upload_properties,omitempty"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *BurnBootloaderRequest) Reset() {
	*x = BurnBootloaderRequest{}
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnBootloaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnBootloaderRequest) ProtoMessage() {}

func (x *BurnBootloaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BurnBootloaderRequest) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *BurnBootloaderRequest) GetFqbn() string {
	if x != nil {
		if x.xxx_hidden_Fqbn != nil {
			return *x.xxx_hidden_Fqbn
		}
		return ""
	}
	return ""
}

func (x *BurnBootloaderRequest) GetPort() *Port {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return nil
}

func (x *BurnBootloaderRequest) GetVerbose() bool {
	if x != nil {
		return x.xxx_hidden_Verbose
	}
	return false
}

func (x *BurnBootloaderRequest) GetVerify() bool {
	if x != nil {
		return x.xxx_hidden_Verify
	}
	return false
}

func (x *BurnBootloaderRequest) GetProgrammer() string {
	if x != nil {
		if x.xxx_hidden_Programmer != nil {
			return *x.xxx_hidden_Programmer
		}
		return ""
	}
	return ""
}

func (x *BurnBootloaderRequest) GetDryRun() bool {
	if x != nil {
		return x.xxx_hidden_DryRun
	}
	return false
}

func (x *BurnBootloaderRequest) GetUserFields() map[string]string {
	if x != nil {
		return x.xxx_hidden_UserFields
	}
	return nil
}

func (x *BurnBootloaderRequest) GetUploadProperties() []string {
	if x != nil {
		return x.xxx_hidden_UploadProperties
	}
	return nil
}

func (x *BurnBootloaderRequest) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *BurnBootloaderRequest) SetFqbn(v string) {
	x.xxx_hidden_Fqbn = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *BurnBootloaderRequest) SetPort(v *Port) {
	x.xxx_hidden_Port = v
}

func (x *BurnBootloaderRequest) SetVerbose(v bool) {
	x.xxx_hidden_Verbose = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *BurnBootloaderRequest) SetVerify(v bool) {
	x.xxx_hidden_Verify = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *BurnBootloaderRequest) SetProgrammer(v string) {
	x.xxx_hidden_Programmer = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *BurnBootloaderRequest) SetDryRun(v bool) {
	x.xxx_hidden_DryRun = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *BurnBootloaderRequest) SetUserFields(v map[string]string) {
	x.xxx_hidden_UserFields = v
}

func (x *BurnBootloaderRequest) SetUploadProperties(v []string) {
	x.xxx_hidden_UploadProperties = v
}

func (x *BurnBootloaderRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *BurnBootloaderRequest) HasFqbn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *BurnBootloaderRequest) HasPort() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Port != nil
}

func (x *BurnBootloaderRequest) HasVerbose() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *BurnBootloaderRequest) HasVerify() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *BurnBootloaderRequest) HasProgrammer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *BurnBootloaderRequest) HasDryRun() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *BurnBootloaderRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

func (x *BurnBootloaderRequest) ClearFqbn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Fqbn = nil
}

func (x *BurnBootloaderRequest) ClearPort() {
	x.xxx_hidden_Port = nil
}

func (x *BurnBootloaderRequest) ClearVerbose() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Verbose = false
}

func (x *BurnBootloaderRequest) ClearVerify() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Verify = false
}

func (x *BurnBootloaderRequest) ClearProgrammer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Programmer = nil
}

func (x *BurnBootloaderRequest) ClearDryRun() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DryRun = false
}

type BurnBootloaderRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Arduino Core Service instance from the `Init` response.
	Instance *Instance
	// Fully qualified board name of the target board (e.g., `arduino:avr:uno`).
	Fqbn *string
	// The port of the programmer used to program the bootloader.
	Port *Port
	// Whether to turn on verbose output during the programming.
	Verbose *bool
	// After programming, verify the contents of the memory on the board match the
	// uploaded binary.
	Verify *bool
	// The programmer to use for burning bootloader.
	Programmer *string
	// If set to true, the actual upload will not be performed but a trace output
	// will be printed stdout. This is for debugging purposes.
	DryRun *bool
	// User provided fields usually used by upload tools that need authentication
	// or in any case fields that can be customized by the user at upload time
	// and cannot be known previously.
	// For more info:
	// https://arduino.github.io/arduino-cli/latest/platform-specification/#user-provided-fields
	UserFields map[string]string
	// List of custom upload properties.
	UploadProperties []string
}

func (b0 BurnBootloaderRequest_builder) Build() *BurnBootloaderRequest {
	m0 := &BurnBootloaderRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	if b.Fqbn != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Fqbn = b.Fqbn
	}
	x.xxx_hidden_Port = b.Port
	if b.Verbose != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Verbose = *b.Verbose
	}
	if b.Verify != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Verify = *b.Verify
	}
	if b.Programmer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Programmer = b.Programmer
	}
	if b.DryRun != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_DryRun = *b.DryRun
	}
	x.xxx_hidden_UserFields = b.UserFields
	x.xxx_hidden_UploadProperties = b.UploadProperties
	return m0
}

type BurnBootloaderResponse struct {
	state              protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Message isBurnBootloaderResponse_Message `protobuf_oneof:"message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BurnBootloaderResponse) Reset() {
	*x = BurnBootloaderResponse{}
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnBootloaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnBootloaderResponse) ProtoMessage() {}

func (x *BurnBootloaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BurnBootloaderResponse) GetOutStream() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*burnBootloaderResponse_OutStream); ok {
			return x.OutStream
		}
	}
	return nil
}

func (x *BurnBootloaderResponse) GetErrStream() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*burnBootloaderResponse_ErrStream); ok {
			return x.ErrStream
		}
	}
	return nil
}

func (x *BurnBootloaderResponse) SetOutStream(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Message = &burnBootloaderResponse_OutStream{v}
}

func (x *BurnBootloaderResponse) SetErrStream(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Message = &burnBootloaderResponse_ErrStream{v}
}

func (x *BurnBootloaderResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *BurnBootloaderResponse) HasOutStream() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*burnBootloaderResponse_OutStream)
	return ok
}

func (x *BurnBootloaderResponse) HasErrStream() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*burnBootloaderResponse_ErrStream)
	return ok
}

func (x *BurnBootloaderResponse) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *BurnBootloaderResponse) ClearOutStream() {
	if _, ok := x.xxx_hidden_Message.(*burnBootloaderResponse_OutStream); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *BurnBootloaderResponse) ClearErrStream() {
	if _, ok := x.xxx_hidden_Message.(*burnBootloaderResponse_ErrStream); ok {
		x.xxx_hidden_Message = nil
	}
}

const BurnBootloaderResponse_Message_not_set_case case_BurnBootloaderResponse_Message = 0
const BurnBootloaderResponse_OutStream_case case_BurnBootloaderResponse_Message = 1
const BurnBootloaderResponse_ErrStream_case case_BurnBootloaderResponse_Message = 2

func (x *BurnBootloaderResponse) WhichMessage() case_BurnBootloaderResponse_Message {
	if x == nil {
		return BurnBootloaderResponse_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *burnBootloaderResponse_OutStream:
		return BurnBootloaderResponse_OutStream_case
	case *burnBootloaderResponse_ErrStream:
		return BurnBootloaderResponse_ErrStream_case
	default:
		return BurnBootloaderResponse_Message_not_set_case
	}
}

type BurnBootloaderResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Message:
	// The output of the burn bootloader process.
	OutStream []byte
	// The error output of the burn bootloader process.
	ErrStream []byte
	// -- end of xxx_hidden_Message
}

func (b0 BurnBootloaderResponse_builder) Build() *BurnBootloaderResponse {
	m0 := &BurnBootloaderResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.OutStream != nil {
		x.xxx_hidden_Message = &burnBootloaderResponse_OutStream{b.OutStream}
	}
	if b.ErrStream != nil {
		x.xxx_hidden_Message = &burnBootloaderResponse_ErrStream{b.ErrStream}
	}
	return m0
}

type case_BurnBootloaderResponse_Message protoreflect.FieldNumber

func (x case_BurnBootloaderResponse_Message) String() string {
	md := file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[7].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isBurnBootloaderResponse_Message interface {
	isBurnBootloaderResponse_Message()
}

type burnBootloaderResponse_OutStream struct {
	// The output of the burn bootloader process.
	OutStream []byte `protobuf:"bytes,1,opt,name=out_stream,json=outStream,oneof"`
}

type burnBootloaderResponse_ErrStream struct {
	// The error output of the burn bootloader process.
	ErrStream []byte `protobuf:"bytes,2,opt,name=err_stream,json=errStream,oneof"`
}

func (*burnBootloaderResponse_OutStream) isBurnBootloaderResponse_Message() {}

func (*burnBootloaderResponse_ErrStream) isBurnBootloaderResponse_Message() {}

type ListProgrammersAvailableForUploadRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance    *Instance              `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	xxx_hidden_Fqbn        *string                `protobuf:"bytes,2,opt,name=fqbn" json:"fqbn,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListProgrammersAvailableForUploadRequest) Reset() {
	*x = ListProgrammersAvailableForUploadRequest{}
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProgrammersAvailableForUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProgrammersAvailableForUploadRequest) ProtoMessage() {}

func (x *ListProgrammersAvailableForUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListProgrammersAvailableForUploadRequest) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *ListProgrammersAvailableForUploadRequest) GetFqbn() string {
	if x != nil {
		if x.xxx_hidden_Fqbn != nil {
			return *x.xxx_hidden_Fqbn
		}
		return ""
	}
	return ""
}

func (x *ListProgrammersAvailableForUploadRequest) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *ListProgrammersAvailableForUploadRequest) SetFqbn(v string) {
	x.xxx_hidden_Fqbn = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ListProgrammersAvailableForUploadRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *ListProgrammersAvailableForUploadRequest) HasFqbn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListProgrammersAvailableForUploadRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

func (x *ListProgrammersAvailableForUploadRequest) ClearFqbn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Fqbn = nil
}

type ListProgrammersAvailableForUploadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Arduino Core Service instance from the `Init` response.
	Instance *Instance
	// Fully qualified board name of the target board (e.g., `arduino:avr:uno`).
	Fqbn *string
}

func (b0 ListProgrammersAvailableForUploadRequest_builder) Build() *ListProgrammersAvailableForUploadRequest {
	m0 := &ListProgrammersAvailableForUploadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	if b.Fqbn != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Fqbn = b.Fqbn
	}
	return m0
}

type ListProgrammersAvailableForUploadResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Programmers *[]*Programmer         `protobuf:"bytes,1,rep,name=programmers" json:"programmers,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListProgrammersAvailableForUploadResponse) Reset() {
	*x = ListProgrammersAvailableForUploadResponse{}
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProgrammersAvailableForUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProgrammersAvailableForUploadResponse) ProtoMessage() {}

func (x *ListProgrammersAvailableForUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListProgrammersAvailableForUploadResponse) GetProgrammers() []*Programmer {
	if x != nil {
		if x.xxx_hidden_Programmers != nil {
			return *x.xxx_hidden_Programmers
		}
	}
	return nil
}

func (x *ListProgrammersAvailableForUploadResponse) SetProgrammers(v []*Programmer) {
	x.xxx_hidden_Programmers = &v
}

type ListProgrammersAvailableForUploadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// List of programmers supported by the board.
	Programmers []*Programmer
}

func (b0 ListProgrammersAvailableForUploadResponse_builder) Build() *ListProgrammersAvailableForUploadResponse {
	m0 := &ListProgrammersAvailableForUploadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Programmers = &b.Programmers
	return m0
}

type SupportedUserFieldsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance    *Instance              `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	xxx_hidden_Fqbn        *string                `protobuf:"bytes,2,opt,name=fqbn" json:"fqbn,omitempty"`
	xxx_hidden_Protocol    *string                `protobuf:"bytes,3,opt,name=protocol" json:"protocol,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SupportedUserFieldsRequest) Reset() {
	*x = SupportedUserFieldsRequest{}
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedUserFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedUserFieldsRequest) ProtoMessage() {}

func (x *SupportedUserFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SupportedUserFieldsRequest) GetInstance() *Instance {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *SupportedUserFieldsRequest) GetFqbn() string {
	if x != nil {
		if x.xxx_hidden_Fqbn != nil {
			return *x.xxx_hidden_Fqbn
		}
		return ""
	}
	return ""
}

func (x *SupportedUserFieldsRequest) GetProtocol() string {
	if x != nil {
		if x.xxx_hidden_Protocol != nil {
			return *x.xxx_hidden_Protocol
		}
		return ""
	}
	return ""
}

func (x *SupportedUserFieldsRequest) SetInstance(v *Instance) {
	x.xxx_hidden_Instance = v
}

func (x *SupportedUserFieldsRequest) SetFqbn(v string) {
	x.xxx_hidden_Fqbn = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *SupportedUserFieldsRequest) SetProtocol(v string) {
	x.xxx_hidden_Protocol = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *SupportedUserFieldsRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *SupportedUserFieldsRequest) HasFqbn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SupportedUserFieldsRequest) HasProtocol() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SupportedUserFieldsRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

func (x *SupportedUserFieldsRequest) ClearFqbn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Fqbn = nil
}

func (x *SupportedUserFieldsRequest) ClearProtocol() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Protocol = nil
}

type SupportedUserFieldsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Arduino Core Service instance from the `Init` response.
	Instance *Instance
	// Fully qualified board name of the target board (e.g., `arduino:avr:uno`).
	Fqbn *string
	// Protocol that will be used to upload, this information is
	// necessary to pick the right upload tool for the board specified
	// with the FQBN.
	Protocol *string
}

func (b0 SupportedUserFieldsRequest_builder) Build() *SupportedUserFieldsRequest {
	m0 := &SupportedUserFieldsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	if b.Fqbn != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Fqbn = b.Fqbn
	}
	if b.Protocol != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Protocol = b.Protocol
	}
	return m0
}

type UserField struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ToolId      *string                `protobuf:"bytes,1,opt,name=tool_id,json=toolId" json:"tool_id,omitempty"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	xxx_hidden_Label       *string                `protobuf:"bytes,3,opt,name=label" json:"label,omitempty"`
	xxx_hidden_Secret      bool                   `protobuf:"varint,4,opt,name=secret" json:"secret,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserField) Reset() {
	*x = UserField{}
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserField) ProtoMessage() {}

func (x *UserField) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserField) GetToolId() string {
	if x != nil {
		if x.xxx_hidden_ToolId != nil {
			return *x.xxx_hidden_ToolId
		}
		return ""
	}
	return ""
}

func (x *UserField) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *UserField) GetLabel() string {
	if x != nil {
		if x.xxx_hidden_Label != nil {
			return *x.xxx_hidden_Label
		}
		return ""
	}
	return ""
}

func (x *UserField) GetSecret() bool {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return false
}

func (x *UserField) SetToolId(v string) {
	x.xxx_hidden_ToolId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *UserField) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *UserField) SetLabel(v string) {
	x.xxx_hidden_Label = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *UserField) SetSecret(v bool) {
	x.xxx_hidden_Secret = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *UserField) HasToolId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserField) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UserField) HasLabel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UserField) HasSecret() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UserField) ClearToolId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ToolId = nil
}

func (x *UserField) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *UserField) ClearLabel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Label = nil
}

func (x *UserField) ClearSecret() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Secret = false
}

type UserField_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Id of the tool that supports this field.
	ToolId *string
	// Name used internally to store and retrieve this field.
	Name *string
	// Label is the text shown to the user when they need to input this field.
	Label *string
	// True if the value of the field must not be shown when typing, for example
	// when the user inputs a network password.
	Secret *bool
}

func (b0 UserField_builder) Build() *UserField {
	m0 := &UserField{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ToolId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_ToolId = b.ToolId
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Name = b.Name
	}
	if b.Label != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Label = b.Label
	}
	if b.Secret != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Secret = *b.Secret
	}
	return m0
}

type SupportedUserFieldsResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserFields *[]*UserField          `protobuf:"bytes,1,rep,name=user_fields,json=userFields" json:"user_fields,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SupportedUserFieldsResponse) Reset() {
	*x = SupportedUserFieldsResponse{}
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedUserFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedUserFieldsResponse) ProtoMessage() {}

func (x *SupportedUserFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SupportedUserFieldsResponse) GetUserFields() []*UserField {
	if x != nil {
		if x.xxx_hidden_UserFields != nil {
			return *x.xxx_hidden_UserFields
		}
	}
	return nil
}

func (x *SupportedUserFieldsResponse) SetUserFields(v []*UserField) {
	x.xxx_hidden_UserFields = &v
}

type SupportedUserFieldsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// User fields supported by board specified in SupportedUserFieldsRequest.
	// If board doesn't support any field it will be empty.
	UserFields []*UserField
}

func (b0 SupportedUserFieldsResponse_builder) Build() *SupportedUserFieldsResponse {
	m0 := &SupportedUserFieldsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserFields = &b.UserFields
	return m0
}

var File_cc_arduino_cli_commands_v1_upload_proto protoreflect.FileDescriptor

var file_cc_arduino_cli_commands_v1_upload_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x69,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x63, 0x63, 0x2e, 0x61, 0x72,
	0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x27, 0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e,
	0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25,
	0x63, 0x63, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf, 0x04, 0x0a, 0x0d, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63,
	0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x71, 0x62, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x71, 0x62, 0x6e,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x34, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x72,
	0x74, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x62, 0x6f,
	0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x69, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x72, 0x79,
	0x5f, 0x72, 0x75, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x72, 0x79, 0x52,
	0x75, 0x6e, 0x12, 0x5a, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64,
	0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x2b,
	0x0a, 0x11, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x55,
	0x73, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa1, 0x01, 0x0a, 0x0e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x0a, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1f,
	0x0a, 0x0a, 0x65, 0x72, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x65, 0x72, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x42, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x28, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x60,
	0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x50,
	0x0a, 0x13, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x63,
	0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x11, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x6f, 0x72, 0x74,
	0x22, 0x24, 0x0a, 0x22, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x49, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xcd, 0x04, 0x0a, 0x1c, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x63, 0x2e, 0x61,
	0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x71, 0x62,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x71, 0x62, 0x6e, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x50, 0x61, 0x74, 0x68, 0x12, 0x34,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63,
	0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x44, 0x69, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61,
	0x6d, 0x6d, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x72, 0x79, 0x5f, 0x72, 0x75,
	0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x72, 0x79, 0x52, 0x75, 0x6e, 0x12,
	0x69, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x0b,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x48, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e,
	0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a,
	0x75, 0x73, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x75, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18,
	0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x6c, 0x0a, 0x1d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x55, 0x73, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x5f, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x6f,
	0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1f, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x5f,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09,
	0x65, 0x72, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0xde, 0x03, 0x0a, 0x15, 0x42, 0x75, 0x72, 0x6e, 0x42, 0x6f, 0x6f,
	0x74, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40,
	0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x71, 0x62, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x66, 0x71, 0x62, 0x6e, 0x12, 0x34, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e,
	0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x62, 0x6f, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x62, 0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x1e, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07,
	0x64, 0x72, 0x79, 0x5f, 0x72, 0x75, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64,
	0x72, 0x79, 0x52, 0x75, 0x6e, 0x12, 0x62, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x63, 0x63, 0x2e,
	0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x72, 0x6e, 0x42, 0x6f, 0x6f, 0x74,
	0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x75,
	0x73, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x0c,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x65, 0x0a, 0x16, 0x42, 0x75, 0x72, 0x6e, 0x42, 0x6f, 0x6f,
	0x74, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x12, 0x1f, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x65, 0x72, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x80, 0x01, 0x0a,
	0x28, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x73,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x6f, 0x72, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x63,
	0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x71, 0x62, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x71, 0x62, 0x6e, 0x22,
	0x75, 0x0a, 0x29, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65,
	0x72, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x6f, 0x72, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0b,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63,
	0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x6d, 0x65, 0x72, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x1a, 0x53, 0x75, 0x70, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64,
	0x75, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x71, 0x62, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x71, 0x62, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x66, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22,
	0x65, 0x0a, 0x1b, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46,
	0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x63, 0x2e, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f,
	0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x42, 0x50, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x72, 0x64,
	0x75, 0x69, 0x6e, 0x6f, 0x2d, 0x63, 0x6c, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x63, 0x2f,
	0x61, 0x72, 0x64, 0x75, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x92, 0x03, 0x05, 0xd2, 0x3e, 0x02, 0x10, 0x03, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x70, 0xe8, 0x07,
}

var file_cc_arduino_cli_commands_v1_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_cc_arduino_cli_commands_v1_upload_proto_goTypes = []any{
	(*UploadRequest)(nil),                             // 0: cc.arduino.cli.commands.v1.UploadRequest
	(*UploadResponse)(nil),                            // 1: cc.arduino.cli.commands.v1.UploadResponse
	(*UploadResult)(nil),                              // 2: cc.arduino.cli.commands.v1.UploadResult
	(*ProgrammerIsRequiredForUploadError)(nil),        // 3: cc.arduino.cli.commands.v1.ProgrammerIsRequiredForUploadError
	(*UploadUsingProgrammerRequest)(nil),              // 4: cc.arduino.cli.commands.v1.UploadUsingProgrammerRequest
	(*UploadUsingProgrammerResponse)(nil),             // 5: cc.arduino.cli.commands.v1.UploadUsingProgrammerResponse
	(*BurnBootloaderRequest)(nil),                     // 6: cc.arduino.cli.commands.v1.BurnBootloaderRequest
	(*BurnBootloaderResponse)(nil),                    // 7: cc.arduino.cli.commands.v1.BurnBootloaderResponse
	(*ListProgrammersAvailableForUploadRequest)(nil),  // 8: cc.arduino.cli.commands.v1.ListProgrammersAvailableForUploadRequest
	(*ListProgrammersAvailableForUploadResponse)(nil), // 9: cc.arduino.cli.commands.v1.ListProgrammersAvailableForUploadResponse
	(*SupportedUserFieldsRequest)(nil),                // 10: cc.arduino.cli.commands.v1.SupportedUserFieldsRequest
	(*UserField)(nil),                                 // 11: cc.arduino.cli.commands.v1.UserField
	(*SupportedUserFieldsResponse)(nil),               // 12: cc.arduino.cli.commands.v1.SupportedUserFieldsResponse
	nil,                                               // 13: cc.arduino.cli.commands.v1.UploadRequest.UserFieldsEntry
	nil,                                               // 14: cc.arduino.cli.commands.v1.UploadUsingProgrammerRequest.UserFieldsEntry
	nil,                                               // 15: cc.arduino.cli.commands.v1.BurnBootloaderRequest.UserFieldsEntry
	(*Instance)(nil),                                  // 16: cc.arduino.cli.commands.v1.Instance
	(*Port)(nil),                                      // 17: cc.arduino.cli.commands.v1.Port
	(*Programmer)(nil),                                // 18: cc.arduino.cli.commands.v1.Programmer
}
var file_cc_arduino_cli_commands_v1_upload_proto_depIdxs = []int32{
	16, // 0: cc.arduino.cli.commands.v1.UploadRequest.instance:type_name -> cc.arduino.cli.commands.v1.Instance
	17, // 1: cc.arduino.cli.commands.v1.UploadRequest.port:type_name -> cc.arduino.cli.commands.v1.Port
	13, // 2: cc.arduino.cli.commands.v1.UploadRequest.user_fields:type_name -> cc.arduino.cli.commands.v1.UploadRequest.UserFieldsEntry
	2,  // 3: cc.arduino.cli.commands.v1.UploadResponse.result:type_name -> cc.arduino.cli.commands.v1.UploadResult
	17, // 4: cc.arduino.cli.commands.v1.UploadResult.updated_upload_port:type_name -> cc.arduino.cli.commands.v1.Port
	16, // 5: cc.arduino.cli.commands.v1.UploadUsingProgrammerRequest.instance:type_name -> cc.arduino.cli.commands.v1.Instance
	17, // 6: cc.arduino.cli.commands.v1.UploadUsingProgrammerRequest.port:type_name -> cc.arduino.cli.commands.v1.Port
	14, // 7: cc.arduino.cli.commands.v1.UploadUsingProgrammerRequest.user_fields:type_name -> cc.arduino.cli.commands.v1.UploadUsingProgrammerRequest.UserFieldsEntry
	16, // 8: cc.arduino.cli.commands.v1.BurnBootloaderRequest.instance:type_name -> cc.arduino.cli.commands.v1.Instance
	17, // 9: cc.arduino.cli.commands.v1.BurnBootloaderRequest.port:type_name -> cc.arduino.cli.commands.v1.Port
	15, // 10: cc.arduino.cli.commands.v1.BurnBootloaderRequest.user_fields:type_name -> cc.arduino.cli.commands.v1.BurnBootloaderRequest.UserFieldsEntry
	16, // 11: cc.arduino.cli.commands.v1.ListProgrammersAvailableForUploadRequest.instance:type_name -> cc.arduino.cli.commands.v1.Instance
	18, // 12: cc.arduino.cli.commands.v1.ListProgrammersAvailableForUploadResponse.programmers:type_name -> cc.arduino.cli.commands.v1.Programmer
	16, // 13: cc.arduino.cli.commands.v1.SupportedUserFieldsRequest.instance:type_name -> cc.arduino.cli.commands.v1.Instance
	11, // 14: cc.arduino.cli.commands.v1.SupportedUserFieldsResponse.user_fields:type_name -> cc.arduino.cli.commands.v1.UserField
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_cc_arduino_cli_commands_v1_upload_proto_init() }
func file_cc_arduino_cli_commands_v1_upload_proto_init() {
	if File_cc_arduino_cli_commands_v1_upload_proto != nil {
		return
	}
	file_cc_arduino_cli_commands_v1_common_proto_init()
	file_cc_arduino_cli_commands_v1_port_proto_init()
	file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[1].OneofWrappers = []any{
		(*uploadResponse_OutStream)(nil),
		(*uploadResponse_ErrStream)(nil),
		(*uploadResponse_Result)(nil),
	}
	file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[5].OneofWrappers = []any{
		(*uploadUsingProgrammerResponse_OutStream)(nil),
		(*uploadUsingProgrammerResponse_ErrStream)(nil),
	}
	file_cc_arduino_cli_commands_v1_upload_proto_msgTypes[7].OneofWrappers = []any{
		(*burnBootloaderResponse_OutStream)(nil),
		(*burnBootloaderResponse_ErrStream)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cc_arduino_cli_commands_v1_upload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cc_arduino_cli_commands_v1_upload_proto_goTypes,
		DependencyIndexes: file_cc_arduino_cli_commands_v1_upload_proto_depIdxs,
		MessageInfos:      file_cc_arduino_cli_commands_v1_upload_proto_msgTypes,
	}.Build()
	File_cc_arduino_cli_commands_v1_upload_proto = out.File
	file_cc_arduino_cli_commands_v1_upload_proto_rawDesc = nil
	file_cc_arduino_cli_commands_v1_upload_proto_goTypes = nil
	file_cc_arduino_cli_commands_v1_upload_proto_depIdxs = nil
}
